
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 10 2025 20:14:40 -03 (Jan 10 2025 23:14:40 UTC)

// Verification Directory fv/decodificador_pt2272 

module ADDRESS_INTERPRETER(A, INTERPRETED_ADDR, F_BIT_LOCATOR);
  input [7:0] A;
  output [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  wire [7:0] A;
  wire [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  comp_endereco comp_endereco(.A (A), .A_01 (INTERPRETED_ADDR), .A_F
       (F_BIT_LOCATOR));
endmodule

module decodificador_pt2272(clk, reset, A, cod_i, D, dv);
  input clk, reset, cod_i;
  input [7:0] A;
  output [3:0] D;
  output dv;
  wire clk, reset, cod_i;
  wire [7:0] A;
  wire [3:0] D;
  wire dv;
  wire [7:0] INTERPRETED_ADDR;
  wire [7:0] F_BIT_LOCATOR;
  wire [2:0] BIDIR_SHIFTREG_OP_MODE;
  wire [1:0] BIDIR_SHIFTREG_PT2272_BIT_IN;
  wire [4:0] HIGH_PULSE_COUNTING;
  wire [7:0] LOW_PULSE_COUNTING;
  wire [25:0] BIDIR_SHIFTREG_PARALLEL_OUT;
  wire [2:0] current_state;
  wire [7:0] internal_f_bit_locator;
  wire [7:0] internal_interpreted_addr;
  wire [6:0] internal_oscillator_clk_cycle_counting;
  wire PREVIOUS_cod_i, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, osc_clk, reset_counters;
  ADDRESS_INTERPRETER addr_translator(.A (A), .INTERPRETED_ADDR
       (INTERPRETED_ADDR), .F_BIT_LOCATOR (F_BIT_LOCATOR));
  INVXL g4685(.A (reset), .Y (n_289));
  DFFSHQX1 \BIDIR_SHIFTREG_OP_MODE_reg[1] (.SN (n_289), .CK (osc_clk),
       .D (n_188), .Q (BIDIR_SHIFTREG_OP_MODE[1]));
  DFFRHQX1 \BIDIR_SHIFTREG_OP_MODE_reg[2] (.RN (n_289), .CK (osc_clk),
       .D (n_189), .Q (BIDIR_SHIFTREG_OP_MODE[2]));
  DFFRHQX1 \BIDIR_SHIFTREG_PT2272_BIT_IN_reg[0] (.RN (n_289), .CK
       (osc_clk), .D (n_145), .Q (BIDIR_SHIFTREG_PT2272_BIT_IN[0]));
  DFFRHQX1 \BIDIR_SHIFTREG_PT2272_BIT_IN_reg[1] (.RN (n_289), .CK
       (osc_clk), .D (n_184), .Q (BIDIR_SHIFTREG_PT2272_BIT_IN[1]));
  DFFRHQX1 \D_reg[0] (.RN (n_289), .CK (osc_clk), .D (n_139), .Q
       (D[0]));
  DFFRHQX1 \D_reg[1] (.RN (n_289), .CK (osc_clk), .D (n_132), .Q
       (D[1]));
  DFFRHQX1 \D_reg[2] (.RN (n_289), .CK (osc_clk), .D (n_140), .Q
       (D[2]));
  DFFRHQX1 \D_reg[3] (.RN (n_289), .CK (osc_clk), .D (n_137), .Q
       (D[3]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[0] (.RN (n_289), .CK (osc_clk), .D
       (n_182), .Q (HIGH_PULSE_COUNTING[0]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[1] (.RN (n_289), .CK (osc_clk), .D
       (n_186), .Q (HIGH_PULSE_COUNTING[1]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[1] (.RN (n_289), .CK (osc_clk), .D
       (n_224), .Q (LOW_PULSE_COUNTING[1]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[6] (.RN (n_289), .CK (osc_clk), .D
       (n_286), .Q (LOW_PULSE_COUNTING[6]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[7] (.RN (n_289), .CK (osc_clk), .D
       (n_288), .Q (LOW_PULSE_COUNTING[7]));
  DFFRHQX1 PREVIOUS_cod_i_reg(.RN (n_289), .CK (cod_i), .D (cod_i), .Q
       (PREVIOUS_cod_i));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[0] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_212), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[0]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[1] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_225), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[1]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[2] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_217), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[3] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_238), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[3]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[4] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_246), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[5] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_218), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[6] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_236), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[6]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[7] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_234), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[8] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_211), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[8]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[9] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_215), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[10] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_209), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[10]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[11] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_233), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[12] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_214), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[13] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_235), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[14] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_213), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[14]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[15] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_216), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[16] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_240), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[16]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[17] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_239), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[18] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_222), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[18]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[19] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_221), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[20] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_243), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[20]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[21] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_220), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[21]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[22] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_242), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[23] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_219), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[24] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_226), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[24]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[25] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_210), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[25]));
  DFFRHQX1 \current_state_reg[1] (.RN (n_289), .CK (osc_clk), .D
       (n_258), .Q (current_state[1]));
  SDFFRHQX1 dv_reg(.RN (n_289), .CK (osc_clk), .D (n_262), .SI (dv),
       .SE (n_61), .Q (dv));
  SDFFRHQX1 \internal_f_bit_locator_reg[1] (.RN (n_289), .CK (osc_clk),
       .D (n_130), .SI (internal_f_bit_locator[1]), .SE (n_61), .Q
       (internal_f_bit_locator[1]));
  SDFFRHQX1 \internal_f_bit_locator_reg[2] (.RN (n_289), .CK (osc_clk),
       .D (n_75), .SI (internal_f_bit_locator[2]), .SE (n_61), .Q
       (internal_f_bit_locator[2]));
  SDFFRHQX1 \internal_f_bit_locator_reg[3] (.RN (n_289), .CK (osc_clk),
       .D (n_74), .SI (internal_f_bit_locator[3]), .SE (n_61), .Q
       (internal_f_bit_locator[3]));
  SDFFRHQX1 \internal_f_bit_locator_reg[4] (.RN (n_289), .CK (osc_clk),
       .D (n_72), .SI (internal_f_bit_locator[4]), .SE (n_61), .Q
       (internal_f_bit_locator[4]));
  SDFFRHQX1 \internal_f_bit_locator_reg[5] (.RN (n_289), .CK (osc_clk),
       .D (n_84), .SI (internal_f_bit_locator[5]), .SE (n_61), .Q
       (internal_f_bit_locator[5]));
  SDFFRHQX1 \internal_f_bit_locator_reg[6] (.RN (n_289), .CK (osc_clk),
       .D (n_0), .SI (internal_f_bit_locator[6]), .SE (n_61), .Q
       (internal_f_bit_locator[6]));
  SDFFRHQX1 \internal_f_bit_locator_reg[7] (.RN (n_289), .CK (osc_clk),
       .D (n_73), .SI (internal_f_bit_locator[7]), .SE (n_61), .Q
       (internal_f_bit_locator[7]));
  SDFFRHQX1 \internal_interpreted_addr_reg[0] (.RN (n_289), .CK
       (osc_clk), .D (n_49), .SI (internal_interpreted_addr[0]), .SE
       (n_61), .Q (internal_interpreted_addr[0]));
  DFFRHQX1 \internal_interpreted_addr_reg[3] (.RN (n_289), .CK
       (osc_clk), .D (n_175), .Q (internal_interpreted_addr[3]));
  DFFRHQX1 \internal_interpreted_addr_reg[4] (.RN (n_289), .CK
       (osc_clk), .D (n_174), .Q (internal_interpreted_addr[4]));
  DFFRHQX1 \internal_interpreted_addr_reg[5] (.RN (n_289), .CK
       (osc_clk), .D (n_173), .Q (internal_interpreted_addr[5]));
  DFFRHQX1 \internal_interpreted_addr_reg[6] (.RN (n_289), .CK
       (osc_clk), .D (n_181), .Q (internal_interpreted_addr[6]));
  SDFFRHQX1 internal_oscillator_OUTPUT_CLK_reg(.RN (n_289), .CK (clk),
       .D (n_227), .SI (n_228), .SE (osc_clk), .Q (osc_clk));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[0] (.RN (n_289),
       .CK (clk), .D (n_237), .Q
       (internal_oscillator_clk_cycle_counting[0]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[1] (.RN (n_289),
       .CK (clk), .D (n_241), .Q
       (internal_oscillator_clk_cycle_counting[1]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[3] (.RN (n_289),
       .CK (clk), .D (n_256), .Q
       (internal_oscillator_clk_cycle_counting[3]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[5] (.RN (n_289),
       .CK (clk), .D (n_279), .Q
       (internal_oscillator_clk_cycle_counting[5]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[6] (.RN (n_289),
       .CK (clk), .D (n_282), .Q
       (internal_oscillator_clk_cycle_counting[6]));
  NOR2XL g8613__2398(.A (reset_counters), .B (n_287), .Y (n_288));
  AOI22XL g8615__5107(.A0 (n_103), .A1 (n_285), .B0
       (LOW_PULSE_COUNTING[7]), .B1 (n_102), .Y (n_287));
  AOI21XL g8616__6260(.A0 (n_115), .A1 (n_284), .B0 (reset_counters),
       .Y (n_286));
  XNOR2X1 g8617__4319(.A (LOW_PULSE_COUNTING[7]), .B (n_281), .Y
       (n_285));
  OAI211X1 g8619__8428(.A0 (LOW_PULSE_COUNTING[6]), .A1 (n_272), .B0
       (n_103), .C0 (n_281), .Y (n_284));
  AOI21XL g8621__5526(.A0 (n_112), .A1 (n_277), .B0 (reset_counters),
       .Y (n_283));
  NOR2XL g8623__6783(.A (n_227), .B (n_280), .Y (n_282));
  AOI21XL g8625__3680(.A0 (internal_oscillator_clk_cycle_counting[5]),
       .A1 (n_254), .B0 (internal_oscillator_clk_cycle_counting[6]), .Y
       (n_280));
  NAND2XL g8626__1617(.A (LOW_PULSE_COUNTING[6]), .B (n_272), .Y
       (n_281));
  NOR2XL g8628__2802(.A (n_227), .B (n_273), .Y (n_279));
  OAI32X1 g8629__1705(.A0 (n_88), .A1 (n_197), .A2 (n_266), .B0 (n_11),
       .B1 (n_155), .Y (n_278));
  OAI211X1 g8630__5122(.A0 (LOW_PULSE_COUNTING[5]), .A1 (n_265), .B0
       (n_103), .C0 (n_276), .Y (n_277));
  INVXL g8631(.A (n_272), .Y (n_276));
  AOI21XL g8633__8246(.A0 (n_117), .A1 (n_269), .B0 (reset_counters),
       .Y (n_275));
  NOR2XL g8637__7098(.A (reset_counters), .B (n_270), .Y (n_274));
  XNOR2X1 g8638__6131(.A (internal_oscillator_clk_cycle_counting[5]),
       .B (n_254), .Y (n_273));
  OAI21XL g8640__1881(.A0 (n_88), .A1 (n_261), .B0 (n_154), .Y (n_271));
  AND2X1 g8641__5115(.A (n_265), .B (LOW_PULSE_COUNTING[5]), .Y
       (n_272));
  AOI22XL g8644__7482(.A0 (n_104), .A1 (n_260), .B0
       (HIGH_PULSE_COUNTING[4]), .B1 (n_105), .Y (n_270));
  OAI211X1 g8645__4733(.A0 (LOW_PULSE_COUNTING[4]), .A1 (n_194), .B0
       (n_103), .C0 (n_255), .Y (n_269));
  OAI21XL g8646__6161(.A0 (n_88), .A1 (n_257), .B0 (n_154), .Y (n_268));
  AOI211XL g8647__9315(.A0 (n_8), .A1 (n_195), .B0 (n_227), .C0
       (n_254), .Y (n_267));
  AOI32X1 g8648__9945(.A0 (LOW_PULSE_COUNTING[5]), .A1 (n_53), .A2
       (n_152), .B0 (n_6), .B1 (n_259), .Y (n_266));
  INVX1 g8649(.A (n_255), .Y (n_265));
  AOI21XL g8650__2883(.A0 (n_113), .A1 (n_248), .B0 (reset_counters),
       .Y (n_264));
  AOI21XL g8652__2346(.A0 (n_114), .A1 (n_251), .B0 (reset_counters),
       .Y (n_263));
  NOR4X1 g8653__1666(.A (n_83), .B (n_149), .C (n_230), .D (n_253), .Y
       (n_262));
  AND2X1 g8654__7410(.A (n_250), .B (n_53), .Y (n_261));
  XNOR2X1 g8657__6417(.A (HIGH_PULSE_COUNTING[4]), .B (n_196), .Y
       (n_260));
  NOR4X1 g8658__5477(.A (LOW_PULSE_COUNTING[6]), .B
       (HIGH_PULSE_COUNTING[2]), .C (n_14), .D (n_208), .Y (n_259));
  NOR4X1 g8659__2398(.A (LOW_PULSE_COUNTING[5]), .B (n_88), .C (n_179),
       .D (n_223), .Y (n_258));
  AOI221X1 g8660__5107(.A0 (n_4), .A1 (n_12), .B0
       (HIGH_PULSE_COUNTING[4]), .B1 (LOW_PULSE_COUNTING[4]), .C0
       (n_249), .Y (n_257));
  INVXL g8672(.A (n_252), .Y (n_256));
  OAI211X1 g8673__6260(.A0 (internal_f_bit_locator[2]), .A1 (n_124),
       .B0 (n_192), .C0 (n_232), .Y (n_253));
  OAI211X1 g8674__4319(.A0 (internal_oscillator_clk_cycle_counting[3]),
       .A1 (n_110), .B0 (n_195), .C0 (n_228), .Y (n_252));
  OAI211X1 g8675__8428(.A0 (LOW_PULSE_COUNTING[3]), .A1 (n_158), .B0
       (n_103), .C0 (n_247), .Y (n_251));
  AOI221X1 g8676__5526(.A0 (n_6), .A1 (n_185), .B0
       (LOW_PULSE_COUNTING[5]), .B1 (n_151), .C0 (n_197), .Y (n_250));
  OAI211X1 g8677__6783(.A0 (HIGH_PULSE_COUNTING[3]), .A1 (n_57), .B0
       (n_50), .C0 (n_229), .Y (n_249));
  OAI211X1 g8678__3680(.A0 (HIGH_PULSE_COUNTING[3]), .A1 (n_157), .B0
       (n_104), .C0 (n_196), .Y (n_248));
  NAND2XL g8679__1617(.A (LOW_PULSE_COUNTING[4]), .B (n_194), .Y
       (n_255));
  NOR2XL g8680__2802(.A (n_8), .B (n_195), .Y (n_254));
  INVXL g8685(.A (n_194), .Y (n_247));
  OAI221X1 g8704__1705(.A0 (n_24), .A1 (n_87), .B0 (n_37), .B1 (n_99),
       .C0 (n_201), .Y (n_246));
  AOI21XL g8705__5122(.A0 (n_116), .A1 (n_168), .B0 (reset_counters),
       .Y (n_245));
  AOI21XL g8706__8246(.A0 (n_121), .A1 (n_167), .B0 (reset_counters),
       .Y (n_244));
  OAI221X1 g8707__7098(.A0 (n_44), .A1 (n_87), .B0 (n_28), .B1 (n_99),
       .C0 (n_205), .Y (n_243));
  OAI221X1 g8708__6131(.A0 (n_43), .A1 (n_87), .B0 (n_42), .B1 (n_99),
       .C0 (n_207), .Y (n_242));
  NOR3BXL g8709__1881(.AN (n_51), .B (n_70), .C (n_227), .Y (n_241));
  OAI221X1 g8710__5115(.A0 (n_41), .A1 (n_87), .B0 (n_19), .B1 (n_99),
       .C0 (n_204), .Y (n_240));
  OAI221X1 g8711__7482(.A0 (n_28), .A1 (n_87), .B0 (n_36), .B1 (n_99),
       .C0 (n_206), .Y (n_239));
  OAI221X1 g8712__4733(.A0 (n_27), .A1 (n_99), .B0 (n_24), .B1 (n_97),
       .C0 (n_198), .Y (n_238));
  NAND2XL g8713__6161(.A (internal_oscillator_clk_cycle_counting[0]),
       .B (n_228), .Y (n_237));
  OAI221X1 g8714__9315(.A0 (n_35), .A1 (n_87), .B0 (n_39), .B1 (n_99),
       .C0 (n_200), .Y (n_236));
  OAI221X1 g8715__9945(.A0 (n_19), .A1 (n_87), .B0 (n_22), .B1 (n_99),
       .C0 (n_199), .Y (n_235));
  OAI221X1 g8716__2883(.A0 (n_21), .A1 (n_101), .B0 (n_23), .B1 (n_97),
       .C0 (n_203), .Y (n_234));
  OAI221X1 g8717__2346(.A0 (n_20), .A1 (n_101), .B0 (n_38), .B1 (n_97),
       .C0 (n_202), .Y (n_233));
  NOR4X1 g8718__1666(.A (F_BIT_LOCATOR[0]), .B (n_78), .C (n_143), .D
       (n_193), .Y (n_232));
  AOI211XL g8719__7410(.A0 (n_18), .A1 (n_51), .B0 (n_110), .C0
       (n_227), .Y (n_231));
  OAI211X1 g8720__6417(.A0 (internal_f_bit_locator[7]), .A1 (n_120),
       .B0 (n_80), .C0 (n_191), .Y (n_230));
  NOR2XL g8721__5477(.A (LOW_PULSE_COUNTING[5]), .B (n_223), .Y
       (n_229));
  INVX1 g8722(.A (n_227), .Y (n_228));
  OAI211X1 g8723__2398(.A0 (n_45), .A1 (n_119), .B0 (n_141), .C0
       (n_144), .Y (n_226));
  OAI221X1 g8724__5107(.A0 (n_27), .A1 (n_119), .B0 (n_29), .B1
       (n_101), .C0 (n_190), .Y (n_225));
  NOR2XL g8725__6260(.A (reset_counters), .B (n_166), .Y (n_224));
  NOR3BXL g8746__4319(.AN (internal_oscillator_clk_cycle_counting[5]),
       .B (n_8), .C (n_146), .Y (n_227));
  NAND3BXL g8748__8428(.AN (LOW_PULSE_COUNTING[7]), .B (n_68), .C
       (n_153), .Y (n_223));
  OAI211X1 g8749__5526(.A0 (n_28), .A1 (n_119), .B0 (n_131), .C0
       (n_138), .Y (n_222));
  OAI221X1 g8750__6783(.A0 (n_42), .A1 (n_87), .B0 (n_41), .B1 (n_99),
       .C0 (n_170), .Y (n_221));
  OAI211X1 g8751__3680(.A0 (n_44), .A1 (n_119), .B0 (n_129), .C0
       (n_134), .Y (n_220));
  OAI211X1 g8752__1617(.A0 (n_43), .A1 (n_119), .B0 (n_126), .C0
       (n_159), .Y (n_219));
  OAI221X1 g8753__2802(.A0 (n_25), .A1 (n_99), .B0 (n_35), .B1 (n_97),
       .C0 (n_160), .Y (n_218));
  OAI221X1 g8754__1705(.A0 (n_25), .A1 (n_87), .B0 (n_29), .B1 (n_99),
       .C0 (n_163), .Y (n_217));
  OAI221X1 g8755__5122(.A0 (n_36), .A1 (n_119), .B0 (n_19), .B1
       (n_101), .C0 (n_178), .Y (n_216));
  OAI221X1 g8756__8246(.A0 (n_26), .A1 (n_101), .B0 (n_35), .B1 (n_99),
       .C0 (n_162), .Y (n_215));
  OAI221X1 g8757__7098(.A0 (n_22), .A1 (n_101), .B0 (n_20), .B1 (n_99),
       .C0 (n_161), .Y (n_214));
  OAI221X1 g8758__6131(.A0 (n_19), .A1 (n_119), .B0 (n_40), .B1 (n_97),
       .C0 (n_164), .Y (n_213));
  OAI221X1 g8759__1881(.A0 (n_29), .A1 (n_119), .B0 (n_27), .B1 (n_87),
       .C0 (n_142), .Y (n_212));
  OAI221X1 g8760__5115(.A0 (n_26), .A1 (n_119), .B0 (n_20), .B1 (n_97),
       .C0 (n_165), .Y (n_211));
  OAI211X1 g8761__7482(.A0 (n_45), .A1 (n_101), .B0 (n_148), .C0
       (n_147), .Y (n_210));
  OAI221X1 g8762__4733(.A0 (n_20), .A1 (n_119), .B0 (n_23), .B1
       (n_101), .C0 (n_169), .Y (n_209));
  AOI31X1 g8763__6161(.A0 (HIGH_PULSE_COUNTING[4]), .A1 (n_12), .A2
       (n_52), .B0 (n_180), .Y (n_208));
  AOI222X1 g8764__9315(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .C1 (n_1), .Y (n_207));
  AOI222X1 g8765__9945(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .C1 (n_1), .Y (n_206));
  AOI222X1 g8766__2883(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .C1 (n_1), .Y (n_205));
  AOI222X1 g8767__2346(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .C1 (n_1), .Y (n_204));
  AOI222X1 g8768__1666(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_98), .Y (n_203));
  AOI222X1 g8769__7410(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .C1 (n_98), .Y (n_202));
  AOI222X1 g8770__6417(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .C1 (n_1), .Y (n_201));
  AOI222X1 g8771__5477(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .C1 (n_1), .Y (n_200));
  AOI222X1 g8772__2398(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .C1 (n_1), .Y (n_199));
  AOI222X1 g8773__5107(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .B1 (n_118), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .C1 (n_86), .Y (n_198));
  MXI2XL g8774__6260(.A (n_123), .B (F_BIT_LOCATOR[1]), .S0
       (internal_f_bit_locator[1]), .Y (n_193));
  OAI31X1 g8775__4319(.A0 (F_BIT_LOCATOR[3]), .A1
       (internal_f_bit_locator[3]), .A2 (n_79), .B0 (n_59), .Y (n_192));
  OAI31X1 g8776__8428(.A0 (F_BIT_LOCATOR[6]), .A1
       (internal_f_bit_locator[6]), .A2 (n_82), .B0 (n_60), .Y (n_191));
  AOI222X1 g8777__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .A1 (n_1),
       .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .B1 (n_86), .C0
       (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .C1 (n_98), .Y (n_190));
  AO21X1 g8778__6783(.A0 (BIDIR_SHIFTREG_OP_MODE[2]), .A1 (n_64), .B0
       (n_155), .Y (n_189));
  AND2X1 g8779__3680(.A (n_150), .B (BIDIR_SHIFTREG_OP_MODE[1]), .Y
       (n_188));
  OAI21XL g8780__1617(.A0 (n_2), .A1 (n_63), .B0 (n_156), .Y (n_187));
  NOR2XL g8781__2802(.A (reset_counters), .B (n_133), .Y (n_186));
  NAND2XL g8782__1705(.A (n_52), .B (n_153), .Y (n_185));
  OAI2BB1X1 g8783__5122(.A0N (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .A1N
       (n_111), .B0 (n_69), .Y (n_184));
  NOR2XL g8784__8246(.A (reset_counters), .B (n_127), .Y (n_183));
  NOR2XL g8785__7098(.A (reset_counters), .B (n_128), .Y (n_182));
  NAND3BXL g8790__6131(.AN (LOW_PULSE_COUNTING[7]), .B (n_66), .C
       (n_68), .Y (n_197));
  NAND2XL g8791__1881(.A (HIGH_PULSE_COUNTING[3]), .B (n_157), .Y
       (n_196));
  NAND2XL g8792__5115(.A (internal_oscillator_clk_cycle_counting[3]),
       .B (n_110), .Y (n_195));
  AND2X1 g8793__7482(.A (n_158), .B (LOW_PULSE_COUNTING[3]), .Y
       (n_194));
  INVXL g8795(.A (n_172), .Y (n_181));
  INVXL g8796(.A (n_179), .Y (n_180));
  AOI222X1 g8797__4733(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .B1 (n_98), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .C1 (n_1), .Y (n_178));
  OAI31X1 g8798__6161(.A0 (n_37), .A1 (n_25), .A2 (n_61), .B0 (n_91),
       .Y (n_177));
  OAI31X1 g8799__9315(.A0 (n_39), .A1 (n_24), .A2 (n_61), .B0 (n_90),
       .Y (n_176));
  OAI31X1 g8800__9945(.A0 (n_21), .A1 (n_35), .A2 (n_61), .B0 (n_94),
       .Y (n_175));
  OAI31X1 g8801__2883(.A0 (n_26), .A1 (n_23), .A2 (n_61), .B0 (n_95),
       .Y (n_174));
  OAI31X1 g8802__2346(.A0 (n_20), .A1 (n_22), .A2 (n_61), .B0 (n_96),
       .Y (n_173));
  AOI32X1 g8803__1666(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .A2 (n_62), .B0
       (internal_interpreted_addr[6]), .B1 (n_61), .Y (n_172));
  OAI31X1 g8804__7410(.A0 (n_19), .A1 (n_36), .A2 (n_61), .B0 (n_92),
       .Y (n_171));
  AOI222X1 g8805__6417(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .B1 (n_1), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .C1 (n_118), .Y (n_170));
  AOI222X1 g8806__5477(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .B1 (n_98), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .C1 (n_1), .Y (n_169));
  OAI211X1 g8807__2398(.A0 (LOW_PULSE_COUNTING[2]), .A1 (n_58), .B0
       (n_103), .C0 (n_108), .Y (n_168));
  OAI211X1 g8808__5107(.A0 (HIGH_PULSE_COUNTING[2]), .A1 (n_55), .B0
       (n_104), .C0 (n_109), .Y (n_167));
  AOI22XL g8809__6260(.A0 (n_103), .A1 (n_85), .B0
       (LOW_PULSE_COUNTING[1]), .B1 (n_102), .Y (n_166));
  AOI222X1 g8810__4319(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .B1 (n_98), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .C1 (n_100), .Y (n_165));
  AOI222X1 g8811__8428(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .B1 (n_98), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .C1 (n_100), .Y (n_164));
  AOI222X1 g8812__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .B1 (n_1), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .C1 (n_118), .Y (n_163));
  AOI222X1 g8813__6783(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .B1 (n_1), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .C1 (n_118), .Y (n_162));
  AOI222X1 g8814__3680(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .B1 (n_1), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .C1 (n_118), .Y (n_161));
  AOI222X1 g8815__1617(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .B1 (n_86), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_118), .Y (n_160));
  AOI222X1 g8816__2802(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .B1 (n_98), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .C1 (n_100), .Y (n_159));
  AOI32X1 g8817__1705(.A0 (HIGH_PULSE_COUNTING[4]), .A1 (n_3), .A2
       (n_57), .B0 (n_52), .B1 (n_53), .Y (n_179));
  INVX1 g8818(.A (n_108), .Y (n_158));
  INVX1 g8819(.A (n_109), .Y (n_157));
  INVXL g8820(.A (n_155), .Y (n_156));
  INVXL g8821(.A (n_151), .Y (n_152));
  ADDHX1 g8822__5122(.A (current_state[2]), .B (n_64), .CO (n_150), .S
       (n_155));
  OAI22XL g8823__8246(.A0 (internal_f_bit_locator[5]), .A1 (n_81), .B0
       (F_BIT_LOCATOR[7]), .B1 (n_32), .Y (n_149));
  NAND2XL g8824__7098(.A (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B (n_118),
       .Y (n_148));
  AOI22XL g8825__6131(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A1
       (n_98), .B0 (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .B1 (n_1), .Y
       (n_147));
  NAND4BXL g8826__1881(.AN (n_70), .B
       (internal_oscillator_clk_cycle_counting[6]), .C
       (internal_oscillator_clk_cycle_counting[3]), .D
       (internal_oscillator_clk_cycle_counting[2]), .Y (n_146));
  OAI22XL g8827__5115(.A0 (n_5), .A1 (n_93), .B0 (current_state[1]),
       .B1 (n_89), .Y (n_145));
  AOI22XL g8828__7482(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .B1 (n_1), .Y
       (n_144));
  AOI2BB1XL g8829__4733(.A0N (F_BIT_LOCATOR[4]), .A1N (n_77), .B0
       (internal_f_bit_locator[4]), .Y (n_143));
  AOI22XL g8830__6161(.A0 (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .A1
       (n_98), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .B1 (n_1), .Y
       (n_142));
  AOI22XL g8831__9315(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .B1 (n_98), .Y
       (n_141));
  NAND3BXL g8832__9945(.AN (current_state[2]), .B (n_104), .C (n_63),
       .Y (n_154));
  NOR4BX1 g8833__2883(.AN (n_66), .B (HIGH_PULSE_COUNTING[2]), .C
       (LOW_PULSE_COUNTING[6]), .D (n_14), .Y (n_153));
  NAND4XL g8834__2346(.A (LOW_PULSE_COUNTING[3]), .B
       (LOW_PULSE_COUNTING[6]), .C (n_3), .D (n_47), .Y (n_151));
  INVXL g8835(.A (n_136), .Y (n_140));
  INVXL g8836(.A (n_135), .Y (n_139));
  AOI22XL g8837__1666(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .B1 (n_98), .Y
       (n_138));
  OAI31X1 g8838__7410(.A0 (n_40), .A1 (n_41), .A2 (n_106), .B0 (n_122),
       .Y (n_137));
  AOI32X1 g8839__6417(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A2 (n_107), .B0 (D[2]), .B1
       (n_106), .Y (n_136));
  AOI32X1 g8840__5477(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A2 (n_107), .B0 (D[0]), .B1
       (n_106), .Y (n_135));
  AOI22XL g8841__2398(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A1
       (n_98), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .B1 (n_1), .Y
       (n_134));
  AOI32X1 g8842__5107(.A0 (n_54), .A1 (n_104), .A2 (n_65), .B0
       (HIGH_PULSE_COUNTING[1]), .B1 (n_105), .Y (n_133));
  OAI31X1 g8843__6260(.A0 (n_42), .A1 (n_44), .A2 (n_106), .B0 (n_125),
       .Y (n_132));
  AOI22XL g8844__4319(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A1
       (n_86), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .B1 (n_1), .Y
       (n_131));
  OAI221X1 g8845__8428(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .A1
       (n_29), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .B1 (n_27), .C0
       (n_76), .Y (n_130));
  AOI22XL g8846__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .A1
       (n_100), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .B1 (n_86), .Y
       (n_129));
  XNOR2X1 g8847__6783(.A (HIGH_PULSE_COUNTING[0]), .B (n_104), .Y
       (n_128));
  XNOR2X1 g8848__3680(.A (LOW_PULSE_COUNTING[0]), .B (n_103), .Y
       (n_127));
  NAND2XL g8849__1617(.A (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B (n_1),
       .Y (n_126));
  NAND2XL g8850__2802(.A (D[1]), .B (n_106), .Y (n_125));
  AOI221X1 g8851__1705(.A0 (n_34), .A1 (internal_interpreted_addr[2]),
       .B0 (INTERPRETED_ADDR[2]), .B1 (n_9), .C0 (F_BIT_LOCATOR[2]), .Y
       (n_124));
  AOI221X1 g8852__5122(.A0 (n_46), .A1 (internal_interpreted_addr[1]),
       .B0 (INTERPRETED_ADDR[1]), .B1 (n_10), .C0 (F_BIT_LOCATOR[1]),
       .Y (n_123));
  NAND2XL g8853__8246(.A (D[3]), .B (n_106), .Y (n_122));
  NAND2XL g8854__7098(.A (HIGH_PULSE_COUNTING[2]), .B (n_105), .Y
       (n_121));
  AOI221X1 g8855__6131(.A0 (n_33), .A1 (internal_interpreted_addr[7]),
       .B0 (INTERPRETED_ADDR[7]), .B1 (n_17), .C0 (F_BIT_LOCATOR[7]),
       .Y (n_120));
  INVX1 g8856(.A (n_119), .Y (n_118));
  NAND2XL g8857__1881(.A (LOW_PULSE_COUNTING[4]), .B (n_102), .Y
       (n_117));
  NAND2XL g8858__5115(.A (LOW_PULSE_COUNTING[2]), .B (n_102), .Y
       (n_116));
  NAND2XL g8859__7482(.A (LOW_PULSE_COUNTING[6]), .B (n_102), .Y
       (n_115));
  NAND2XL g8860__4733(.A (LOW_PULSE_COUNTING[3]), .B (n_102), .Y
       (n_114));
  NAND2XL g8861__6161(.A (HIGH_PULSE_COUNTING[3]), .B (n_105), .Y
       (n_113));
  NAND2XL g8862__9315(.A (LOW_PULSE_COUNTING[5]), .B (n_102), .Y
       (n_112));
  OAI211X1 g8863__9945(.A0 (current_state[1]), .A1 (current_state[2]),
       .B0 (n_16), .C0 (n_48), .Y (n_111));
  AOI22XL g8864__2883(.A0 (n_2), .A1 (n_71), .B0
       (BIDIR_SHIFTREG_OP_MODE[1]), .B1 (BIDIR_SHIFTREG_OP_MODE[2]), .Y
       (n_119));
  INVX1 g8865(.A (n_106), .Y (n_107));
  INVX1 g8866(.A (n_105), .Y (n_104));
  INVX1 g8867(.A (n_103), .Y (n_102));
  INVX1 g8868(.A (n_101), .Y (n_100));
  INVX1 g8869(.A (n_99), .Y (n_98));
  INVX1 g8870(.A (n_1), .Y (n_97));
  NAND2XL g8871__2346(.A (internal_interpreted_addr[5]), .B (n_61), .Y
       (n_96));
  NAND2XL g8872__1666(.A (internal_interpreted_addr[4]), .B (n_61), .Y
       (n_95));
  NAND2XL g8873__7410(.A (internal_interpreted_addr[3]), .B (n_61), .Y
       (n_94));
  NOR2XL g8874__6417(.A (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .B (n_63),
       .Y (n_93));
  NAND2XL g8875__5477(.A (internal_interpreted_addr[7]), .B (n_61), .Y
       (n_92));
  NAND2XL g8876__2398(.A (internal_interpreted_addr[1]), .B (n_61), .Y
       (n_91));
  NAND2XL g8877__5107(.A (internal_interpreted_addr[2]), .B (n_61), .Y
       (n_90));
  NOR2BX1 g8878__6260(.AN (n_69), .B (BIDIR_SHIFTREG_PT2272_BIT_IN[0]),
       .Y (n_89));
  NOR2XL g8879__4319(.A (n_18), .B (n_51), .Y (n_110));
  NAND2XL g8880__8428(.A (HIGH_PULSE_COUNTING[2]), .B (n_55), .Y
       (n_109));
  NAND2XL g8881__5526(.A (LOW_PULSE_COUNTING[2]), .B (n_58), .Y
       (n_108));
  NAND2XL g8882__6783(.A (dv), .B (n_62), .Y (n_106));
  NAND2XL g8883__3680(.A (cod_i), .B (PREVIOUS_cod_i), .Y (n_105));
  NOR2BX1 g8884__1617(.AN (PREVIOUS_cod_i), .B (cod_i), .Y (n_103));
  NAND2XL g8885__2802(.A (BIDIR_SHIFTREG_OP_MODE[0]), .B (n_71), .Y
       (n_101));
  NAND2XL g8886__1705(.A (n_2), .B (n_56), .Y (n_99));
  INVX1 g8888(.A (n_87), .Y (n_86));
  OAI21XL g8889__5122(.A0 (LOW_PULSE_COUNTING[1]), .A1 (n_15), .B0
       (n_67), .Y (n_85));
  OAI22XL g8890__8246(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .A1
       (n_20), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .B1 (n_22), .Y
       (n_84));
  OAI22XL g8892__7098(.A0 (F_BIT_LOCATOR[2]), .A1 (n_31), .B0
       (F_BIT_LOCATOR[4]), .B1 (n_30), .Y (n_83));
  CLKXOR2X1 g8893__6131(.A (INTERPRETED_ADDR[6]), .B
       (internal_interpreted_addr[6]), .Y (n_82));
  XNOR2X1 g8894__1881(.A (INTERPRETED_ADDR[5]), .B
       (internal_interpreted_addr[5]), .Y (n_81));
  XNOR2X1 g8895__5115(.A (F_BIT_LOCATOR[5]), .B
       (internal_f_bit_locator[5]), .Y (n_80));
  CLKXOR2X1 g8896__7482(.A (INTERPRETED_ADDR[3]), .B
       (internal_interpreted_addr[3]), .Y (n_79));
  CLKXOR2X1 g8897__4733(.A (INTERPRETED_ADDR[0]), .B
       (internal_interpreted_addr[0]), .Y (n_78));
  CLKXOR2X1 g8898__6161(.A (INTERPRETED_ADDR[4]), .B
       (internal_interpreted_addr[4]), .Y (n_77));
  AOI22XL g8899__9315(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .A1 (n_25),
       .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .B1 (n_37), .Y (n_76));
  OAI22XL g8900__9945(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .A1 (n_39),
       .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .B1 (n_24), .Y (n_75));
  OAI22XL g8901__2883(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .A1 (n_21),
       .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .B1 (n_35), .Y (n_74));
  OAI22XL g8902__2346(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .A1
       (n_19), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .B1 (n_36), .Y
       (n_73));
  OAI22XL g8903__1666(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .A1 (n_26),
       .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .B1 (n_23), .Y (n_72));
  NAND3BXL g8904__7410(.AN (current_state[1]), .B (current_state[0]),
       .C (current_state[2]), .Y (n_88));
  NAND3BXL g8905__6417(.AN (BIDIR_SHIFTREG_OP_MODE[2]), .B
       (BIDIR_SHIFTREG_OP_MODE[1]), .C (n_2), .Y (n_87));
  INVXL g8906(.A (n_67), .Y (n_68));
  INVXL g8907(.A (n_66), .Y (n_65));
  INVX1 g8908(.A (n_63), .Y (n_64));
  INVX1 g8909(.A (n_62), .Y (n_61));
  NAND2XL g8910__5477(.A (F_BIT_LOCATOR[6]), .B
       (internal_f_bit_locator[6]), .Y (n_60));
  NAND2XL g8911__2398(.A (F_BIT_LOCATOR[3]), .B
       (internal_f_bit_locator[3]), .Y (n_59));
  NOR2XL g8912__5107(.A (BIDIR_SHIFTREG_OP_MODE[1]), .B
       (BIDIR_SHIFTREG_OP_MODE[2]), .Y (n_71));
  NOR2XL g8914__6260(.A (internal_oscillator_clk_cycle_counting[1]), .B
       (internal_oscillator_clk_cycle_counting[0]), .Y (n_70));
  NAND2XL g8915__4319(.A (current_state[0]), .B (n_5), .Y (n_69));
  NAND2XL g8916__8428(.A (LOW_PULSE_COUNTING[1]), .B (n_15), .Y (n_67));
  NOR2XL g8917__5526(.A (HIGH_PULSE_COUNTING[1]), .B
       (HIGH_PULSE_COUNTING[0]), .Y (n_66));
  NOR2XL g8918__6783(.A (current_state[0]), .B (current_state[1]), .Y
       (n_63));
  NOR2XL g8919__3680(.A (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B (n_45),
       .Y (n_62));
  INVXL g8921(.A (n_55), .Y (n_54));
  NAND2XL g8922__1617(.A (LOW_PULSE_COUNTING[3]), .B
       (HIGH_PULSE_COUNTING[3]), .Y (n_50));
  NOR2XL g8923__2802(.A (n_29), .B (n_27), .Y (n_49));
  NAND2XL g8924__1705(.A (current_state[1]), .B (current_state[2]), .Y
       (n_48));
  NOR2XL g8925__5122(.A (LOW_PULSE_COUNTING[2]), .B (n_7), .Y (n_47));
  AND2X1 g8926__8246(.A (LOW_PULSE_COUNTING[1]), .B
       (LOW_PULSE_COUNTING[0]), .Y (n_58));
  NOR2XL g8927__7098(.A (LOW_PULSE_COUNTING[4]), .B (n_13), .Y (n_57));
  NOR2BX1 g8928__6131(.AN (BIDIR_SHIFTREG_OP_MODE[2]), .B
       (BIDIR_SHIFTREG_OP_MODE[1]), .Y (n_56));
  AND2X1 g8929__1881(.A (HIGH_PULSE_COUNTING[0]), .B
       (HIGH_PULSE_COUNTING[1]), .Y (n_55));
  NOR2XL g8930__5115(.A (HIGH_PULSE_COUNTING[4]), .B (n_12), .Y (n_53));
  NOR2XL g8931__7482(.A (LOW_PULSE_COUNTING[3]), .B (n_3), .Y (n_52));
  NAND2XL g8932__4733(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_51));
  INVXL g8933(.A (INTERPRETED_ADDR[1]), .Y (n_46));
  INVX1 g8937(.A (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .Y (n_45));
  INVX1 g8939(.A (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .Y (n_44));
  INVX1 g8940(.A (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .Y (n_43));
  INVX1 g8942(.A (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .Y (n_42));
  INVX1 g8943(.A (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .Y (n_41));
  INVX1 g8944(.A (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .Y (n_40));
  INVX1 g8946(.A (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .Y (n_39));
  INVX1 g8949(.A (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .Y (n_38));
  INVX1 g8950(.A (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .Y (n_37));
  INVX1 g8951(.A (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .Y (n_36));
  INVX1 g8952(.A (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .Y (n_35));
  INVXL g8954(.A (INTERPRETED_ADDR[2]), .Y (n_34));
  INVXL g8955(.A (INTERPRETED_ADDR[7]), .Y (n_33));
  INVXL g8956(.A (internal_f_bit_locator[7]), .Y (n_32));
  INVXL g8958(.A (internal_f_bit_locator[2]), .Y (n_31));
  INVXL g8961(.A (internal_f_bit_locator[4]), .Y (n_30));
  INVX1 g8963(.A (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .Y (n_29));
  INVX1 g8964(.A (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .Y (n_28));
  INVX1 g8965(.A (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .Y (n_27));
  INVX1 g8966(.A (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .Y (n_26));
  INVX1 g8967(.A (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .Y (n_25));
  INVX1 g8970(.A (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .Y (n_24));
  INVX1 g8972(.A (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .Y (n_23));
  INVX1 g8973(.A (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .Y (n_22));
  INVX1 g8974(.A (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .Y (n_21));
  INVX1 g8975(.A (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .Y (n_20));
  INVX1 g8976(.A (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .Y (n_19));
  DFFSX1 BIDIR_SHIFTREG_ENABLER_reg(.SN (n_289), .CK (osc_clk), .D
       (n_187), .Q (BIDIR_SHIFTREG_OP_MODE[0]), .QN (n_2));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[2] (.RN (n_289), .CK (osc_clk), .D
       (n_244), .Q (HIGH_PULSE_COUNTING[2]), .QN (n_7));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[3] (.RN (n_289), .CK (osc_clk), .D
       (n_264), .Q (HIGH_PULSE_COUNTING[3]), .QN (n_3));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[4] (.RN (n_289), .CK (osc_clk), .D
       (n_274), .Q (HIGH_PULSE_COUNTING[4]), .QN (n_4));
  DFFRX1 \LOW_PULSE_COUNTING_reg[0] (.RN (n_289), .CK (osc_clk), .D
       (n_183), .Q (LOW_PULSE_COUNTING[0]), .QN (n_15));
  DFFRX1 \LOW_PULSE_COUNTING_reg[2] (.RN (n_289), .CK (osc_clk), .D
       (n_245), .Q (LOW_PULSE_COUNTING[2]), .QN (n_14));
  DFFRX1 \LOW_PULSE_COUNTING_reg[3] (.RN (n_289), .CK (osc_clk), .D
       (n_263), .Q (LOW_PULSE_COUNTING[3]), .QN (n_13));
  DFFRX1 \LOW_PULSE_COUNTING_reg[4] (.RN (n_289), .CK (osc_clk), .D
       (n_275), .Q (LOW_PULSE_COUNTING[4]), .QN (n_12));
  DFFRX1 \LOW_PULSE_COUNTING_reg[5] (.RN (n_289), .CK (osc_clk), .D
       (n_283), .Q (LOW_PULSE_COUNTING[5]), .QN (n_6));
  DFFRX1 \current_state_reg[0] (.RN (n_289), .CK (osc_clk), .D (n_271),
       .Q (current_state[0]), .QN (n_16));
  DFFRX1 \current_state_reg[2] (.RN (n_289), .CK (osc_clk), .D (n_268),
       .Q (current_state[2]), .QN (n_5));
  DFFRX1 \internal_interpreted_addr_reg[1] (.RN (n_289), .CK (osc_clk),
       .D (n_177), .Q (internal_interpreted_addr[1]), .QN (n_10));
  DFFRX1 \internal_interpreted_addr_reg[2] (.RN (n_289), .CK (osc_clk),
       .D (n_176), .Q (internal_interpreted_addr[2]), .QN (n_9));
  DFFRX1 \internal_interpreted_addr_reg[7] (.RN (n_289), .CK (osc_clk),
       .D (n_171), .Q (internal_interpreted_addr[7]), .QN (n_17));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[2] (.RN (n_289),
       .CK (clk), .D (n_231), .Q
       (internal_oscillator_clk_cycle_counting[2]), .QN (n_18));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[4] (.RN (n_289),
       .CK (clk), .D (n_267), .Q
       (internal_oscillator_clk_cycle_counting[4]), .QN (n_8));
  DFFRX1 reset_counters_reg(.RN (n_289), .CK (osc_clk), .D (n_278), .Q
       (reset_counters), .QN (n_11));
  NOR2BX1 g2__6161(.AN (n_56), .B (n_2), .Y (n_1));
  MXI2XL g9013__9315(.A (n_38), .B (BIDIR_SHIFTREG_PARALLEL_OUT[13]),
       .S0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .Y (n_0));
endmodule

