
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 13 2025 10:50:37 -03 (Jan 13 2025 13:50:37 UTC)

// Verification Directory fv/decodificador_pt2272 

module ADDRESS_INTERPRETER(A, INTERPRETED_ADDR, F_BIT_LOCATOR);
  input [7:0] A;
  output [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  wire [7:0] A;
  wire [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  comp_endereco comp_endereco(.A (A), .A_01 (INTERPRETED_ADDR), .A_F
       (F_BIT_LOCATOR));
endmodule

module decodificador_pt2272(clk, reset, A, cod_i, D, dv);
  input clk, reset, cod_i;
  input [7:0] A;
  output [3:0] D;
  output dv;
  wire clk, reset, cod_i;
  wire [7:0] A;
  wire [3:0] D;
  wire dv;
  wire [7:0] INTERPRETED_ADDR;
  wire [7:0] F_BIT_LOCATOR;
  wire [1:0] BIDIR_SHIFTREG_PT2272_BIT_IN;
  wire [4:0] HIGH_PULSE_COUNTING;
  wire [7:0] LOW_PULSE_COUNTING;
  wire [25:0] BIDIR_SHIFTREG_PARALLEL_OUT;
  wire [2:0] BIDIR_SHIFTREG_OP_MODE;
  wire [2:0] current_state;
  wire [7:0] internal_f_bit_locator;
  wire [7:0] internal_interpreted_addr;
  wire [6:0] internal_oscillator_clk_cycle_counting;
  wire BIDIR_SHIFTREG_RESET, PREVIOUS_cod_i, n_0, n_1, n_2, n_3, n_4,
       n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, osc_clk, reset_counters;
  ADDRESS_INTERPRETER addr_translator(.A (A), .INTERPRETED_ADDR
       (INTERPRETED_ADDR), .F_BIT_LOCATOR (F_BIT_LOCATOR));
  DFFHQX1 \BIDIR_SHIFTREG_PT2272_BIT_IN_reg[0] (.CK (osc_clk), .D
       (n_136), .Q (BIDIR_SHIFTREG_PT2272_BIT_IN[0]));
  DFFHQX1 \BIDIR_SHIFTREG_PT2272_BIT_IN_reg[1] (.CK (osc_clk), .D
       (n_138), .Q (BIDIR_SHIFTREG_PT2272_BIT_IN[1]));
  DFFSHQX1 BIDIR_SHIFTREG_RESET_reg(.SN (n_18), .CK (osc_clk), .D
       (n_129), .Q (BIDIR_SHIFTREG_RESET));
  DFFRHQX1 \D_reg[0] (.RN (n_18), .CK (osc_clk), .D (n_112), .Q (D[0]));
  DFFRHQX1 \D_reg[1] (.RN (n_18), .CK (osc_clk), .D (n_120), .Q (D[1]));
  DFFRHQX1 \D_reg[2] (.RN (n_18), .CK (osc_clk), .D (n_114), .Q (D[2]));
  DFFRHQX1 \D_reg[3] (.RN (n_18), .CK (osc_clk), .D (n_113), .Q (D[3]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[0] (.RN (n_18), .CK (osc_clk), .D
       (n_130), .Q (HIGH_PULSE_COUNTING[0]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[1] (.RN (n_18), .CK (osc_clk), .D
       (n_132), .Q (HIGH_PULSE_COUNTING[1]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[3] (.RN (n_18), .CK (osc_clk), .D
       (n_167), .Q (HIGH_PULSE_COUNTING[3]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[1] (.RN (n_18), .CK (osc_clk), .D
       (n_137), .Q (LOW_PULSE_COUNTING[1]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[7] (.RN (n_18), .CK (osc_clk), .D
       (n_193), .Q (LOW_PULSE_COUNTING[7]));
  DFFRHQX1 PREVIOUS_cod_i_reg(.RN (n_18), .CK (cod_i), .D (cod_i), .Q
       (PREVIOUS_cod_i));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[0] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[0]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[1] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[1]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[2] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[3] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[3]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[4] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[5] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[6] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[6]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[7] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[8] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[8]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[9] (.RN (n_19), .CK (osc_clk), .D
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[10] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[10]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[11] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[12] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[13] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[14] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[14]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[15] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[16] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[16]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[17] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[18] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[18]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[19] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[20] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[20]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[21] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[21]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[22] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[23] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .SI
       (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[24] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .SI
       (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[24]));
  SDFFRHQX1 \RCVD_DATA_SHIFTREG_q_reg[25] (.RN (n_19), .CK (osc_clk),
       .D (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .SI
       (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .SE
       (BIDIR_SHIFTREG_OP_MODE[0]), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[25]));
  DFFRHQX1 \current_state_reg[0] (.RN (n_18), .CK (osc_clk), .D
       (n_176), .Q (current_state[0]));
  DFFRHQX1 \current_state_reg[1] (.RN (n_18), .CK (osc_clk), .D
       (n_155), .Q (current_state[1]));
  DFFRHQX1 dv_reg(.RN (n_18), .CK (osc_clk), .D (n_186), .Q (dv));
  SDFFRHQX1 \internal_f_bit_locator_reg[1] (.RN (n_18), .CK (osc_clk),
       .D (n_119), .SI (internal_f_bit_locator[1]), .SE (n_33), .Q
       (internal_f_bit_locator[1]));
  SDFFRHQX1 \internal_f_bit_locator_reg[2] (.RN (n_18), .CK (osc_clk),
       .D (n_95), .SI (internal_f_bit_locator[2]), .SE (n_33), .Q
       (internal_f_bit_locator[2]));
  SDFFRHQX1 \internal_f_bit_locator_reg[3] (.RN (n_18), .CK (osc_clk),
       .D (n_99), .SI (internal_f_bit_locator[3]), .SE (n_33), .Q
       (internal_f_bit_locator[3]));
  SDFFRHQX1 \internal_f_bit_locator_reg[4] (.RN (n_18), .CK (osc_clk),
       .D (n_105), .SI (internal_f_bit_locator[4]), .SE (n_33), .Q
       (internal_f_bit_locator[4]));
  SDFFRHQX1 \internal_f_bit_locator_reg[5] (.RN (n_18), .CK (osc_clk),
       .D (n_101), .SI (internal_f_bit_locator[5]), .SE (n_33), .Q
       (internal_f_bit_locator[5]));
  SDFFRHQX1 \internal_f_bit_locator_reg[6] (.RN (n_18), .CK (osc_clk),
       .D (n_103), .SI (internal_f_bit_locator[6]), .SE (n_33), .Q
       (internal_f_bit_locator[6]));
  SDFFRHQX1 \internal_f_bit_locator_reg[7] (.RN (n_18), .CK (osc_clk),
       .D (n_97), .SI (internal_f_bit_locator[7]), .SE (n_33), .Q
       (internal_f_bit_locator[7]));
  SDFFRHQX1 \internal_interpreted_addr_reg[0] (.RN (n_18), .CK
       (osc_clk), .D (n_30), .SI (internal_interpreted_addr[0]), .SE
       (n_33), .Q (internal_interpreted_addr[0]));
  SDFFRHQX1 \internal_interpreted_addr_reg[1] (.RN (n_18), .CK
       (osc_clk), .D (n_31), .SI (internal_interpreted_addr[1]), .SE
       (n_33), .Q (internal_interpreted_addr[1]));
  SDFFRHQX1 \internal_interpreted_addr_reg[2] (.RN (n_18), .CK
       (osc_clk), .D (n_94), .SI (internal_interpreted_addr[2]), .SE
       (n_33), .Q (internal_interpreted_addr[2]));
  SDFFRHQX1 \internal_interpreted_addr_reg[3] (.RN (n_18), .CK
       (osc_clk), .D (n_98), .SI (internal_interpreted_addr[3]), .SE
       (n_33), .Q (internal_interpreted_addr[3]));
  SDFFRHQX1 \internal_interpreted_addr_reg[4] (.RN (n_18), .CK
       (osc_clk), .D (n_104), .SI (internal_interpreted_addr[4]), .SE
       (n_33), .Q (internal_interpreted_addr[4]));
  SDFFRHQX1 \internal_interpreted_addr_reg[5] (.RN (n_18), .CK
       (osc_clk), .D (n_100), .SI (internal_interpreted_addr[5]), .SE
       (n_33), .Q (internal_interpreted_addr[5]));
  SDFFRHQX1 \internal_interpreted_addr_reg[6] (.RN (n_18), .CK
       (osc_clk), .D (n_102), .SI (internal_interpreted_addr[6]), .SE
       (n_33), .Q (internal_interpreted_addr[6]));
  SDFFRHQX1 \internal_interpreted_addr_reg[7] (.RN (n_18), .CK
       (osc_clk), .D (n_96), .SI (internal_interpreted_addr[7]), .SE
       (n_33), .Q (internal_interpreted_addr[7]));
  SDFFRHQX1 internal_oscillator_OUTPUT_CLK_reg(.RN (n_18), .CK (clk),
       .D (n_140), .SI (n_141), .SE (osc_clk), .Q (osc_clk));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[0] (.RN (n_18),
       .CK (clk), .D (n_150), .Q
       (internal_oscillator_clk_cycle_counting[0]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[1] (.RN (n_18),
       .CK (clk), .D (n_145), .Q
       (internal_oscillator_clk_cycle_counting[1]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[3] (.RN (n_18),
       .CK (clk), .D (n_159), .Q
       (internal_oscillator_clk_cycle_counting[3]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[5] (.RN (n_18),
       .CK (clk), .D (n_181), .Q
       (internal_oscillator_clk_cycle_counting[5]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[6] (.RN (n_18),
       .CK (clk), .D (n_187), .Q
       (internal_oscillator_clk_cycle_counting[6]));
  NOR2XL g7164__2398(.A (reset_counters), .B (n_192), .Y (n_193));
  AOI22XL g7166__5107(.A0 (n_64), .A1 (n_190), .B0
       (LOW_PULSE_COUNTING[7]), .B1 (n_63), .Y (n_192));
  AOI21XL g7167__6260(.A0 (n_76), .A1 (n_189), .B0 (reset_counters), .Y
       (n_191));
  XNOR2X1 g7168__4319(.A (LOW_PULSE_COUNTING[7]), .B (n_185), .Y
       (n_190));
  OAI211X1 g7170__8428(.A0 (LOW_PULSE_COUNTING[6]), .A1 (n_172), .B0
       (n_64), .C0 (n_185), .Y (n_189));
  AOI21XL g7172__5526(.A0 (n_79), .A1 (n_180), .B0 (reset_counters), .Y
       (n_188));
  NOR2XL g7176__6783(.A (n_140), .B (n_184), .Y (n_187));
  OAI2BB1X1 g7177__3680(.A0N (dv), .A1N (n_33), .B0 (n_182), .Y
       (n_186));
  AOI21XL g7178__1617(.A0 (internal_oscillator_clk_cycle_counting[5]),
       .A1 (n_160), .B0 (internal_oscillator_clk_cycle_counting[6]), .Y
       (n_184));
  NAND2XL g7179__2802(.A (LOW_PULSE_COUNTING[6]), .B (n_172), .Y
       (n_185));
  OAI22XL g7181__1705(.A0 (n_59), .A1 (n_173), .B0 (n_0), .B1 (n_74),
       .Y (n_183));
  NAND4XL g7182__5122(.A (n_40), .B (n_55), .C (n_32), .D (n_175), .Y
       (n_182));
  NOR2XL g7183__8246(.A (n_140), .B (n_174), .Y (n_181));
  OAI211X1 g7184__7098(.A0 (LOW_PULSE_COUNTING[5]), .A1 (n_168), .B0
       (n_64), .C0 (n_179), .Y (n_180));
  INVXL g7185(.A (n_172), .Y (n_179));
  AOI21XL g7187__6131(.A0 (n_77), .A1 (n_171), .B0 (reset_counters), .Y
       (n_178));
  NOR2XL g7189__1881(.A (reset_counters), .B (n_170), .Y (n_177));
  OAI21XL g7190__5115(.A0 (n_59), .A1 (n_165), .B0 (n_143), .Y (n_176));
  NOR4X1 g7192__7482(.A (n_41), .B (n_54), .C (n_117), .D (n_162), .Y
       (n_175));
  XNOR2X1 g7193__4733(.A (internal_oscillator_clk_cycle_counting[5]),
       .B (n_160), .Y (n_174));
  OA22X1 g7194__6161(.A0 (n_90), .A1 (n_163), .B0
       (LOW_PULSE_COUNTING[6]), .B1 (n_164), .Y (n_173));
  AND2X1 g7195__9315(.A (n_168), .B (LOW_PULSE_COUNTING[5]), .Y
       (n_172));
  OAI211X1 g7198__9945(.A0 (LOW_PULSE_COUNTING[4]), .A1 (n_134), .B0
       (n_64), .C0 (n_158), .Y (n_171));
  AOI22XL g7199__2883(.A0 (n_66), .A1 (n_161), .B0
       (HIGH_PULSE_COUNTING[4]), .B1 (n_65), .Y (n_170));
  AOI211XL g7200__2346(.A0 (n_12), .A1 (n_135), .B0 (n_140), .C0
       (n_160), .Y (n_169));
  INVX1 g7201(.A (n_158), .Y (n_168));
  AOI21XL g7202__1666(.A0 (n_81), .A1 (n_154), .B0 (reset_counters), .Y
       (n_167));
  AOI21XL g7203__7410(.A0 (n_78), .A1 (n_157), .B0 (reset_counters), .Y
       (n_166));
  AOI221X1 g7204__6417(.A0 (LOW_PULSE_COUNTING[3]), .A1 (n_8), .B0
       (LOW_PULSE_COUNTING[6]), .B1 (n_2), .C0 (n_163), .Y (n_165));
  NAND4XL g7205__5477(.A (HIGH_PULSE_COUNTING[4]), .B (n_9), .C (n_60),
       .D (n_149), .Y (n_164));
  OAI221X1 g7209__2398(.A0 (internal_f_bit_locator[5]), .A1 (n_87), .B0
       (internal_f_bit_locator[4]), .B1 (n_88), .C0 (n_153), .Y
       (n_162));
  XNOR2X1 g7210__5107(.A (HIGH_PULSE_COUNTING[4]), .B (n_133), .Y
       (n_161));
  NAND3BXL g7211__6260(.AN (HIGH_PULSE_COUNTING[4]), .B
       (LOW_PULSE_COUNTING[4]), .C (n_149), .Y (n_163));
  NOR2XL g7216__4319(.A (n_12), .B (n_135), .Y (n_160));
  INVXL g7219(.A (n_152), .Y (n_159));
  OAI211X1 g7220__8428(.A0 (LOW_PULSE_COUNTING[3]), .A1 (n_121), .B0
       (n_64), .C0 (n_151), .Y (n_157));
  OAI21XL g7221__5526(.A0 (n_59), .A1 (n_142), .B0 (n_143), .Y (n_156));
  NOR2XL g7222__6783(.A (n_59), .B (n_148), .Y (n_155));
  OAI211X1 g7223__3680(.A0 (HIGH_PULSE_COUNTING[3]), .A1 (n_122), .B0
       (n_66), .C0 (n_133), .Y (n_154));
  NOR4X1 g7224__1617(.A (F_BIT_LOCATOR[0]), .B (n_52), .C (n_131), .D
       (n_139), .Y (n_153));
  OAI211X1 g7225__2802(.A0 (internal_oscillator_clk_cycle_counting[3]),
       .A1 (n_69), .B0 (n_135), .C0 (n_141), .Y (n_152));
  NAND2XL g7226__1705(.A (LOW_PULSE_COUNTING[4]), .B (n_134), .Y
       (n_158));
  INVXL g7227(.A (n_134), .Y (n_151));
  NAND2XL g7228__5122(.A (internal_oscillator_clk_cycle_counting[0]),
       .B (n_141), .Y (n_150));
  OAI21XL g7233__8246(.A0 (n_37), .A1 (n_62), .B0 (n_142), .Y (n_148));
  AOI21XL g7234__7098(.A0 (n_80), .A1 (n_126), .B0 (reset_counters), .Y
       (n_147));
  AOI21XL g7235__6131(.A0 (n_83), .A1 (n_125), .B0 (reset_counters), .Y
       (n_146));
  NOR3BXL g7236__1881(.AN (n_46), .B (n_49), .C (n_140), .Y (n_145));
  AOI211XL g7237__5115(.A0 (n_6), .A1 (n_46), .B0 (n_69), .C0 (n_140),
       .Y (n_144));
  AOI211XL g7238__7482(.A0 (LOW_PULSE_COUNTING[6]), .A1 (n_5), .B0
       (n_45), .C0 (n_127), .Y (n_149));
  INVX1 g7251(.A (n_140), .Y (n_141));
  OAI222XL g7252__4733(.A0 (F_BIT_LOCATOR[5]), .A1 (n_22), .B0
       (internal_f_bit_locator[6]), .B1 (n_82), .C0
       (internal_f_bit_locator[7]), .C1 (n_84), .Y (n_139));
  NAND2XL g7253__6161(.A (n_73), .B (n_128), .Y (n_138));
  NOR2XL g7254__9315(.A (reset_counters), .B (n_124), .Y (n_137));
  OAI211X1 g7255__9945(.A0 (current_state[1]), .A1 (n_89), .B0 (n_61),
       .C0 (n_93), .Y (n_136));
  OA22X1 g7256__2883(.A0 (n_59), .A1 (n_60), .B0 (n_65), .B1 (n_70), .Y
       (n_143));
  NOR4X1 g7257__2346(.A (LOW_PULSE_COUNTING[7]), .B (n_45), .C (n_91),
       .D (n_92), .Y (n_142));
  NOR3BXL g7264__1666(.AN (internal_oscillator_clk_cycle_counting[5]),
       .B (n_12), .C (n_116), .Y (n_140));
  NOR2XL g7265__7410(.A (reset_counters), .B (n_108), .Y (n_132));
  NAND2XL g7270__6417(.A (internal_oscillator_clk_cycle_counting[3]),
       .B (n_69), .Y (n_135));
  AND2X1 g7271__5477(.A (n_121), .B (LOW_PULSE_COUNTING[3]), .Y
       (n_134));
  NAND2XL g7272__2398(.A (HIGH_PULSE_COUNTING[3]), .B (n_122), .Y
       (n_133));
  OAI22XL g7274__5107(.A0 (internal_f_bit_locator[2]), .A1 (n_85), .B0
       (internal_f_bit_locator[3]), .B1 (n_86), .Y (n_131));
  NOR2XL g7275__6260(.A (reset_counters), .B (n_107), .Y (n_130));
  AND2X1 g7276__4319(.A (n_70), .B (BIDIR_SHIFTREG_RESET), .Y (n_129));
  OAI31X1 g7277__8428(.A0 (reset), .A1 (current_state[0]), .A2 (n_50),
       .B0 (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .Y (n_128));
  OAI211X1 g7278__5526(.A0 (LOW_PULSE_COUNTING[6]), .A1 (n_3), .B0
       (n_44), .C0 (n_75), .Y (n_127));
  OAI211X1 g7279__6783(.A0 (LOW_PULSE_COUNTING[2]), .A1 (n_39), .B0
       (n_64), .C0 (n_71), .Y (n_126));
  OAI211X1 g7280__3680(.A0 (HIGH_PULSE_COUNTING[2]), .A1 (n_48), .B0
       (n_66), .C0 (n_72), .Y (n_125));
  AOI22XL g7281__1617(.A0 (n_64), .A1 (n_57), .B0
       (LOW_PULSE_COUNTING[1]), .B1 (n_63), .Y (n_124));
  NOR2XL g7282__2802(.A (reset_counters), .B (n_106), .Y (n_123));
  INVX1 g7283(.A (n_72), .Y (n_122));
  INVX1 g7284(.A (n_71), .Y (n_121));
  INVXL g7285(.A (n_115), .Y (n_120));
  OAI211X1 g7286__1705(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .A1
       (n_20), .B0 (n_56), .C0 (n_42), .Y (n_119));
  OAI221X1 g7287__5122(.A0 (n_34), .A1 (n_35), .B0 (n_7), .B1 (n_36),
       .C0 (n_93), .Y (n_118));
  AOI2BB1XL g7288__8246(.A0N (F_BIT_LOCATOR[1]), .A1N (n_53), .B0
       (internal_f_bit_locator[1]), .Y (n_117));
  NAND4BXL g7289__7098(.AN (n_49), .B
       (internal_oscillator_clk_cycle_counting[6]), .C
       (internal_oscillator_clk_cycle_counting[3]), .D
       (internal_oscillator_clk_cycle_counting[2]), .Y (n_116));
  AOI32X1 g7290__6131(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .A2 (n_67), .B0 (D[1]), .B1
       (n_68), .Y (n_115));
  INVXL g7291(.A (n_111), .Y (n_114));
  INVXL g7292(.A (n_110), .Y (n_113));
  INVXL g7293(.A (n_109), .Y (n_112));
  AOI32X1 g7294__1881(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A2 (n_67), .B0 (D[2]), .B1
       (n_68), .Y (n_111));
  AOI32X1 g7295__5115(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .A2 (n_67), .B0 (D[3]), .B1
       (n_68), .Y (n_110));
  AOI32X1 g7296__7482(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A2 (n_67), .B0 (D[0]), .B1
       (n_68), .Y (n_109));
  AOI32X1 g7297__4733(.A0 (n_47), .A1 (n_66), .A2 (n_43), .B0
       (HIGH_PULSE_COUNTING[1]), .B1 (n_65), .Y (n_108));
  XNOR2X1 g7298__6161(.A (HIGH_PULSE_COUNTING[0]), .B (n_66), .Y
       (n_107));
  XNOR2X1 g7299__9315(.A (LOW_PULSE_COUNTING[0]), .B (n_64), .Y
       (n_106));
  ADDHX1 g7300__9945(.A (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .CO (n_104), .S (n_105));
  ADDHX1 g7301__2883(.A (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .CO (n_102), .S (n_103));
  ADDHX1 g7302__2346(.A (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .CO (n_100), .S (n_101));
  ADDHX1 g7303__1666(.A (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .CO (n_98), .S (n_99));
  ADDHX1 g7304__7410(.A (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .CO (n_96), .S (n_97));
  ADDHX1 g7305__6417(.A (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .CO (n_94), .S (n_95));
  NAND4XL g7329__5477(.A (LOW_PULSE_COUNTING[2]), .B (n_3), .C (n_29),
       .D (n_44), .Y (n_92));
  OAI222XL g7330__2398(.A0 (n_2), .A1 (n_9), .B0
       (HIGH_PULSE_COUNTING[4]), .B1 (LOW_PULSE_COUNTING[4]), .C0
       (n_9), .C1 (n_1), .Y (n_91));
  AOI22XL g7331__5107(.A0 (n_8), .A1 (n_38), .B0
       (LOW_PULSE_COUNTING[6]), .B1 (n_37), .Y (n_90));
  NOR2BX1 g7332__6260(.AN (n_73), .B (BIDIR_SHIFTREG_PT2272_BIT_IN[0]),
       .Y (n_89));
  NOR2BX1 g7333__4319(.AN (n_58), .B (F_BIT_LOCATOR[4]), .Y (n_88));
  AOI221X1 g7334__8428(.A0 (n_28), .A1 (internal_interpreted_addr[5]),
       .B0 (INTERPRETED_ADDR[5]), .B1 (n_25), .C0 (F_BIT_LOCATOR[5]),
       .Y (n_87));
  AOI221X1 g7335__5526(.A0 (n_27), .A1 (internal_interpreted_addr[3]),
       .B0 (INTERPRETED_ADDR[3]), .B1 (n_14), .C0 (F_BIT_LOCATOR[3]),
       .Y (n_86));
  AOI221X1 g7336__6783(.A0 (n_16), .A1 (internal_interpreted_addr[2]),
       .B0 (INTERPRETED_ADDR[2]), .B1 (n_15), .C0 (F_BIT_LOCATOR[2]),
       .Y (n_85));
  NOR2BX1 g7337__3680(.AN (n_51), .B (F_BIT_LOCATOR[7]), .Y (n_84));
  NAND2XL g7338__1617(.A (HIGH_PULSE_COUNTING[2]), .B (n_65), .Y
       (n_83));
  AOI221X1 g7339__2802(.A0 (n_17), .A1 (internal_interpreted_addr[6]),
       .B0 (INTERPRETED_ADDR[6]), .B1 (n_23), .C0 (F_BIT_LOCATOR[6]),
       .Y (n_82));
  NAND2XL g7340__1705(.A (HIGH_PULSE_COUNTING[3]), .B (n_65), .Y
       (n_81));
  NAND2XL g7341__5122(.A (LOW_PULSE_COUNTING[2]), .B (n_63), .Y (n_80));
  NAND2XL g7342__8246(.A (LOW_PULSE_COUNTING[5]), .B (n_63), .Y (n_79));
  NAND2XL g7343__7098(.A (LOW_PULSE_COUNTING[3]), .B (n_63), .Y (n_78));
  NAND2XL g7344__6131(.A (LOW_PULSE_COUNTING[4]), .B (n_63), .Y (n_77));
  NAND2XL g7345__1881(.A (LOW_PULSE_COUNTING[6]), .B (n_63), .Y (n_76));
  AOI221X1 g7346__5115(.A0 (n_4), .A1 (n_3), .B0
       (LOW_PULSE_COUNTING[2]), .B1 (HIGH_PULSE_COUNTING[2]), .C0
       (LOW_PULSE_COUNTING[7]), .Y (n_75));
  OA21X1 g7347__7482(.A0 (n_10), .A1 (n_34), .B0 (n_70), .Y (n_74));
  NAND3XL g7348__4733(.A (n_18), .B (current_state[2]), .C (n_34), .Y
       (n_93));
  INVX1 g7352(.A (n_68), .Y (n_67));
  INVX1 g7353(.A (n_66), .Y (n_65));
  INVX1 g7354(.A (n_64), .Y (n_63));
  AND2X1 g7355__6161(.A (n_38), .B (n_1), .Y (n_62));
  NAND2XL g7356__9315(.A (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .B (n_35),
       .Y (n_61));
  NAND2XL g7357__9945(.A (current_state[0]), .B (n_36), .Y (n_73));
  NAND2XL g7358__2883(.A (HIGH_PULSE_COUNTING[2]), .B (n_48), .Y
       (n_72));
  NAND2XL g7359__2346(.A (LOW_PULSE_COUNTING[2]), .B (n_39), .Y (n_71));
  NAND2XL g7360__1666(.A (n_10), .B (n_34), .Y (n_70));
  NOR2XL g7361__7410(.A (n_6), .B (n_46), .Y (n_69));
  NAND2XL g7362__6417(.A (dv), .B (n_32), .Y (n_68));
  AND2X1 g7363__5477(.A (PREVIOUS_cod_i), .B (cod_i), .Y (n_66));
  NOR2BX1 g7364__2398(.AN (PREVIOUS_cod_i), .B (cod_i), .Y (n_64));
  XNOR2X1 g7365__5107(.A (INTERPRETED_ADDR[4]), .B
       (internal_interpreted_addr[4]), .Y (n_58));
  OAI21XL g7366__6260(.A0 (LOW_PULSE_COUNTING[1]), .A1 (n_11), .B0
       (n_45), .Y (n_57));
  XNOR2X1 g7367__4319(.A (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .Y (n_56));
  XNOR2X1 g7368__8428(.A (INTERPRETED_ADDR[0]), .B
       (internal_interpreted_addr[0]), .Y (n_55));
  OAI22XL g7369__5526(.A0 (F_BIT_LOCATOR[3]), .A1 (n_13), .B0
       (F_BIT_LOCATOR[4]), .B1 (n_26), .Y (n_54));
  CLKXOR2X1 g7370__6783(.A (INTERPRETED_ADDR[1]), .B
       (internal_interpreted_addr[1]), .Y (n_53));
  OAI22XL g7371__3680(.A0 (F_BIT_LOCATOR[6]), .A1 (n_24), .B0
       (F_BIT_LOCATOR[7]), .B1 (n_21), .Y (n_52));
  XNOR2X1 g7372__1617(.A (INTERPRETED_ADDR[7]), .B
       (internal_interpreted_addr[7]), .Y (n_51));
  XNOR2X1 g7373__2802(.A (current_state[1]), .B (current_state[2]), .Y
       (n_50));
  OR2X1 g7374__1705(.A (n_37), .B (n_38), .Y (n_60));
  NAND3BXL g7375__5122(.AN (current_state[1]), .B (current_state[0]),
       .C (current_state[2]), .Y (n_59));
  INVXL g7376(.A (n_48), .Y (n_47));
  INVXL g7377(.A (n_44), .Y (n_43));
  NAND2XL g7378__8246(.A (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .B (n_20),
       .Y (n_42));
  NOR2BX1 g7379__7098(.AN (internal_f_bit_locator[2]), .B
       (F_BIT_LOCATOR[2]), .Y (n_41));
  NAND2BXL g7380__6131(.AN (F_BIT_LOCATOR[1]), .B
       (internal_f_bit_locator[1]), .Y (n_40));
  NOR2XL g7381__1881(.A (internal_oscillator_clk_cycle_counting[1]), .B
       (internal_oscillator_clk_cycle_counting[0]), .Y (n_49));
  AND2X1 g7383__5115(.A (HIGH_PULSE_COUNTING[0]), .B
       (HIGH_PULSE_COUNTING[1]), .Y (n_48));
  NAND2XL g7384__7482(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_46));
  NAND2XL g7385__4733(.A (LOW_PULSE_COUNTING[1]), .B (n_11), .Y (n_45));
  NOR2XL g7386__6161(.A (HIGH_PULSE_COUNTING[1]), .B
       (HIGH_PULSE_COUNTING[0]), .Y (n_44));
  INVX1 g7387(.A (n_35), .Y (n_36));
  INVX1 g7388(.A (n_33), .Y (n_32));
  AND2X1 g7389__9315(.A (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .Y (n_31));
  AND2X1 g7390__9945(.A (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .Y (n_30));
  NOR2XL g7391__2883(.A (HIGH_PULSE_COUNTING[2]), .B
       (LOW_PULSE_COUNTING[6]), .Y (n_29));
  AND2X1 g7392__2346(.A (LOW_PULSE_COUNTING[1]), .B
       (LOW_PULSE_COUNTING[0]), .Y (n_39));
  AND2X1 g7393__1666(.A (n_2), .B (HIGH_PULSE_COUNTING[3]), .Y (n_38));
  NOR2XL g7394__7410(.A (HIGH_PULSE_COUNTING[3]), .B (n_2), .Y (n_37));
  NAND2XL g7395__6417(.A (n_18), .B (n_10), .Y (n_35));
  NOR2XL g7396__5477(.A (current_state[0]), .B (current_state[1]), .Y
       (n_34));
  NAND2BXL g7397__2398(.AN (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B
       (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .Y (n_33));
  INVXL g7398(.A (INTERPRETED_ADDR[5]), .Y (n_28));
  INVXL g7399(.A (INTERPRETED_ADDR[3]), .Y (n_27));
  INVXL g7400(.A (internal_f_bit_locator[4]), .Y (n_26));
  INVXL g7401(.A (internal_interpreted_addr[5]), .Y (n_25));
  INVXL g7402(.A (internal_f_bit_locator[6]), .Y (n_24));
  INVXL g7403(.A (internal_interpreted_addr[6]), .Y (n_23));
  INVXL g7404(.A (internal_f_bit_locator[5]), .Y (n_22));
  INVXL g7406(.A (internal_f_bit_locator[7]), .Y (n_21));
  INVX1 g7408(.A (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .Y (n_20));
  INVXL g7412(.A (BIDIR_SHIFTREG_RESET), .Y (n_19));
  INVXL g7413(.A (reset), .Y (n_18));
  INVXL g7415(.A (INTERPRETED_ADDR[6]), .Y (n_17));
  INVXL g7416(.A (INTERPRETED_ADDR[2]), .Y (n_16));
  INVXL g7417(.A (internal_interpreted_addr[2]), .Y (n_15));
  INVXL g7419(.A (internal_interpreted_addr[3]), .Y (n_14));
  INVXL g7420(.A (internal_f_bit_locator[3]), .Y (n_13));
  DFFX1 \BIDIR_SHIFTREG_OP_MODE_reg[0] (.CK (osc_clk), .D (n_118), .Q
       (BIDIR_SHIFTREG_OP_MODE[0]), .QN (n_7));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[2] (.RN (n_18), .CK (osc_clk), .D
       (n_146), .Q (HIGH_PULSE_COUNTING[2]), .QN (n_5));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[4] (.RN (n_18), .CK (osc_clk), .D
       (n_177), .Q (HIGH_PULSE_COUNTING[4]), .QN (n_1));
  DFFRX1 \LOW_PULSE_COUNTING_reg[0] (.RN (n_18), .CK (osc_clk), .D
       (n_123), .Q (LOW_PULSE_COUNTING[0]), .QN (n_11));
  DFFRX1 \LOW_PULSE_COUNTING_reg[2] (.RN (n_18), .CK (osc_clk), .D
       (n_147), .Q (LOW_PULSE_COUNTING[2]), .QN (n_4));
  DFFRX1 \LOW_PULSE_COUNTING_reg[3] (.RN (n_18), .CK (osc_clk), .D
       (n_166), .Q (LOW_PULSE_COUNTING[3]), .QN (n_2));
  DFFRX1 \LOW_PULSE_COUNTING_reg[4] (.RN (n_18), .CK (osc_clk), .D
       (n_178), .Q (LOW_PULSE_COUNTING[4]), .QN (n_9));
  DFFRX1 \LOW_PULSE_COUNTING_reg[5] (.RN (n_18), .CK (osc_clk), .D
       (n_188), .Q (LOW_PULSE_COUNTING[5]), .QN (n_3));
  DFFRX1 \LOW_PULSE_COUNTING_reg[6] (.RN (n_18), .CK (osc_clk), .D
       (n_191), .Q (LOW_PULSE_COUNTING[6]), .QN (n_8));
  DFFRX1 \current_state_reg[2] (.RN (n_18), .CK (osc_clk), .D (n_156),
       .Q (current_state[2]), .QN (n_10));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[2] (.RN (n_18),
       .CK (clk), .D (n_144), .Q
       (internal_oscillator_clk_cycle_counting[2]), .QN (n_6));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[4] (.RN (n_18),
       .CK (clk), .D (n_169), .Q
       (internal_oscillator_clk_cycle_counting[4]), .QN (n_12));
  DFFRX1 reset_counters_reg(.RN (n_18), .CK (osc_clk), .D (n_183), .Q
       (reset_counters), .QN (n_0));
endmodule

