
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 10 2025 19:04:34 -03 (Jan 10 2025 22:04:34 UTC)

// Verification Directory fv/decodificador_pt2272 

module ADDRESS_INTERPRETER(A, INTERPRETED_ADDR, F_BIT_LOCATOR);
  input [7:0] A;
  output [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  wire [7:0] A;
  wire [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  comp_endereco comp_endereco(.A (A), .A_01 (INTERPRETED_ADDR), .A_F
       (F_BIT_LOCATOR));
endmodule

module decodificador_pt2272(clk, reset, A, cod_i, D, dv);
  input clk, reset, cod_i;
  input [7:0] A;
  output [3:0] D;
  output dv;
  wire clk, reset, cod_i;
  wire [7:0] A;
  wire [3:0] D;
  wire dv;
  wire [7:0] INTERPRETED_ADDR;
  wire [7:0] F_BIT_LOCATOR;
  wire [2:0] BIDIR_SHIFTREG_OP_MODE;
  wire [1:0] BIDIR_SHIFTREG_PT2272_BIT_IN;
  wire [4:0] HIGH_PULSE_COUNTING;
  wire [7:0] LOW_PULSE_COUNTING;
  wire [25:0] BIDIR_SHIFTREG_PARALLEL_OUT;
  wire [7:0] current_state;
  wire [7:0] internal_f_bit_locator;
  wire [7:0] internal_interpreted_addr;
  wire [6:0] internal_oscillator_clk_cycle_counting;
  wire PREVIOUS_cod_i, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, osc_clk,
       reset_counters;
  ADDRESS_INTERPRETER addr_translator(.A (A), .INTERPRETED_ADDR
       (INTERPRETED_ADDR), .F_BIT_LOCATOR (F_BIT_LOCATOR));
  DFFSHQX1 \BIDIR_SHIFTREG_OP_MODE_reg[1] (.SN (n_18), .CK (osc_clk),
       .D (n_242), .Q (BIDIR_SHIFTREG_OP_MODE[1]));
  DFFRHQX1 \BIDIR_SHIFTREG_OP_MODE_reg[2] (.RN (n_18), .CK (osc_clk),
       .D (n_246), .Q (BIDIR_SHIFTREG_OP_MODE[2]));
  DFFRHQX1 \BIDIR_SHIFTREG_PT2272_BIT_IN_reg[0] (.RN (n_18), .CK
       (osc_clk), .D (n_223), .Q (BIDIR_SHIFTREG_PT2272_BIT_IN[0]));
  DFFRHQX1 \BIDIR_SHIFTREG_PT2272_BIT_IN_reg[1] (.RN (n_18), .CK
       (osc_clk), .D (n_220), .Q (BIDIR_SHIFTREG_PT2272_BIT_IN[1]));
  DFFRHQX1 \D_reg[0] (.RN (n_18), .CK (osc_clk), .D (n_143), .Q (D[0]));
  DFFRHQX1 \D_reg[1] (.RN (n_18), .CK (osc_clk), .D (n_138), .Q (D[1]));
  DFFRHQX1 \D_reg[2] (.RN (n_18), .CK (osc_clk), .D (n_137), .Q (D[2]));
  DFFRHQX1 \D_reg[3] (.RN (n_18), .CK (osc_clk), .D (n_142), .Q (D[3]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[0] (.RN (n_18), .CK (osc_clk), .D
       (n_182), .Q (HIGH_PULSE_COUNTING[0]));
  DFFRHQX1 \HIGH_PULSE_COUNTING_reg[1] (.RN (n_18), .CK (osc_clk), .D
       (n_185), .Q (HIGH_PULSE_COUNTING[1]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[0] (.RN (n_18), .CK (osc_clk), .D
       (n_183), .Q (LOW_PULSE_COUNTING[0]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[2] (.RN (n_18), .CK (osc_clk), .D
       (n_257), .Q (LOW_PULSE_COUNTING[2]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[5] (.RN (n_18), .CK (osc_clk), .D
       (n_295), .Q (LOW_PULSE_COUNTING[5]));
  DFFRHQX1 \LOW_PULSE_COUNTING_reg[7] (.RN (n_18), .CK (osc_clk), .D
       (n_300), .Q (LOW_PULSE_COUNTING[7]));
  DFFRHQX1 PREVIOUS_cod_i_reg(.RN (n_18), .CK (cod_i), .D (cod_i), .Q
       (PREVIOUS_cod_i));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[0] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_206), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[0]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[1] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_241), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[1]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[2] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_238), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[2]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[3] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_235), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[3]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[4] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_237), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[5] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_208), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[6] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_217), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[6]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[7] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_229), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[7]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[8] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_233), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[8]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[9] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_232), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[9]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[10] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_231), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[10]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[11] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_236), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[12] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_205), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[13] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_210), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[14] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_230), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[14]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[15] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_207), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[16] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_234), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[16]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[17] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_209), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[18] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_212), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[18]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[19] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_214), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[19]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[20] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_204), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[20]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[21] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_211), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[21]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[22] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_216), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[23] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_215), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[24] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_221), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[24]));
  DFFHQX1 \RCVD_DATA_SHIFTREG_q_reg[25] (.CK
       (BIDIR_SHIFTREG_OP_MODE[0]), .D (n_219), .Q
       (BIDIR_SHIFTREG_PARALLEL_OUT[25]));
  DFFHQX1 \current_state_reg[0] (.CK (osc_clk), .D (n_284), .Q
       (current_state[0]));
  DFFHQX1 \current_state_reg[1] (.CK (osc_clk), .D (n_287), .Q
       (current_state[1]));
  DFFHQX1 \current_state_reg[2] (.CK (osc_clk), .D (n_283), .Q
       (current_state[2]));
  DFFHQX1 \current_state_reg[3] (.CK (osc_clk), .D (n_261), .Q
       (current_state[3]));
  DFFHQX1 \current_state_reg[5] (.CK (osc_clk), .D (n_279), .Q
       (current_state[5]));
  SDFFRHQX1 dv_reg(.RN (n_18), .CK (osc_clk), .D (n_286), .SI (dv), .SE
       (n_51), .Q (dv));
  SDFFRHQX1 \internal_f_bit_locator_reg[1] (.RN (n_18), .CK (osc_clk),
       .D (n_133), .SI (internal_f_bit_locator[1]), .SE (n_51), .Q
       (internal_f_bit_locator[1]));
  SDFFRHQX1 \internal_f_bit_locator_reg[2] (.RN (n_18), .CK (osc_clk),
       .D (n_0), .SI (internal_f_bit_locator[2]), .SE (n_51), .Q
       (internal_f_bit_locator[2]));
  SDFFRHQX1 \internal_f_bit_locator_reg[3] (.RN (n_18), .CK (osc_clk),
       .D (n_69), .SI (internal_f_bit_locator[3]), .SE (n_51), .Q
       (internal_f_bit_locator[3]));
  SDFFRHQX1 \internal_f_bit_locator_reg[4] (.RN (n_18), .CK (osc_clk),
       .D (n_72), .SI (internal_f_bit_locator[4]), .SE (n_51), .Q
       (internal_f_bit_locator[4]));
  SDFFRHQX1 \internal_f_bit_locator_reg[5] (.RN (n_18), .CK (osc_clk),
       .D (n_71), .SI (internal_f_bit_locator[5]), .SE (n_51), .Q
       (internal_f_bit_locator[5]));
  SDFFRHQX1 \internal_f_bit_locator_reg[6] (.RN (n_18), .CK (osc_clk),
       .D (n_70), .SI (internal_f_bit_locator[6]), .SE (n_51), .Q
       (internal_f_bit_locator[6]));
  SDFFRHQX1 \internal_f_bit_locator_reg[7] (.RN (n_18), .CK (osc_clk),
       .D (n_1), .SI (internal_f_bit_locator[7]), .SE (n_51), .Q
       (internal_f_bit_locator[7]));
  SDFFRHQX1 \internal_interpreted_addr_reg[0] (.RN (n_18), .CK
       (osc_clk), .D (n_49), .SI (internal_interpreted_addr[0]), .SE
       (n_51), .Q (internal_interpreted_addr[0]));
  DFFRHQX1 \internal_interpreted_addr_reg[2] (.RN (n_18), .CK
       (osc_clk), .D (n_177), .Q (internal_interpreted_addr[2]));
  DFFRHQX1 \internal_interpreted_addr_reg[3] (.RN (n_18), .CK
       (osc_clk), .D (n_171), .Q (internal_interpreted_addr[3]));
  DFFRHQX1 \internal_interpreted_addr_reg[6] (.RN (n_18), .CK
       (osc_clk), .D (n_168), .Q (internal_interpreted_addr[6]));
  SDFFRHQX1 internal_oscillator_OUTPUT_CLK_reg(.RN (n_18), .CK (clk),
       .D (n_224), .SI (n_225), .SE (osc_clk), .Q (osc_clk));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[0] (.RN (n_18),
       .CK (clk), .D (n_248), .Q
       (internal_oscillator_clk_cycle_counting[0]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[1] (.RN (n_18),
       .CK (clk), .D (n_239), .Q
       (internal_oscillator_clk_cycle_counting[1]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[3] (.RN (n_18),
       .CK (clk), .D (n_254), .Q
       (internal_oscillator_clk_cycle_counting[3]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[5] (.RN (n_18),
       .CK (clk), .D (n_288), .Q
       (internal_oscillator_clk_cycle_counting[5]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[6] (.RN (n_18),
       .CK (clk), .D (n_291), .Q
       (internal_oscillator_clk_cycle_counting[6]));
  NOR2XL g9872__2398(.A (reset_counters), .B (n_299), .Y (n_300));
  AOI22XL g9874__5107(.A0 (n_97), .A1 (n_297), .B0
       (LOW_PULSE_COUNTING[7]), .B1 (n_96), .Y (n_299));
  AOI21XL g9875__6260(.A0 (n_108), .A1 (n_296), .B0 (reset_counters),
       .Y (n_298));
  XNOR2X1 g9876__4319(.A (LOW_PULSE_COUNTING[7]), .B (n_294), .Y
       (n_297));
  OAI211X1 g9878__8428(.A0 (LOW_PULSE_COUNTING[6]), .A1 (n_285), .B0
       (n_97), .C0 (n_294), .Y (n_296));
  AOI21XL g9879__5526(.A0 (n_112), .A1 (n_293), .B0 (reset_counters),
       .Y (n_295));
  OAI211X1 g9883__6783(.A0 (LOW_PULSE_COUNTING[5]), .A1 (n_281), .B0
       (n_97), .C0 (n_292), .Y (n_293));
  NAND2XL g9884__3680(.A (LOW_PULSE_COUNTING[6]), .B (n_285), .Y
       (n_294));
  INVXL g9885(.A (n_285), .Y (n_292));
  NOR2XL g9888__1617(.A (n_224), .B (n_289), .Y (n_291));
  AOI21XL g9889__2802(.A0 (n_114), .A1 (n_282), .B0 (reset_counters),
       .Y (n_290));
  AOI21XL g9890__1705(.A0 (internal_oscillator_clk_cycle_counting[5]),
       .A1 (n_252), .B0 (internal_oscillator_clk_cycle_counting[6]), .Y
       (n_289));
  NOR2XL g9893__5122(.A (n_224), .B (n_274), .Y (n_288));
  NAND3BXL g9894__8246(.AN (n_275), .B (n_18), .C (n_251), .Y (n_287));
  NOR4X1 g9895__7098(.A (n_59), .B (n_60), .C (n_180), .D (n_277), .Y
       (n_286));
  NAND4XL g9900__6131(.A (n_18), .B (n_148), .C (n_251), .D (n_267), .Y
       (n_284));
  NAND4XL g9901__1881(.A (n_18), .B (n_251), .C (n_253), .D (n_266), .Y
       (n_283));
  OAI211X1 g9902__5115(.A0 (LOW_PULSE_COUNTING[4]), .A1 (n_247), .B0
       (n_97), .C0 (n_268), .Y (n_282));
  AND2X1 g9903__7482(.A (n_281), .B (LOW_PULSE_COUNTING[5]), .Y
       (n_285));
  INVX1 g9904(.A (n_268), .Y (n_281));
  NOR2XL g9905__4733(.A (reset_counters), .B (n_270), .Y (n_280));
  NOR2XL g9906__6161(.A (reset), .B (n_271), .Y (n_279));
  AOI21XL g9907__9315(.A0 (n_110), .A1 (n_265), .B0 (reset_counters),
       .Y (n_278));
  OAI211X1 g9909__9945(.A0 (internal_f_bit_locator[7]), .A1 (n_120),
       .B0 (n_179), .C0 (n_273), .Y (n_277));
  OAI211X1 g9910__2883(.A0 (n_4), .A1 (n_153), .B0 (n_253), .C0
       (n_267), .Y (n_276));
  OAI211X1 g9911__2346(.A0 (n_55), .A1 (n_262), .B0 (n_131), .C0
       (n_255), .Y (n_275));
  XNOR2X1 g9912__1666(.A (internal_oscillator_clk_cycle_counting[5]),
       .B (n_252), .Y (n_274));
  INVXL g9913(.A (n_272), .Y (n_273));
  OAI221X1 g9914__7410(.A0 (internal_f_bit_locator[4]), .A1 (n_119),
       .B0 (internal_f_bit_locator[3]), .B1 (n_76), .C0 (n_260), .Y
       (n_272));
  AOI22XL g9916__6417(.A0 (n_154), .A1 (n_258), .B0 (n_99), .B1
       (n_156), .Y (n_271));
  AOI22XL g9917__5477(.A0 (n_99), .A1 (n_256), .B0
       (HIGH_PULSE_COUNTING[4]), .B1 (n_98), .Y (n_270));
  AOI211XL g9918__2398(.A0 (n_17), .A1 (n_187), .B0 (n_224), .C0
       (n_252), .Y (n_269));
  NAND2XL g9919__5107(.A (LOW_PULSE_COUNTING[4]), .B (n_247), .Y
       (n_268));
  OR2X1 g9922__6260(.A (n_54), .B (n_262), .Y (n_266));
  OAI211X1 g9923__4319(.A0 (LOW_PULSE_COUNTING[3]), .A1 (n_227), .B0
       (n_97), .C0 (n_263), .Y (n_265));
  AOI21XL g9924__8428(.A0 (n_122), .A1 (n_249), .B0 (reset_counters),
       .Y (n_264));
  OR2X1 g9925__5526(.A (n_83), .B (n_262), .Y (n_267));
  INVXL g9926(.A (n_247), .Y (n_263));
  NAND2XL g9927__6783(.A (n_18), .B (n_251), .Y (n_261));
  NAND4XL g9929__3680(.A (HIGH_PULSE_COUNTING[4]), .B (n_5), .C (n_9),
       .D (n_222), .Y (n_262));
  INVXL g9931(.A (n_259), .Y (n_260));
  OAI211X1 g9932__1617(.A0 (internal_f_bit_locator[2]), .A1 (n_77), .B0
       (n_73), .C0 (n_240), .Y (n_259));
  OR4X1 g9933__2802(.A (n_48), .B (n_83), .C (n_117), .D (n_201), .Y
       (n_258));
  AOI21XL g9934__1705(.A0 (n_124), .A1 (n_245), .B0 (reset_counters),
       .Y (n_257));
  XNOR2X1 g9935__5122(.A (HIGH_PULSE_COUNTING[4]), .B (n_188), .Y
       (n_256));
  NAND4XL g9936__8246(.A (LOW_PULSE_COUNTING[3]), .B
       (LOW_PULSE_COUNTING[6]), .C (n_127), .D (n_226), .Y (n_255));
  INVXL g9948(.A (n_250), .Y (n_254));
  OAI211X1 g9949__7098(.A0 (internal_oscillator_clk_cycle_counting[3]),
       .A1 (n_102), .B0 (n_187), .C0 (n_225), .Y (n_250));
  OAI211X1 g9950__6131(.A0 (HIGH_PULSE_COUNTING[3]), .A1 (n_157), .B0
       (n_99), .C0 (n_188), .Y (n_249));
  NAND4XL g9951__1881(.A (LOW_PULSE_COUNTING[4]), .B (n_151), .C
       (n_145), .D (n_226), .Y (n_253));
  NOR2XL g9952__5115(.A (n_17), .B (n_187), .Y (n_252));
  AOI211XL g9953__7482(.A0 (current_state[3]), .A1 (n_98), .B0 (n_126),
       .C0 (n_213), .Y (n_251));
  NAND2XL g9961__4733(.A (internal_oscillator_clk_cycle_counting[0]),
       .B (n_225), .Y (n_248));
  OAI2BB1X1 g9981__6161(.A0N (BIDIR_SHIFTREG_OP_MODE[2]), .A1N (n_190),
       .B0 (n_152), .Y (n_246));
  OAI211X1 g9982__9315(.A0 (LOW_PULSE_COUNTING[2]), .A1 (n_53), .B0
       (n_97), .C0 (n_155), .Y (n_245));
  AOI21XL g9983__9945(.A0 (n_125), .A1 (n_163), .B0 (reset_counters),
       .Y (n_244));
  OAI2BB1X1 g9984__2883(.A0N (BIDIR_SHIFTREG_OP_MODE[0]), .A1N (n_190),
       .B0 (n_152), .Y (n_243));
  NOR3BXL g9985__2346(.AN (BIDIR_SHIFTREG_OP_MODE[1]), .B (n_153), .C
       (n_189), .Y (n_242));
  OAI221X1 g9986__1666(.A0 (n_27), .A1 (n_95), .B0 (n_25), .B1 (n_91),
       .C0 (n_203), .Y (n_241));
  NOR4X1 g9987__7410(.A (F_BIT_LOCATOR[0]), .B (n_75), .C (n_78), .D
       (n_186), .Y (n_240));
  NOR3BXL g9988__6417(.AN (n_66), .B (n_58), .C (n_224), .Y (n_239));
  OAI221X1 g9989__5477(.A0 (n_42), .A1 (n_95), .B0 (n_27), .B1 (n_93),
       .C0 (n_198), .Y (n_238));
  OAI221X1 g9990__2398(.A0 (n_41), .A1 (n_93), .B0 (n_38), .B1 (n_91),
       .C0 (n_193), .Y (n_237));
  OAI221X1 g9991__5107(.A0 (n_19), .A1 (n_93), .B0 (n_35), .B1 (n_91),
       .C0 (n_192), .Y (n_236));
  OAI221X1 g9992__6260(.A0 (n_36), .A1 (n_81), .B0 (n_42), .B1 (n_93),
       .C0 (n_197), .Y (n_235));
  OAI221X1 g9993__4319(.A0 (n_20), .A1 (n_95), .B0 (n_29), .B1 (n_91),
       .C0 (n_202), .Y (n_234));
  OAI221X1 g9994__8428(.A0 (n_19), .A1 (n_81), .B0 (n_38), .B1 (n_93),
       .C0 (n_196), .Y (n_233));
  OAI221X1 g9995__5526(.A0 (n_22), .A1 (n_81), .B0 (n_23), .B1 (n_93),
       .C0 (n_195), .Y (n_232));
  OAI221X1 g9996__6783(.A0 (n_40), .A1 (n_81), .B0 (n_37), .B1 (n_93),
       .C0 (n_194), .Y (n_231));
  OAI221X1 g9997__3680(.A0 (n_20), .A1 (n_81), .B0 (n_21), .B1 (n_93),
       .C0 (n_200), .Y (n_230));
  OAI221X1 g9998__1617(.A0 (n_38), .A1 (n_95), .B0 (n_19), .B1 (n_91),
       .C0 (n_199), .Y (n_229));
  AOI211XL g9999__2802(.A0 (n_15), .A1 (n_66), .B0 (n_102), .C0
       (n_224), .Y (n_228));
  AND2X1 g10000__1705(.A (n_227), .B (LOW_PULSE_COUNTING[3]), .Y
       (n_247));
  INVX1 g10001(.A (n_155), .Y (n_227));
  INVX1 g10002(.A (n_224), .Y (n_225));
  NAND3BXL g10003__5122(.AN (n_126), .B (n_146), .C (n_150), .Y
       (n_223));
  NOR2XL g10004__8246(.A (n_82), .B (n_191), .Y (n_222));
  OAI211X1 g10005__7098(.A0 (n_44), .A1 (n_116), .B0 (n_141), .C0
       (n_134), .Y (n_221));
  NAND2BXL g10006__6131(.AN (n_126), .B (n_162), .Y (n_220));
  OAI211X1 g10007__1881(.A0 (n_44), .A1 (n_95), .B0 (n_149), .C0
       (n_140), .Y (n_219));
  AOI21XL g10008__5115(.A0 (n_113), .A1 (n_129), .B0 (reset_counters),
       .Y (n_218));
  NOR2XL g10009__7482(.A (HIGH_PULSE_COUNTING[4]), .B (n_191), .Y
       (n_226));
  NOR3BXL g10027__4733(.AN (internal_oscillator_clk_cycle_counting[5]),
       .B (n_17), .C (n_144), .Y (n_224));
  OAI221X1 g10028__6161(.A0 (n_38), .A1 (n_116), .B0 (n_37), .B1
       (n_91), .C0 (n_161), .Y (n_217));
  OAI221X1 g10029__9315(.A0 (n_32), .A1 (n_93), .B0 (n_44), .B1 (n_91),
       .C0 (n_165), .Y (n_216));
  OAI211X1 g10030__9945(.A0 (n_44), .A1 (n_81), .B0 (n_111), .C0
       (n_174), .Y (n_215));
  OAI221X1 g10031__2883(.A0 (n_26), .A1 (n_116), .B0 (n_29), .B1
       (n_95), .C0 (n_181), .Y (n_214));
  NOR3XL g10032__2346(.A (n_103), .B (n_154), .C (n_156), .Y (n_213));
  OAI221X1 g10033__1666(.A0 (n_29), .A1 (n_116), .B0 (n_32), .B1
       (n_91), .C0 (n_184), .Y (n_212));
  OAI221X1 g10034__7410(.A0 (n_31), .A1 (n_116), .B0 (n_43), .B1
       (n_91), .C0 (n_178), .Y (n_211));
  OAI221X1 g10035__6417(.A0 (n_40), .A1 (n_93), .B0 (n_20), .B1 (n_91),
       .C0 (n_158), .Y (n_210));
  OAI221X1 g10036__5477(.A0 (n_28), .A1 (n_116), .B0 (n_20), .B1
       (n_93), .C0 (n_166), .Y (n_209));
  OAI221X1 g10037__2398(.A0 (n_38), .A1 (n_81), .B0 (n_25), .B1 (n_93),
       .C0 (n_159), .Y (n_208));
  OAI221X1 g10038__5107(.A0 (n_20), .A1 (n_116), .B0 (n_28), .B1
       (n_91), .C0 (n_164), .Y (n_207));
  OAI221X1 g10039__6260(.A0 (n_27), .A1 (n_116), .B0 (n_42), .B1
       (n_81), .C0 (n_147), .Y (n_206));
  OAI221X1 g10040__4319(.A0 (n_21), .A1 (n_116), .B0 (n_22), .B1
       (n_93), .C0 (n_160), .Y (n_205));
  OAI221X1 g10041__8428(.A0 (n_31), .A1 (n_81), .B0 (n_29), .B1 (n_93),
       .C0 (n_175), .Y (n_204));
  AOI222X1 g10042__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .C1 (n_92), .Y (n_203));
  AOI222X1 g10043__6783(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .C1 (n_92), .Y (n_202));
  OAI222XL g10044__3680(.A0 (n_5), .A1 (n_127), .B0
       (LOW_PULSE_COUNTING[6]), .B1 (n_107), .C0
       (HIGH_PULSE_COUNTING[4]), .C1 (LOW_PULSE_COUNTING[4]), .Y
       (n_201));
  AOI222X1 g10045__1617(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .C1 (n_2), .Y (n_200));
  AOI222X1 g10046__2802(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_92), .Y (n_199));
  AOI222X1 g10047__1705(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .C1 (n_2), .Y (n_198));
  AOI222X1 g10048__5122(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_2), .Y (n_197));
  AOI222X1 g10049__8246(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .C1 (n_2), .Y (n_196));
  AOI222X1 g10050__7098(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .C1 (n_2), .Y (n_195));
  AOI222X1 g10051__6131(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .C1 (n_2), .Y (n_194));
  AOI222X1 g10052__1881(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_80), .Y (n_193));
  AOI222X1 g10053__5115(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .B1 (n_115), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .C1 (n_80), .Y (n_192));
  INVXL g10054(.A (n_190), .Y (n_189));
  MXI2XL g10055__7482(.A (n_118), .B (F_BIT_LOCATOR[1]), .S0
       (internal_f_bit_locator[1]), .Y (n_186));
  NOR2XL g10056__4733(.A (reset_counters), .B (n_135), .Y (n_185));
  AOI222X1 g10057__6161(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .B1 (n_92), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .C1 (n_94), .Y (n_184));
  NOR2XL g10058__9315(.A (reset_counters), .B (n_130), .Y (n_183));
  NOR2XL g10059__9945(.A (reset_counters), .B (n_132), .Y (n_182));
  AOI222X1 g10060__2883(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .B1 (n_92), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .C1 (n_2), .Y (n_181));
  MXI2XL g10061__2346(.A (n_121), .B (F_BIT_LOCATOR[5]), .S0
       (internal_f_bit_locator[5]), .Y (n_180));
  OAI31X1 g10062__1666(.A0 (F_BIT_LOCATOR[6]), .A1
       (internal_f_bit_locator[6]), .A2 (n_74), .B0 (n_50), .Y (n_179));
  AOI222X1 g10063__7410(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .B1 (n_92), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .C1 (n_94), .Y (n_178));
  NAND2BXL g10064__6417(.AN (n_117), .B (n_154), .Y (n_191));
  AOI21XL g10069__5477(.A0 (n_39), .A1 (n_105), .B0 (n_156), .Y
       (n_190));
  NAND2XL g10070__2398(.A (HIGH_PULSE_COUNTING[3]), .B (n_157), .Y
       (n_188));
  NAND2XL g10071__5107(.A (internal_oscillator_clk_cycle_counting[3]),
       .B (n_102), .Y (n_187));
  INVXL g10072(.A (n_172), .Y (n_177));
  INVXL g10073(.A (n_167), .Y (n_176));
  AOI222X1 g10074__6260(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .B1 (n_2), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .C1 (n_115), .Y (n_175));
  AOI222X1 g10075__4319(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .B1 (n_92), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .C1 (n_115), .Y (n_174));
  OAI31X1 g10076__8428(.A0 (n_41), .A1 (n_25), .A2 (n_51), .B0 (n_88),
       .Y (n_173));
  AOI32X1 g10077__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .A2 (n_52), .B0
       (internal_interpreted_addr[2]), .B1 (n_51), .Y (n_172));
  OAI31X1 g10078__6783(.A0 (n_38), .A1 (n_23), .A2 (n_51), .B0 (n_87),
       .Y (n_171));
  OAI31X1 g10079__3680(.A0 (n_37), .A1 (n_19), .A2 (n_51), .B0 (n_85),
       .Y (n_170));
  OAI31X1 g10080__1617(.A0 (n_22), .A1 (n_40), .A2 (n_51), .B0 (n_86),
       .Y (n_169));
  OAI31X1 g10081__2802(.A0 (n_21), .A1 (n_35), .A2 (n_51), .B0 (n_89),
       .Y (n_168));
  AOI32X1 g10082__1705(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .A2 (n_52), .B0
       (internal_interpreted_addr[7]), .B1 (n_51), .Y (n_167));
  AOI222X1 g10083__5122(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .B1 (n_2), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .C1 (n_94), .Y (n_166));
  AOI222X1 g10084__8246(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .B1 (n_80), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .C1 (n_115), .Y (n_165));
  AOI222X1 g10085__7098(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .B1 (n_92), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .C1 (n_94), .Y (n_164));
  OAI211X1 g10086__6131(.A0 (HIGH_PULSE_COUNTING[2]), .A1 (n_64), .B0
       (n_99), .C0 (n_104), .Y (n_163));
  AOI32X1 g10087__1881(.A0 (current_state[2]), .A1 (current_state[0]),
       .A2 (n_105), .B0 (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .B1 (n_106),
       .Y (n_162));
  AOI222X1 g10088__5115(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .B1 (n_92), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_94), .Y (n_161));
  AOI222X1 g10089__7482(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .B1 (n_2), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .C1 (n_94), .Y (n_160));
  AOI222X1 g10090__4733(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .B1 (n_2), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .C1 (n_115), .Y (n_159));
  AOI222X1 g10091__6161(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .B1 (n_80), .C0
       (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .C1 (n_115), .Y (n_158));
  INVX1 g10092(.A (n_104), .Y (n_157));
  INVX1 g10093(.A (n_152), .Y (n_153));
  OAI21XL g10094__9315(.A0 (n_54), .A1 (n_84), .B0
       (LOW_PULSE_COUNTING[6]), .Y (n_151));
  OAI2BB1X1 g10095__9945(.A0N (n_47), .A1N (n_105), .B0
       (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .Y (n_150));
  NAND2XL g10096__2883(.A (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B
       (n_115), .Y (n_149));
  OAI21XL g10097__2346(.A0 (n_90), .A1 (n_99), .B0 (n_103), .Y (n_148));
  AOI22XL g10098__1666(.A0 (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .A1
       (n_92), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .B1 (n_2), .Y
       (n_147));
  NAND4XL g10099__7410(.A (current_state[1]), .B (current_state[2]), .C
       (n_39), .D (n_62), .Y (n_146));
  OAI21XL g10100__6417(.A0 (n_55), .A1 (n_82), .B0 (n_5), .Y (n_145));
  NAND4BXL g10101__5477(.AN (n_58), .B
       (internal_oscillator_clk_cycle_counting[6]), .C
       (internal_oscillator_clk_cycle_counting[3]), .D
       (internal_oscillator_clk_cycle_counting[2]), .Y (n_144));
  NOR4BX1 g10102__2398(.AN (current_state[3]), .B (current_state[5]),
       .C (n_24), .D (n_65), .Y (n_156));
  NAND2XL g10103__5107(.A (LOW_PULSE_COUNTING[2]), .B (n_53), .Y
       (n_155));
  NOR4X1 g10104__6260(.A (current_state[2]), .B (current_state[1]), .C
       (current_state[0]), .D (n_61), .Y (n_154));
  AOI31X1 g10105__4319(.A0 (current_state[2]), .A1 (n_65), .A2 (n_62),
       .B0 (n_126), .Y (n_152));
  INVXL g10106(.A (n_139), .Y (n_143));
  INVXL g10107(.A (n_136), .Y (n_142));
  AOI22XL g10108__8428(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .A1
       (n_80), .B0 (BIDIR_SHIFTREG_PT2272_BIT_IN[0]), .B1 (n_2), .Y
       (n_141));
  AOI22XL g10109__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A1
       (n_92), .B0 (BIDIR_SHIFTREG_PT2272_BIT_IN[1]), .B1 (n_2), .Y
       (n_140));
  AOI32X1 g10110__6783(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A2 (n_101), .B0 (D[0]), .B1
       (n_100), .Y (n_139));
  OAI31X1 g10111__3680(.A0 (n_32), .A1 (n_31), .A2 (n_100), .B0
       (n_123), .Y (n_138));
  OAI31X1 g10112__1617(.A0 (n_29), .A1 (n_26), .A2 (n_100), .B0
       (n_109), .Y (n_137));
  AOI32X1 g10113__2802(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[16]), .A1
       (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .A2 (n_101), .B0 (D[3]), .B1
       (n_100), .Y (n_136));
  AOI32X1 g10114__1705(.A0 (n_63), .A1 (n_67), .A2 (n_99), .B0
       (HIGH_PULSE_COUNTING[1]), .B1 (n_98), .Y (n_135));
  AOI22XL g10115__5122(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .A1
       (n_94), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[22]), .B1 (n_92), .Y
       (n_134));
  OAI221X1 g10116__8246(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .A1
       (n_27), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .B1 (n_42), .C0
       (n_79), .Y (n_133));
  XNOR2X1 g10117__7098(.A (HIGH_PULSE_COUNTING[0]), .B (n_99), .Y
       (n_132));
  OA22X1 g10118__6131(.A0 (current_state[5]), .A1 (n_96), .B0
       (PREVIOUS_cod_i), .B1 (n_30), .Y (n_131));
  XNOR2X1 g10119__1881(.A (LOW_PULSE_COUNTING[0]), .B (n_97), .Y
       (n_130));
  OAI211X1 g10120__5115(.A0 (LOW_PULSE_COUNTING[0]), .A1
       (LOW_PULSE_COUNTING[1]), .B0 (n_97), .C0 (n_128), .Y (n_129));
  INVXL g10121(.A (n_53), .Y (n_128));
  NAND2XL g10122__7482(.A (HIGH_PULSE_COUNTING[2]), .B (n_98), .Y
       (n_125));
  NAND2XL g10123__4733(.A (LOW_PULSE_COUNTING[2]), .B (n_96), .Y
       (n_124));
  NAND2XL g10124__6161(.A (D[1]), .B (n_100), .Y (n_123));
  NAND2XL g10125__9315(.A (HIGH_PULSE_COUNTING[3]), .B (n_98), .Y
       (n_122));
  AOI221X1 g10126__9945(.A0 (n_45), .A1 (internal_interpreted_addr[5]),
       .B0 (INTERPRETED_ADDR[5]), .B1 (n_14), .C0 (F_BIT_LOCATOR[5]),
       .Y (n_121));
  AOI221X1 g10127__2883(.A0 (n_46), .A1 (internal_interpreted_addr[7]),
       .B0 (INTERPRETED_ADDR[7]), .B1 (n_8), .C0 (F_BIT_LOCATOR[7]), .Y
       (n_120));
  AOI221X1 g10128__2346(.A0 (n_34), .A1 (internal_interpreted_addr[4]),
       .B0 (INTERPRETED_ADDR[4]), .B1 (n_16), .C0 (F_BIT_LOCATOR[4]),
       .Y (n_119));
  AOI221X1 g10129__1666(.A0 (n_33), .A1 (internal_interpreted_addr[1]),
       .B0 (INTERPRETED_ADDR[1]), .B1 (n_13), .C0 (F_BIT_LOCATOR[1]),
       .Y (n_118));
  NOR2XL g10130__7410(.A (n_56), .B (n_84), .Y (n_127));
  NOR2BX1 g10131__6417(.AN (n_103), .B (n_65), .Y (n_126));
  INVX1 g10132(.A (n_116), .Y (n_115));
  NAND2XL g10133__5477(.A (LOW_PULSE_COUNTING[4]), .B (n_96), .Y
       (n_114));
  NAND2XL g10134__2398(.A (LOW_PULSE_COUNTING[1]), .B (n_96), .Y
       (n_113));
  NAND2XL g10135__5107(.A (LOW_PULSE_COUNTING[5]), .B (n_96), .Y
       (n_112));
  NAND2XL g10136__6260(.A (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B (n_2),
       .Y (n_111));
  NAND2XL g10137__4319(.A (LOW_PULSE_COUNTING[3]), .B (n_96), .Y
       (n_110));
  NAND2XL g10138__8428(.A (D[2]), .B (n_100), .Y (n_109));
  NAND2XL g10139__5526(.A (LOW_PULSE_COUNTING[6]), .B (n_96), .Y
       (n_108));
  NOR2BX1 g10140__6783(.AN (n_56), .B (n_82), .Y (n_107));
  OAI211X1 g10141__3680(.A0 (current_state[2]), .A1 (n_30), .B0 (n_39),
       .C0 (n_62), .Y (n_106));
  OR4X1 g10142__1617(.A (LOW_PULSE_COUNTING[0]), .B
       (LOW_PULSE_COUNTING[7]), .C (n_12), .D (n_67), .Y (n_117));
  AOI22XL g10143__2802(.A0 (n_3), .A1 (n_68), .B0
       (BIDIR_SHIFTREG_OP_MODE[1]), .B1 (BIDIR_SHIFTREG_OP_MODE[2]), .Y
       (n_116));
  INVX1 g10144(.A (n_100), .Y (n_101));
  INVX1 g10145(.A (n_99), .Y (n_98));
  INVX1 g10146(.A (n_97), .Y (n_96));
  INVX1 g10147(.A (n_95), .Y (n_94));
  INVX1 g10148(.A (n_93), .Y (n_92));
  INVX1 g10149(.A (n_2), .Y (n_91));
  NOR2XL g10150__1705(.A (PREVIOUS_cod_i), .B (n_39), .Y (n_90));
  NAND2XL g10151__5122(.A (internal_interpreted_addr[6]), .B (n_51), .Y
       (n_89));
  NAND2XL g10152__8246(.A (internal_interpreted_addr[1]), .B (n_51), .Y
       (n_88));
  NAND2XL g10153__7098(.A (internal_interpreted_addr[3]), .B (n_51), .Y
       (n_87));
  NAND2XL g10154__6131(.A (internal_interpreted_addr[5]), .B (n_51), .Y
       (n_86));
  NAND2XL g10155__1881(.A (internal_interpreted_addr[4]), .B (n_51), .Y
       (n_85));
  AND2X1 g10156__5115(.A (n_62), .B (n_30), .Y (n_105));
  NAND2XL g10157__7482(.A (HIGH_PULSE_COUNTING[2]), .B (n_64), .Y
       (n_104));
  AND2X1 g10158__4733(.A (n_62), .B (n_24), .Y (n_103));
  NOR2XL g10159__6161(.A (n_15), .B (n_66), .Y (n_102));
  NAND2XL g10160__9315(.A (dv), .B (n_52), .Y (n_100));
  AND2X1 g10161__9945(.A (PREVIOUS_cod_i), .B (cod_i), .Y (n_99));
  NOR2BX1 g10162__2883(.AN (PREVIOUS_cod_i), .B (cod_i), .Y (n_97));
  NAND2XL g10163__2346(.A (BIDIR_SHIFTREG_OP_MODE[0]), .B (n_68), .Y
       (n_95));
  NAND2XL g10164__1666(.A (n_3), .B (n_57), .Y (n_93));
  INVX1 g10166(.A (n_81), .Y (n_80));
  AOI22XL g10168__7410(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .A1
       (n_25), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .B1 (n_41), .Y
       (n_79));
  CLKXOR2X1 g10169__6417(.A (INTERPRETED_ADDR[0]), .B
       (internal_interpreted_addr[0]), .Y (n_78));
  XNOR2X1 g10170__5477(.A (INTERPRETED_ADDR[2]), .B
       (internal_interpreted_addr[2]), .Y (n_77));
  XNOR2X1 g10171__2398(.A (INTERPRETED_ADDR[3]), .B
       (internal_interpreted_addr[3]), .Y (n_76));
  CLKXOR2X1 g10172__5107(.A (F_BIT_LOCATOR[2]), .B
       (internal_f_bit_locator[2]), .Y (n_75));
  CLKXOR2X1 g10173__6260(.A (INTERPRETED_ADDR[6]), .B
       (internal_interpreted_addr[6]), .Y (n_74));
  XNOR2X1 g10174__4319(.A (F_BIT_LOCATOR[3]), .B
       (internal_f_bit_locator[3]), .Y (n_73));
  OAI22XL g10175__8428(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .A1
       (n_37), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .B1 (n_19), .Y
       (n_72));
  OAI22XL g10176__5526(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .A1
       (n_22), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .B1 (n_40), .Y
       (n_71));
  OAI22XL g10177__6783(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .A1
       (n_21), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .B1 (n_35), .Y
       (n_70));
  OAI22XL g10178__3680(.A0 (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .A1
       (n_38), .B0 (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .B1 (n_23), .Y
       (n_69));
  NAND3BXL g10180__1617(.AN (LOW_PULSE_COUNTING[2]), .B
       (LOW_PULSE_COUNTING[5]), .C (HIGH_PULSE_COUNTING[2]), .Y (n_84));
  AND2X1 g10181__2802(.A (n_55), .B (n_54), .Y (n_83));
  NAND3BXL g10182__1705(.AN (LOW_PULSE_COUNTING[5]), .B
       (LOW_PULSE_COUNTING[2]), .C (n_11), .Y (n_82));
  NAND3BXL g10183__5122(.AN (BIDIR_SHIFTREG_OP_MODE[2]), .B
       (BIDIR_SHIFTREG_OP_MODE[1]), .C (n_3), .Y (n_81));
  INVXL g10184(.A (n_64), .Y (n_63));
  NAND2BXL g10185__8246(.AN (current_state[3]), .B (current_state[5]),
       .Y (n_61));
  NOR2BX1 g10186__7098(.AN (internal_f_bit_locator[4]), .B
       (F_BIT_LOCATOR[4]), .Y (n_60));
  NOR2BX1 g10187__6131(.AN (internal_f_bit_locator[7]), .B
       (F_BIT_LOCATOR[7]), .Y (n_59));
  NOR2XL g10188__1881(.A (BIDIR_SHIFTREG_OP_MODE[1]), .B
       (BIDIR_SHIFTREG_OP_MODE[2]), .Y (n_68));
  OR2X1 g10189__5115(.A (HIGH_PULSE_COUNTING[1]), .B
       (HIGH_PULSE_COUNTING[0]), .Y (n_67));
  NAND2XL g10190__7482(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_66));
  NAND2XL g10191__4733(.A (current_state[1]), .B (current_state[0]), .Y
       (n_65));
  AND2X1 g10192__6161(.A (HIGH_PULSE_COUNTING[0]), .B
       (HIGH_PULSE_COUNTING[1]), .Y (n_64));
  NOR2XL g10194__9315(.A (current_state[3]), .B (current_state[5]), .Y
       (n_62));
  INVX1 g10196(.A (n_52), .Y (n_51));
  NAND2XL g10197__9945(.A (F_BIT_LOCATOR[6]), .B
       (internal_f_bit_locator[6]), .Y (n_50));
  NOR2XL g10198__2883(.A (n_27), .B (n_42), .Y (n_49));
  NOR2XL g10199__2346(.A (n_6), .B (n_9), .Y (n_48));
  NAND2XL g10200__1666(.A (current_state[0]), .B (n_24), .Y (n_47));
  NOR2XL g10201__7410(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_58));
  NOR2BX1 g10202__6417(.AN (BIDIR_SHIFTREG_OP_MODE[2]), .B
       (BIDIR_SHIFTREG_OP_MODE[1]), .Y (n_57));
  NAND2XL g10203__5477(.A (LOW_PULSE_COUNTING[4]), .B (n_10), .Y
       (n_56));
  NAND2XL g10204__2398(.A (HIGH_PULSE_COUNTING[3]), .B (n_7), .Y
       (n_55));
  NAND2XL g10205__5107(.A (LOW_PULSE_COUNTING[3]), .B (n_10), .Y
       (n_54));
  AND2X1 g10206__6260(.A (LOW_PULSE_COUNTING[1]), .B
       (LOW_PULSE_COUNTING[0]), .Y (n_53));
  NOR2XL g10207__4319(.A (BIDIR_SHIFTREG_PARALLEL_OUT[25]), .B (n_44),
       .Y (n_52));
  INVXL g10208(.A (INTERPRETED_ADDR[7]), .Y (n_46));
  INVXL g10209(.A (INTERPRETED_ADDR[5]), .Y (n_45));
  INVX1 g10217(.A (BIDIR_SHIFTREG_PARALLEL_OUT[24]), .Y (n_44));
  INVXL g10218(.A (BIDIR_SHIFTREG_PARALLEL_OUT[23]), .Y (n_43));
  INVX1 g10220(.A (BIDIR_SHIFTREG_PARALLEL_OUT[1]), .Y (n_42));
  INVX1 g10222(.A (BIDIR_SHIFTREG_PARALLEL_OUT[2]), .Y (n_41));
  INVX1 g10223(.A (BIDIR_SHIFTREG_PARALLEL_OUT[11]), .Y (n_40));
  INVX1 g10224(.A (current_state[0]), .Y (n_39));
  INVX1 g10226(.A (BIDIR_SHIFTREG_PARALLEL_OUT[6]), .Y (n_38));
  INVX1 g10227(.A (BIDIR_SHIFTREG_PARALLEL_OUT[8]), .Y (n_37));
  INVX1 g10228(.A (BIDIR_SHIFTREG_PARALLEL_OUT[4]), .Y (n_36));
  INVX1 g10230(.A (BIDIR_SHIFTREG_PARALLEL_OUT[13]), .Y (n_35));
  INVXL g10231(.A (INTERPRETED_ADDR[4]), .Y (n_34));
  INVXL g10232(.A (INTERPRETED_ADDR[1]), .Y (n_33));
  INVX1 g10235(.A (BIDIR_SHIFTREG_PARALLEL_OUT[20]), .Y (n_32));
  INVX1 g10236(.A (BIDIR_SHIFTREG_PARALLEL_OUT[21]), .Y (n_31));
  INVX1 g10237(.A (current_state[1]), .Y (n_30));
  INVX1 g10238(.A (BIDIR_SHIFTREG_PARALLEL_OUT[18]), .Y (n_29));
  INVX1 g10239(.A (BIDIR_SHIFTREG_PARALLEL_OUT[17]), .Y (n_28));
  INVX1 g10240(.A (BIDIR_SHIFTREG_PARALLEL_OUT[0]), .Y (n_27));
  INVX1 g10241(.A (BIDIR_SHIFTREG_PARALLEL_OUT[19]), .Y (n_26));
  INVX1 g10243(.A (BIDIR_SHIFTREG_PARALLEL_OUT[3]), .Y (n_25));
  INVX1 g10244(.A (current_state[2]), .Y (n_24));
  INVX1 g10245(.A (BIDIR_SHIFTREG_PARALLEL_OUT[7]), .Y (n_23));
  INVX1 g10246(.A (BIDIR_SHIFTREG_PARALLEL_OUT[10]), .Y (n_22));
  INVX1 g10247(.A (BIDIR_SHIFTREG_PARALLEL_OUT[12]), .Y (n_21));
  INVX1 g10248(.A (BIDIR_SHIFTREG_PARALLEL_OUT[15]), .Y (n_20));
  INVX1 g10249(.A (BIDIR_SHIFTREG_PARALLEL_OUT[9]), .Y (n_19));
  INVX1 g10253(.A (reset), .Y (n_18));
  DFFSX1 BIDIR_SHIFTREG_ENABLER_reg(.SN (n_18), .CK (osc_clk), .D
       (n_243), .Q (BIDIR_SHIFTREG_OP_MODE[0]), .QN (n_3));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[2] (.RN (n_18), .CK (osc_clk), .D
       (n_244), .Q (HIGH_PULSE_COUNTING[2]), .QN (n_11));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[3] (.RN (n_18), .CK (osc_clk), .D
       (n_264), .Q (HIGH_PULSE_COUNTING[3]), .QN (n_10));
  DFFRX1 \HIGH_PULSE_COUNTING_reg[4] (.RN (n_18), .CK (osc_clk), .D
       (n_280), .Q (HIGH_PULSE_COUNTING[4]), .QN (n_6));
  DFFRX1 \LOW_PULSE_COUNTING_reg[1] (.RN (n_18), .CK (osc_clk), .D
       (n_218), .Q (LOW_PULSE_COUNTING[1]), .QN (n_12));
  DFFRX1 \LOW_PULSE_COUNTING_reg[3] (.RN (n_18), .CK (osc_clk), .D
       (n_278), .Q (LOW_PULSE_COUNTING[3]), .QN (n_7));
  DFFRX1 \LOW_PULSE_COUNTING_reg[4] (.RN (n_18), .CK (osc_clk), .D
       (n_290), .Q (LOW_PULSE_COUNTING[4]), .QN (n_9));
  DFFRX1 \LOW_PULSE_COUNTING_reg[6] (.RN (n_18), .CK (osc_clk), .D
       (n_298), .Q (LOW_PULSE_COUNTING[6]), .QN (n_5));
  DFFRX1 \internal_interpreted_addr_reg[1] (.RN (n_18), .CK (osc_clk),
       .D (n_173), .Q (internal_interpreted_addr[1]), .QN (n_13));
  DFFRX1 \internal_interpreted_addr_reg[4] (.RN (n_18), .CK (osc_clk),
       .D (n_170), .Q (internal_interpreted_addr[4]), .QN (n_16));
  DFFRX1 \internal_interpreted_addr_reg[5] (.RN (n_18), .CK (osc_clk),
       .D (n_169), .Q (internal_interpreted_addr[5]), .QN (n_14));
  DFFRX1 \internal_interpreted_addr_reg[7] (.RN (n_18), .CK (osc_clk),
       .D (n_176), .Q (internal_interpreted_addr[7]), .QN (n_8));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[2] (.RN (n_18),
       .CK (clk), .D (n_228), .Q
       (internal_oscillator_clk_cycle_counting[2]), .QN (n_15));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[4] (.RN (n_18),
       .CK (clk), .D (n_269), .Q
       (internal_oscillator_clk_cycle_counting[4]), .QN (n_17));
  DFFRX1 reset_counters_reg(.RN (n_18), .CK (osc_clk), .D (n_276), .Q
       (reset_counters), .QN (n_4));
  NOR2BX1 g2__8428(.AN (n_57), .B (n_3), .Y (n_2));
  MXI2XL g10284__5526(.A (n_20), .B (BIDIR_SHIFTREG_PARALLEL_OUT[15]),
       .S0 (BIDIR_SHIFTREG_PARALLEL_OUT[14]), .Y (n_1));
  MXI2XL g10285__6783(.A (n_36), .B (BIDIR_SHIFTREG_PARALLEL_OUT[4]),
       .S0 (BIDIR_SHIFTREG_PARALLEL_OUT[5]), .Y (n_0));
endmodule

