
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 29 2024 09:19:32 -03 (Nov 29 2024 12:19:32 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count);
  input clk, m, rst;
  output [15:0] count;
  wire clk, m, rst;
  wire [15:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44;
  JKFFRXL \count_reg[15] (.RN (rst), .CK (clk), .J (n_44), .K (n_44),
       .Q (count[15]), .QN (UNCONNECTED));
  JKFFRXL \count_reg[11] (.RN (rst), .CK (clk), .J (n_43), .K (n_43),
       .Q (count[11]), .QN (UNCONNECTED0));
  JKFFRXL \count_reg[14] (.RN (rst), .CK (clk), .J (n_42), .K (n_42),
       .Q (count[14]), .QN (UNCONNECTED1));
  AOI211XL g1373__2398(.A0 (n_37), .A1 (count[14]), .B0 (n_40), .C0
       (n_2), .Y (n_44));
  SDFFRHQX1 \count_reg[10] (.RN (rst), .CK (clk), .D (n_39), .SI
       (count[10]), .SE (n_38), .Q (count[10]));
  JKFFRXL \count_reg[13] (.RN (rst), .CK (clk), .J (n_41), .K (n_41),
       .Q (count[13]), .QN (n_1));
  INVXL g1376(.A (n_40), .Y (n_42));
  AOI221XL g1377__5107(.A0 (n_35), .A1 (count[10]), .B0 (n_39), .B1
       (count[8]), .C0 (n_38), .Y (n_43));
  SDFFRHQX1 \count_reg[12] (.RN (rst), .CK (clk), .D (n_37), .SI
       (count[12]), .SE (n_32), .Q (count[12]));
  OAI221XL g1378__6260(.A0 (n_37), .A1 (count[13]), .B0 (n_1), .B1
       (count[12]), .C0 (n_41), .Y (n_40));
  SDFFRHQX1 \count_reg[9] (.RN (rst), .CK (clk), .D (count[9]), .SI
       (n_34), .SE (n_33), .Q (count[9]));
  JKFFRXL \count_reg[7] (.RN (rst), .CK (clk), .J (n_36), .K (n_36), .Q
       (count[7]), .QN (UNCONNECTED2));
  AOI22XL g1380__4319(.A0 (n_28), .A1 (n_37), .B0 (count[12]), .B1
       (n_22), .Y (n_41));
  OAI221XL g1381__8428(.A0 (n_35), .A1 (count[9]), .B0 (n_34), .B1
       (count[8]), .C0 (n_33), .Y (n_38));
  SDFFRHQX1 \count_reg[8] (.RN (rst), .CK (clk), .D (count[8]), .SI
       (n_35), .SE (n_31), .Q (count[8]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_30), .SI
       (count[6]), .SE (n_29), .Q (count[6]));
  OAI221XL g1383__5526(.A0 (n_26), .A1 (m), .B0 (n_20), .B1 (n_24), .C0
       (n_31), .Y (n_32));
  AOI22XL g1384__6783(.A0 (n_27), .A1 (n_35), .B0 (count[8]), .B1
       (n_21), .Y (n_33));
  AOI221XL g1394__3680(.A0 (count[4]), .A1 (n_30), .B0 (n_19), .B1
       (count[6]), .C0 (n_29), .Y (n_36));
  NAND2BXL g1388__1617(.AN (n_27), .B (n_26), .Y (n_28));
  JKFFRXL \count_reg[3] (.RN (rst), .CK (clk), .J (n_25), .K (n_25), .Q
       (count[3]), .QN (UNCONNECTED3));
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (count[5]), .SI
       (n_18), .SE (n_17), .Q (count[5]));
  AOI22XL g1389__2802(.A0 (n_23), .A1 (n_24), .B0 (m), .B1 (n_16), .Y
       (n_31));
  OR2X1 g1393__1705(.A (n_23), .B (m), .Y (n_27));
  NAND2BXL g1387__5122(.AN (n_21), .B (n_20), .Y (n_22));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (count[4]), .SI
       (n_19), .SE (n_14), .Q (count[4]));
  OAI221XL g1397__8246(.A0 (n_19), .A1 (count[5]), .B0 (n_18), .B1
       (count[4]), .C0 (n_17), .Y (n_29));
  OR2X1 g1392__7098(.A (n_16), .B (n_24), .Y (n_21));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (count[2]), .SI
       (n_15), .SE (n_11), .Q (count[2]));
  NAND4XL g1396__6131(.A (n_9), .B (n_19), .C (n_18), .D (n_30), .Y
       (n_23));
  AOI221XL g1399__1881(.A0 (n_7), .A1 (count[2]), .B0 (n_15), .B1
       (count[1]), .C0 (n_12), .Y (n_25));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (m), .SI (n_24),
       .SE (n_5), .Q (count[1]));
  AOI21XL g1400__5115(.A0 (n_13), .A1 (count[4]), .B0 (n_10), .Y
       (n_17));
  NAND4XL g1395__7482(.A (n_6), .B (count[4]), .C (count[5]), .D
       (count[6]), .Y (n_16));
  AOI22XL g1401__4733(.A0 (n_8), .A1 (n_24), .B0 (m), .B1 (n_13), .Y
       (n_14));
  INVXL g1402(.A (n_11), .Y (n_12));
  OAI222XL g1403__6161(.A0 (n_3), .A1 (count[4]), .B0 (n_19), .B1 (m),
       .C0 (n_24), .C1 (count[4]), .Y (n_10));
  NOR2XL g1406__9315(.A (n_8), .B (count[7]), .Y (n_9));
  AOI221XL g1404__9945(.A0 (count[0]), .A1 (n_24), .B0 (n_7), .B1 (m),
       .C0 (n_4), .Y (n_11));
  NOR2BXL g1405__2883(.AN (count[7]), .B (n_13), .Y (n_6));
  AOI21XL g1412__2346(.A0 (n_7), .A1 (count[0]), .B0 (n_4), .Y (n_5));
  INVXL g1409(.A (n_3), .Y (n_8));
  NOR4BXL g1408__1666(.AN (n_39), .B (count[8]), .C (count[9]), .D
       (count[11]), .Y (n_26));
  NOR4BXL g1411__7410(.AN (n_15), .B (count[1]), .C (count[0]), .D
       (count[3]), .Y (n_3));
  AND4X1 g1407__6417(.A (count[8]), .B (count[9]), .C (count[10]), .D
       (count[11]), .Y (n_20));
  DFFRHQX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q
       (count[0]));
  NOR2XL g1414__5477(.A (n_37), .B (count[14]), .Y (n_2));
  NOR2XL g1415__2398(.A (n_7), .B (count[0]), .Y (n_4));
  NAND4XL g1410__5107(.A (count[1]), .B (count[0]), .C (count[3]), .D
       (count[2]), .Y (n_13));
  INVXL g1422(.A (count[0]), .Y (n_0));
  INVXL g1417(.A (count[9]), .Y (n_34));
  INVXL g1424(.A (count[10]), .Y (n_39));
  INVXL g1423(.A (count[5]), .Y (n_18));
  INVXL g1418(.A (count[1]), .Y (n_7));
  INVXL g1421(.A (count[6]), .Y (n_30));
  INVXL g1420(.A (count[2]), .Y (n_15));
  INVXL g1426(.A (count[8]), .Y (n_35));
  INVXL g1425(.A (count[12]), .Y (n_37));
  INVXL g1427(.A (count[4]), .Y (n_19));
  INVXL g1419(.A (m), .Y (n_24));
endmodule

