
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Dec 20 2024 16:46:02 -03 (Dec 20 2024 19:46:02 UTC)

// Verification Directory fv/BIT_GENERATOR 

module BIT_GENERATOR(osc_clk, rst, enable_generation, input_bit,
     bit_sent, output_signal);
  input osc_clk, rst, enable_generation;
  input [1:0] input_bit;
  output bit_sent, output_signal;
  wire osc_clk, rst, enable_generation;
  wire [1:0] input_bit;
  wire bit_sent, output_signal;
  wire [7:0] current_state;
  wire [6:0] pulse_counter_sync;
  wire [4:0] pulse_counter;
  wire UNCONNECTED, enable_pulse_counting, enable_pulse_counting_sync,
       is_first_run, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_90;
  DFFHQX1 \current_state_reg[0] (.CK (osc_clk), .D (n_84), .Q
       (current_state[0]));
  DFFHQX1 \current_state_reg[4] (.CK (osc_clk), .D (n_79), .Q
       (current_state[4]));
  DFFHQX1 \current_state_reg[2] (.CK (osc_clk), .D (n_80), .Q
       (current_state[2]));
  DFFHQX1 \current_state_reg[1] (.CK (osc_clk), .D (n_83), .Q
       (current_state[1]));
  DFFHQX1 \current_state_reg[3] (.CK (osc_clk), .D (n_82), .Q
       (current_state[3]));
  OAI2BB1X1 g2697__2398(.A0N (current_state[0]), .A1N (n_73), .B0
       (n_77), .Y (n_84));
  OAI211X1 g2713__5107(.A0 (n_41), .A1 (n_81), .B0 (n_54), .C0 (n_71),
       .Y (n_83));
  OAI211X1 g2716__6260(.A0 (n_33), .A1 (n_81), .B0 (n_55), .C0 (n_72),
       .Y (n_82));
  OAI31X1 g2717__4319(.A0 (input_bit[0]), .A1 (input_bit[1]), .A2
       (n_78), .B0 (n_74), .Y (n_80));
  TLATXL bit_sent_reg(.G (n_76), .D (n_68), .Q (bit_sent), .QN
       (UNCONNECTED));
  OAI211X1 g2703__8428(.A0 (n_37), .A1 (n_78), .B0 (n_65), .C0 (n_70),
       .Y (n_79));
  OAI2BB1X1 g2699__5526(.A0N (n_19), .A1N (n_75), .B0
       (enable_generation), .Y (n_77));
  SDFFRHQX1 output_signal_reg(.RN (rst), .CK (osc_clk), .D
       (output_signal), .SI (n_69), .SE (n_66), .Q (output_signal));
  NAND2XL g2701__6783(.A (n_78), .B (n_75), .Y (n_76));
  AOI21XL g2720__3680(.A0 (current_state[2]), .A1 (n_73), .B0 (n_51),
       .Y (n_74));
  NAND2XL g2732__1617(.A (current_state[3]), .B (n_73), .Y (n_72));
  NAND2XL g2733__2802(.A (current_state[1]), .B (n_73), .Y (n_71));
  NAND2XL g2734__1705(.A (current_state[4]), .B (n_73), .Y (n_70));
  DFFHQX1 \pulse_counter_sync_reg[6] (.CK (osc_clk), .D (n_67), .Q
       (pulse_counter_sync[6]));
  NAND2XL g2702__5122(.A (rst), .B (n_63), .Y (n_75));
  DFFHQX1 \pulse_counter_sync_reg[5] (.CK (osc_clk), .D (n_64), .Q
       (pulse_counter_sync[5]));
  OAI221X1 g2739__8246(.A0 (is_first_run), .A1 (n_68), .B0
       (pulse_counter[3]), .B1 (n_50), .C0 (n_56), .Y (n_69));
  INVXL g2707(.A (n_60), .Y (n_67));
  NOR2XL g2743__7098(.A (n_29), .B (n_66), .Y (n_73));
  NAND3BXL g2705__6131(.AN (n_62), .B (rst), .C (n_61), .Y (n_65));
  INVXL g2715(.A (n_59), .Y (n_64));
  OAI22XL g2706__1881(.A0 (n_45), .A1 (n_58), .B0 (n_62), .B1 (n_61),
       .Y (n_63));
  OAI211X1 g2708__5115(.A0 (pulse_counter_sync[6]), .A1 (n_47), .B0
       (enable_pulse_counting_sync), .C0 (n_61), .Y (n_60));
  DFFSHQX1 is_first_run_reg(.SN (rst), .CK (osc_clk), .D (n_48), .Q
       (is_first_run));
  DFFHQX1 \pulse_counter_reg[4] (.CK (osc_clk), .D (n_52), .Q
       (pulse_counter[4]));
  OAI211X1 g2718__7482(.A0 (pulse_counter_sync[5]), .A1 (n_43), .B0
       (enable_pulse_counting_sync), .C0 (n_39), .Y (n_59));
  NAND3BXL g2748__4733(.AN (n_57), .B (n_62), .C (n_58), .Y (n_66));
  SDFFRHQX1 enable_pulse_counting_reg(.RN (rst), .CK (osc_clk), .D
       (enable_pulse_counting), .SI (n_35), .SE (n_57), .Q
       (enable_pulse_counting));
  OA22X1 g2747__6161(.A0 (n_62), .A1 (n_17), .B0 (pulse_counter[2]),
       .B1 (n_49), .Y (n_56));
  DFFHQX1 \pulse_counter_sync_reg[4] (.CK (osc_clk), .D (n_44), .Q
       (pulse_counter_sync[4]));
  DFFHQX1 \pulse_counter_reg[3] (.CK (osc_clk), .D (n_40), .Q
       (pulse_counter[3]));
  NAND3BXL g2760__9315(.AN (input_bit[0]), .B (input_bit[1]), .C
       (n_53), .Y (n_55));
  NAND3BXL g2758__9945(.AN (input_bit[1]), .B (input_bit[0]), .C
       (n_53), .Y (n_54));
  INVXL g2726(.A (n_46), .Y (n_52));
  DFFHQX1 \pulse_counter_sync_reg[3] (.CK (osc_clk), .D (n_32), .Q
       (pulse_counter_sync[3]));
  NOR2XL g2722__2883(.A (n_30), .B (n_81), .Y (n_51));
  OA21X1 g2751__2346(.A0 (pulse_counter[2]), .A1 (n_42), .B0 (n_49), .Y
       (n_50));
  MX2X1 g2755__1666(.A (is_first_run), .B (n_34), .S0 (n_57), .Y
       (n_48));
  NAND2XL g2714__7410(.A (pulse_counter_sync[6]), .B (n_47), .Y (n_61));
  OAI211X1 g2727__6417(.A0 (pulse_counter[4]), .A1 (n_26), .B0
       (enable_pulse_counting), .C0 (n_45), .Y (n_46));
  AOI211XL g2728__5477(.A0 (n_25), .A1 (n_27), .B0 (n_36), .C0 (n_43),
       .Y (n_44));
  AND2X1 g2759__2398(.A (n_42), .B (n_41), .Y (n_58));
  INVXL g2736(.A (n_31), .Y (n_40));
  INVXL g2719(.A (n_47), .Y (n_39));
  INVXL g2762(.A (n_34), .Y (n_35));
  OA21X1 g2761__6260(.A0 (n_0), .A1 (n_33), .B0 (n_41), .Y (n_49));
  AND2X1 g2725__4319(.A (n_43), .B (pulse_counter_sync[5]), .Y (n_47));
  INVXL g2737(.A (n_28), .Y (n_32));
  OAI211X1 g2738__8428(.A0 (pulse_counter[3]), .A1 (n_20), .B0
       (enable_pulse_counting), .C0 (n_22), .Y (n_31));
  NAND2XL g2729__5526(.A (rst), .B (n_45), .Y (n_81));
  INVXL g2766(.A (n_53), .Y (n_78));
  NAND2BXL g2765__6783(.AN (n_68), .B (n_37), .Y (n_34));
  AND2X1 g2768__3680(.A (n_33), .B (n_30), .Y (n_42));
  NOR2XL g2769__1617(.A (n_29), .B (n_68), .Y (n_53));
  OAI211X1 g2740__2802(.A0 (pulse_counter_sync[3]), .A1 (n_23), .B0
       (enable_pulse_counting_sync), .C0 (n_27), .Y (n_28));
  DFFHQX1 \pulse_counter_sync_reg[2] (.CK (osc_clk), .D (n_24), .Q
       (pulse_counter_sync[2]));
  DFFHQX1 \pulse_counter_reg[2] (.CK (osc_clk), .D (n_21), .Q
       (pulse_counter[2]));
  DFFHQX1 \pulse_counter_reg[1] (.CK (osc_clk), .D (n_14), .Q
       (pulse_counter[1]));
  NAND2XL g2735__1705(.A (pulse_counter[4]), .B (n_26), .Y (n_45));
  DFFHQX1 \pulse_counter_sync_reg[1] (.CK (osc_clk), .D (n_15), .Q
       (pulse_counter_sync[1]));
  NOR2XL g2741__5122(.A (n_25), .B (n_27), .Y (n_43));
  AOI211XL g2757__8246(.A0 (n_7), .A1 (n_16), .B0 (n_36), .C0 (n_23),
       .Y (n_24));
  NAND3BXL g2770__7098(.AN (current_state[3]), .B (current_state[2]),
       .C (n_18), .Y (n_30));
  NAND2XL g2773__6131(.A (current_state[0]), .B (n_57), .Y (n_68));
  INVXL g2742(.A (n_26), .Y (n_22));
  AOI211XL g2754__1881(.A0 (n_8), .A1 (n_11), .B0 (n_3), .C0 (n_20), .Y
       (n_21));
  NAND3XL g2777__5115(.A (rst), .B (n_10), .C (n_18), .Y (n_19));
  NAND3BXL g2779__7482(.AN (current_state[2]), .B (current_state[3]),
       .C (n_18), .Y (n_33));
  NAND3BXL g2767__4733(.AN (pulse_counter_sync[6]), .B (n_16), .C
       (n_1), .Y (n_17));
  INVXL g2775(.A (n_9), .Y (n_15));
  INVXL g2774(.A (n_12), .Y (n_14));
  AND2X1 g2753__6161(.A (n_20), .B (pulse_counter[3]), .Y (n_26));
  NAND2XL g2752__9315(.A (pulse_counter_sync[3]), .B (n_23), .Y (n_27));
  OAI211X1 g2776__9945(.A0 (pulse_counter[1]), .A1 (pulse_counter[0]),
       .B0 (enable_pulse_counting), .C0 (n_11), .Y (n_12));
  NAND4BXL g2780__2883(.AN (current_state[0]), .B (current_state[1]),
       .C (n_5), .D (n_10), .Y (n_41));
  NAND3XL g2781__2346(.A (current_state[4]), .B (n_6), .C (n_10), .Y
       (n_62));
  OAI211X1 g2778__1666(.A0 (pulse_counter_sync[1]), .A1
       (pulse_counter_sync[0]), .B0 (enable_pulse_counting_sync), .C0
       (n_16), .Y (n_9));
  DFFHQX1 \pulse_counter_sync_reg[0] (.CK (osc_clk), .D (n_2), .Q
       (pulse_counter_sync[0]));
  DFFHQX1 \pulse_counter_reg[0] (.CK (osc_clk), .D (n_4), .Q
       (pulse_counter[0]));
  NOR3BXL g2784__7410(.AN (n_10), .B (current_state[1]), .C
       (current_state[4]), .Y (n_57));
  NOR2XL g2771__6417(.A (n_8), .B (n_11), .Y (n_20));
  NOR2XL g2772__5477(.A (n_7), .B (n_16), .Y (n_23));
  AND2X1 g2787__2398(.A (n_6), .B (n_5), .Y (n_18));
  NOR2XL g2791__5107(.A (pulse_counter[0]), .B (n_3), .Y (n_4));
  NOR2XL g2792__6260(.A (pulse_counter_sync[0]), .B (n_36), .Y (n_2));
  NOR4X1 g2783__4319(.A (pulse_counter_sync[5]), .B
       (pulse_counter_sync[4]), .C (pulse_counter_sync[3]), .D
       (pulse_counter_sync[2]), .Y (n_1));
  NAND2XL g2793__8428(.A (pulse_counter[1]), .B (pulse_counter[0]), .Y
       (n_11));
  NAND2XL g2789__5526(.A (input_bit[0]), .B (input_bit[1]), .Y (n_37));
  NOR2XL g2788__6783(.A (current_state[0]), .B (current_state[1]), .Y
       (n_6));
  NOR2XL g2790__3680(.A (current_state[2]), .B (current_state[3]), .Y
       (n_10));
  NAND2XL g2794__1617(.A (pulse_counter_sync[1]), .B
       (pulse_counter_sync[0]), .Y (n_16));
  INVXL g2798(.A (pulse_counter[4]), .Y (n_0));
  INVXL g2800(.A (pulse_counter[2]), .Y (n_8));
  INVXL g2797(.A (rst), .Y (n_29));
  INVXL g2801(.A (current_state[4]), .Y (n_5));
  INVXL g2795(.A (pulse_counter_sync[4]), .Y (n_25));
  INVXL g2799(.A (pulse_counter_sync[2]), .Y (n_7));
  INVXL g2802(.A (enable_pulse_counting), .Y (n_3));
  OAI22X1 g2(.A0 (n_37), .A1 (n_68), .B0 (n_36), .B1 (n_57), .Y (n_90));
  DFFRX1 enable_pulse_counting_sync_reg(.RN (rst), .CK (osc_clk), .D
       (n_90), .Q (enable_pulse_counting_sync), .QN (n_36));
endmodule

