
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Mar 13 2025 18:23:55 -03 (Mar 13 2025 21:23:55 UTC)

// Verification Directory fv/sequential 

module sequential(A, B, C, rst, clk, Q, SE);
  input A, B, C, rst, clk, SE;
  output [1:0] Q;
  wire A, B, C, rst, clk, SE;
  wire [1:0] Q;
  wire [1:0] State_r;
  wire n_1, n_3, n_4, n_5, n_6, n_8, n_9;
  SDFFQX1 \State_r_reg[1] (.CK (clk), .D (n_9), .SI (State_r[1]), .SE
       (1'b0), .Q (State_r[1]));
  SDFFQX2 \State_r_reg[0] (.CK (clk), .D (n_6), .SI (Q[1]), .SE (1'b0),
       .Q (Q[1]));
  NOR2X1 g347__2398(.A (rst), .B (n_8), .Y (n_9));
  AOI32X1 g349__5107(.A0 (Q[1]), .A1 (State_r[1]), .A2 (n_1), .B0
       (Q[0]), .B1 (C), .Y (n_8));
  AOI21X1 g348__6260(.A0 (n_5), .A1 (n_3), .B0 (rst), .Y (n_6));
  XNOR2X1 g352__4319(.A (State_r[1]), .B (n_4), .Y (Q[0]));
  NAND3BXL g350__8428(.AN (State_r[1]), .B (n_4), .C (A), .Y (n_5));
  MXI2XL g351__5526(.A (Q[1]), .B (State_r[1]), .S0 (C), .Y (n_3));
  INVX1 g353(.A (B), .Y (n_1));
  INVX1 g356(.A (Q[1]), .Y (n_4));
endmodule

