
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Dec  5 2024 09:57:37 -03 (Dec  5 2024 12:57:37 UTC)

// Verification Directory fv/design_multiplexa_sram 

module design_multiplexa_sram(clk, reset, w_a, r_a, d_a, a_a, w_b, r_b,
     d_b, a_b, q_a, pronto_a, q_b, pronto_b);
  input clk, reset, w_a, r_a, w_b, r_b;
  input [7:0] d_a, a_a, d_b, a_b;
  output [7:0] q_a, q_b;
  output pronto_a, pronto_b;
  wire clk, reset, w_a, r_a, w_b, r_b;
  wire [7:0] d_a, a_a, d_b, a_b;
  wire [7:0] q_a, q_b;
  wire pronto_a, pronto_b;
  wire [7:0] q;
  wire [3:0] estado_atual;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_47;
  wire n_48, n_49, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67;
  SPRAM256X8 U1(.D ({n_59, n_58, n_57, n_56, n_55, n_54, n_53, n_52}),
       .ADR ({n_67, n_66, n_65, n_64, n_63, n_62, n_61, n_60}), .CLK
       (clk), .ENB (1'b0), .WEB (n_49), .OEB (1'b0), .ramvdd (1'b1),
       .ramgnd (1'b0), .Q (q), .RTEST (UNCONNECTED));
  DFFQXLHVT \q_b_reg[0] (.CK (clk), .D (n_36), .Q (q_b[0]));
  DFFQXLHVT \q_a_reg[6] (.CK (clk), .D (n_40), .Q (q_a[6]));
  DFFQXLHVT \q_a_reg[4] (.CK (clk), .D (n_42), .Q (q_a[4]));
  DFFQXLHVT \q_a_reg[0] (.CK (clk), .D (n_38), .Q (q_a[0]));
  DFFQXLHVT \q_a_reg[3] (.CK (clk), .D (n_43), .Q (q_a[3]));
  DFFQXLHVT \q_a_reg[5] (.CK (clk), .D (n_45), .Q (q_a[5]));
  DFFQXLHVT \q_a_reg[2] (.CK (clk), .D (n_44), .Q (q_a[2]));
  DFFQXLHVT \q_a_reg[1] (.CK (clk), .D (n_41), .Q (q_a[1]));
  DFFQXLHVT \q_b_reg[7] (.CK (clk), .D (n_30), .Q (q_b[7]));
  DFFQXLHVT \q_b_reg[6] (.CK (clk), .D (n_33), .Q (q_b[6]));
  DFFQXLHVT \q_b_reg[5] (.CK (clk), .D (n_31), .Q (q_b[5]));
  DFFQXLHVT \q_b_reg[4] (.CK (clk), .D (n_32), .Q (q_b[4]));
  DFFQXLHVT \q_b_reg[3] (.CK (clk), .D (n_37), .Q (q_b[3]));
  DFFQXLHVT \q_b_reg[2] (.CK (clk), .D (n_34), .Q (q_b[2]));
  DFFQXLHVT \q_b_reg[1] (.CK (clk), .D (n_35), .Q (q_b[1]));
  DFFQXLHVT \q_a_reg[7] (.CK (clk), .D (n_39), .Q (q_a[7]));
  AO22X1HVT g1707__2398(.A0 (d_a[2]), .A1 (n_22), .B0 (d_b[2]), .B1
       (n_23), .Y (n_54));
  AO22X1HVT g1708__5107(.A0 (d_a[0]), .A1 (n_22), .B0 (d_b[0]), .B1
       (n_23), .Y (n_52));
  AO22X1HVT g1709__6260(.A0 (a_a[7]), .A1 (n_22), .B0 (a_b[7]), .B1
       (n_23), .Y (n_67));
  AO22X1HVT g1710__4319(.A0 (d_a[6]), .A1 (n_22), .B0 (d_b[6]), .B1
       (n_23), .Y (n_58));
  AO22X1HVT g1711__8428(.A0 (a_a[6]), .A1 (n_22), .B0 (a_b[6]), .B1
       (n_23), .Y (n_66));
  AO22X1HVT g1712__5526(.A0 (a_a[5]), .A1 (n_22), .B0 (a_b[5]), .B1
       (n_23), .Y (n_65));
  AO22X1HVT g1713__6783(.A0 (a_a[4]), .A1 (n_22), .B0 (a_b[4]), .B1
       (n_23), .Y (n_64));
  AO22X1HVT g1714__3680(.A0 (d_a[5]), .A1 (n_22), .B0 (d_b[5]), .B1
       (n_23), .Y (n_57));
  AO22X1HVT g1715__1617(.A0 (d_a[4]), .A1 (n_22), .B0 (d_b[4]), .B1
       (n_23), .Y (n_56));
  AO22X1HVT g1716__2802(.A0 (a_a[3]), .A1 (n_22), .B0 (a_b[3]), .B1
       (n_23), .Y (n_63));
  AO22X1HVT g1717__1705(.A0 (a_a[2]), .A1 (n_22), .B0 (a_b[2]), .B1
       (n_23), .Y (n_62));
  AO22X1HVT g1718__5122(.A0 (a_a[1]), .A1 (n_22), .B0 (a_b[1]), .B1
       (n_23), .Y (n_61));
  AO22X1HVT g1719__8246(.A0 (a_a[0]), .A1 (n_22), .B0 (a_b[0]), .B1
       (n_23), .Y (n_60));
  AO22X1HVT g1720__7098(.A0 (d_a[7]), .A1 (n_22), .B0 (d_b[7]), .B1
       (n_23), .Y (n_59));
  AO22X1HVT g1721__6131(.A0 (d_a[3]), .A1 (n_22), .B0 (d_b[3]), .B1
       (n_23), .Y (n_55));
  AO22X1HVT g1722__1881(.A0 (d_a[1]), .A1 (n_22), .B0 (d_b[1]), .B1
       (n_23), .Y (n_53));
  NOR2XLHVT g1723__5115(.A (reset), .B (n_28), .Y (n_45));
  NOR2XLHVT g1724__7482(.A (reset), .B (n_29), .Y (n_44));
  NOR2XLHVT g1725__4733(.A (reset), .B (n_24), .Y (n_43));
  NOR2XLHVT g1726__6161(.A (reset), .B (n_27), .Y (n_42));
  NOR2XLHVT g1727__9315(.A (reset), .B (n_20), .Y (n_41));
  NOR2XLHVT g1728__9945(.A (reset), .B (n_25), .Y (n_40));
  NOR2XLHVT g1729__2883(.A (reset), .B (n_26), .Y (n_39));
  NOR2XLHVT g1730__2346(.A (reset), .B (n_21), .Y (n_38));
  NOR3BXLHVT g1731__1666(.AN (q[3]), .B (reset), .C (n_19), .Y (n_37));
  NOR3BXLHVT g1732__7410(.AN (q[0]), .B (reset), .C (n_19), .Y (n_36));
  NOR3BXLHVT g1733__6417(.AN (q[1]), .B (reset), .C (n_19), .Y (n_35));
  NOR3BXLHVT g1734__5477(.AN (q[2]), .B (reset), .C (n_19), .Y (n_34));
  NOR3BXLHVT g1735__2398(.AN (q[6]), .B (reset), .C (n_19), .Y (n_33));
  NOR3BXLHVT g1736__5107(.AN (q[4]), .B (reset), .C (n_19), .Y (n_32));
  NOR3BXLHVT g1737__6260(.AN (q[5]), .B (reset), .C (n_19), .Y (n_31));
  NOR3BXLHVT g1738__4319(.AN (q[7]), .B (reset), .C (n_19), .Y (n_30));
  NAND2XLHVT g1739__8428(.A (n_17), .B (q[2]), .Y (n_29));
  NAND2XLHVT g1740__5526(.A (n_17), .B (q[5]), .Y (n_28));
  NAND2XLHVT g1741__6783(.A (n_17), .B (q[4]), .Y (n_27));
  NAND2XLHVT g1742__3680(.A (n_17), .B (q[7]), .Y (n_26));
  NAND2XLHVT g1743__1617(.A (n_17), .B (q[6]), .Y (n_25));
  NAND2XLHVT g1744__2802(.A (n_17), .B (q[3]), .Y (n_24));
  NOR3XLHVT g1745__1705(.A (reset), .B (n_13), .C (n_16), .Y
       (pronto_a));
  NAND2XLHVT g1746__5122(.A (n_17), .B (q[0]), .Y (n_21));
  NAND2XLHVT g1747__8246(.A (n_17), .B (q[1]), .Y (n_20));
  NOR3XLHVT g1748__7098(.A (reset), .B (n_13), .C (n_15), .Y
       (pronto_b));
  NAND2XLHVT g1749__6131(.A (n_47), .B (n_19), .Y (n_23));
  OAI21XLHVT g1750__1881(.A0 (estado_atual[1]), .A1 (n_14), .B0 (n_18),
       .Y (n_22));
  OR2X1HVT g1751__5115(.A (estado_atual[2]), .B (n_15), .Y (n_47));
  OR2X1HVT g1752__7482(.A (n_13), .B (n_48), .Y (n_19));
  INVXLHVT g1753(.A (n_17), .Y (n_18));
  OR2X1HVT g1754__4733(.A (reset), .B (n_14), .Y (n_49));
  NOR2XLHVT g1755__6161(.A (estado_atual[2]), .B (n_16), .Y (n_17));
  OR2X1HVT g1756__9315(.A (estado_atual[1]), .B (estado_atual[0]), .Y
       (n_48));
  NAND2BXLHVT g1757__9945(.AN (estado_atual[0]), .B (estado_atual[1]),
       .Y (n_16));
  NAND2XLHVT g1758__2883(.A (estado_atual[1]), .B (estado_atual[0]), .Y
       (n_15));
  NAND2XLHVT g1759__2346(.A (estado_atual[0]), .B (n_13), .Y (n_14));
  INVX1HVT g1760(.A (estado_atual[2]), .Y (n_13));
  DFFHQX1HVT \estado_atual_reg[0] (.CK (clk), .D (n_12), .Q
       (estado_atual[0]));
  DFFHQX1HVT \estado_atual_reg[1] (.CK (clk), .D (n_11), .Q
       (estado_atual[1]));
  NOR2XLHVT g1426__1666(.A (reset), .B (n_10), .Y (n_12));
  DFFHQX1HVT \estado_atual_reg[2] (.CK (clk), .D (n_9), .Q
       (estado_atual[2]));
  AOI21XLHVT g1428__7410(.A0 (n_7), .A1 (n_4), .B0 (reset), .Y (n_11));
  MX2X1HVT g1429__6417(.A (n_8), .B (n_47), .S0 (n_48), .Y (n_10));
  AOI21XLHVT g1430__5477(.A0 (n_6), .A1 (n_4), .B0 (reset), .Y (n_9));
  AOI2BB1XLHVT g1431__2398(.A0N (r_a), .A1N (n_5), .B0
       (estado_atual[2]), .Y (n_8));
  OAI21XLHVT g1432__5107(.A0 (r_a), .A1 (n_3), .B0 (n_1), .Y (n_7));
  OR4X1HVT g1433__6260(.A (w_a), .B (r_a), .C (n_0), .D (n_48), .Y
       (n_6));
  NOR2XLHVT g1434__4319(.A (w_a), .B (n_2), .Y (n_5));
  NOR2BX1HVT g1435__8428(.AN (n_2), .B (w_a), .Y (n_3));
  XNOR2X1HVT g1436__5526(.A (estado_atual[2]), .B (n_48), .Y (n_4));
  AND2X1HVT g1437__6783(.A (n_0), .B (w_b), .Y (n_2));
  INVXLHVT g1438(.A (n_48), .Y (n_1));
  INVXLHVT g1439(.A (r_b), .Y (n_0));
endmodule

