
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Dec 20 2024 14:47:40 -03 (Dec 20 2024 17:47:40 UTC)

// Verification Directory fv/CLOCK_DIVIDER 
`timescale 1ns/1ps
module CLOCK_DIVIDER(INPUT_CLK, RST, OUTPUT_CLK);
  input INPUT_CLK, RST;
  output OUTPUT_CLK;
  wire INPUT_CLK, RST;
  wire OUTPUT_CLK;
  wire [15:0] clk_cycle_counting;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  DFFHQX1 \clk_cycle_counting_reg[6] (.CK (INPUT_CLK), .D (n_21), .Q
       (clk_cycle_counting[6]));
  DFFHQX1 \clk_cycle_counting_reg[5] (.CK (INPUT_CLK), .D (n_20), .Q
       (clk_cycle_counting[5]));
  NOR2XL g632__2398(.A (n_19), .B (n_15), .Y (n_21));
  NOR2XL g634__5107(.A (n_19), .B (n_18), .Y (n_20));
  DFFHQX1 OUTPUT_CLK_reg(.CK (INPUT_CLK), .D (n_17), .Q (OUTPUT_CLK));
  DFFHQX1 \clk_cycle_counting_reg[4] (.CK (INPUT_CLK), .D (n_16), .Q
       (clk_cycle_counting[4]));
  DFFHQX1 \clk_cycle_counting_reg[3] (.CK (INPUT_CLK), .D (n_11), .Q
       (clk_cycle_counting[3]));
  SDFFQX1 \clk_cycle_counting_reg[0] (.CK (INPUT_CLK), .D (n_0), .SI
       (RST), .SE (n_19), .Q (clk_cycle_counting[0]));
  DFFHQX1 \clk_cycle_counting_reg[2] (.CK (INPUT_CLK), .D (n_13), .Q
       (clk_cycle_counting[2]));
  DFFHQX1 \clk_cycle_counting_reg[1] (.CK (INPUT_CLK), .D (n_12), .Q
       (clk_cycle_counting[1]));
  XNOR2X1 g636__6260(.A (clk_cycle_counting[5]), .B (n_14), .Y (n_18));
  AND2X1 g642__4319(.A (n_10), .B (RST), .Y (n_17));
  NOR2XL g637__8428(.A (n_9), .B (n_19), .Y (n_16));
  AOI21XL g633__5526(.A0 (clk_cycle_counting[5]), .A1 (n_14), .B0
       (clk_cycle_counting[6]), .Y (n_15));
  NOR2XL g647__6783(.A (n_4), .B (n_19), .Y (n_13));
  NOR2XL g648__3680(.A (n_2), .B (n_19), .Y (n_12));
  NOR2XL g645__1617(.A (n_6), .B (n_19), .Y (n_11));
  XNOR2X1 g649__2802(.A (n_8), .B (OUTPUT_CLK), .Y (n_10));
  XNOR2X1 g643__1705(.A (clk_cycle_counting[4]), .B (n_7), .Y (n_9));
  NAND2XL g650__5122(.A (RST), .B (n_8), .Y (n_19));
  AND2X1 g646__8246(.A (n_7), .B (clk_cycle_counting[4]), .Y (n_14));
  XNOR2X1 g652__7098(.A (clk_cycle_counting[3]), .B (n_5), .Y (n_6));
  NAND4BXL g651__6131(.AN (n_1), .B (clk_cycle_counting[4]), .C
       (clk_cycle_counting[5]), .D (clk_cycle_counting[2]), .Y (n_8));
  AND2X1 g653__1881(.A (n_5), .B (clk_cycle_counting[3]), .Y (n_7));
  XNOR2X1 g654__5115(.A (clk_cycle_counting[2]), .B (n_3), .Y (n_4));
  AND2X1 g656__7482(.A (n_3), .B (clk_cycle_counting[2]), .Y (n_5));
  XNOR2X1 g657__4733(.A (clk_cycle_counting[0]), .B
       (clk_cycle_counting[1]), .Y (n_2));
  OAI211X1 g655__6161(.A0 (clk_cycle_counting[1]), .A1
       (clk_cycle_counting[0]), .B0 (clk_cycle_counting[6]), .C0
       (clk_cycle_counting[3]), .Y (n_1));
  AND2X1 g658__9315(.A (clk_cycle_counting[0]), .B
       (clk_cycle_counting[1]), .Y (n_3));
  INVXL g659(.A (clk_cycle_counting[0]), .Y (n_0));
endmodule

