
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point a_i[31] a_i[31] -type PI PI
add mapped point a_i[30] a_i[30] -type PI PI
add mapped point a_i[29] a_i[29] -type PI PI
add mapped point a_i[28] a_i[28] -type PI PI
add mapped point a_i[27] a_i[27] -type PI PI
add mapped point a_i[26] a_i[26] -type PI PI
add mapped point a_i[25] a_i[25] -type PI PI
add mapped point a_i[24] a_i[24] -type PI PI
add mapped point a_i[23] a_i[23] -type PI PI
add mapped point a_i[22] a_i[22] -type PI PI
add mapped point a_i[21] a_i[21] -type PI PI
add mapped point a_i[20] a_i[20] -type PI PI
add mapped point a_i[19] a_i[19] -type PI PI
add mapped point a_i[18] a_i[18] -type PI PI
add mapped point a_i[17] a_i[17] -type PI PI
add mapped point a_i[16] a_i[16] -type PI PI
add mapped point a_i[15] a_i[15] -type PI PI
add mapped point a_i[14] a_i[14] -type PI PI
add mapped point a_i[13] a_i[13] -type PI PI
add mapped point a_i[12] a_i[12] -type PI PI
add mapped point a_i[11] a_i[11] -type PI PI
add mapped point a_i[10] a_i[10] -type PI PI
add mapped point a_i[9] a_i[9] -type PI PI
add mapped point a_i[8] a_i[8] -type PI PI
add mapped point a_i[7] a_i[7] -type PI PI
add mapped point a_i[6] a_i[6] -type PI PI
add mapped point a_i[5] a_i[5] -type PI PI
add mapped point a_i[4] a_i[4] -type PI PI
add mapped point a_i[3] a_i[3] -type PI PI
add mapped point a_i[2] a_i[2] -type PI PI
add mapped point a_i[1] a_i[1] -type PI PI
add mapped point a_i[0] a_i[0] -type PI PI
add mapped point b_i[31] b_i[31] -type PI PI
add mapped point b_i[30] b_i[30] -type PI PI
add mapped point b_i[29] b_i[29] -type PI PI
add mapped point b_i[28] b_i[28] -type PI PI
add mapped point b_i[27] b_i[27] -type PI PI
add mapped point b_i[26] b_i[26] -type PI PI
add mapped point b_i[25] b_i[25] -type PI PI
add mapped point b_i[24] b_i[24] -type PI PI
add mapped point b_i[23] b_i[23] -type PI PI
add mapped point b_i[22] b_i[22] -type PI PI
add mapped point b_i[21] b_i[21] -type PI PI
add mapped point b_i[20] b_i[20] -type PI PI
add mapped point b_i[19] b_i[19] -type PI PI
add mapped point b_i[18] b_i[18] -type PI PI
add mapped point b_i[17] b_i[17] -type PI PI
add mapped point b_i[16] b_i[16] -type PI PI
add mapped point b_i[15] b_i[15] -type PI PI
add mapped point b_i[14] b_i[14] -type PI PI
add mapped point b_i[13] b_i[13] -type PI PI
add mapped point b_i[12] b_i[12] -type PI PI
add mapped point b_i[11] b_i[11] -type PI PI
add mapped point b_i[10] b_i[10] -type PI PI
add mapped point b_i[9] b_i[9] -type PI PI
add mapped point b_i[8] b_i[8] -type PI PI
add mapped point b_i[7] b_i[7] -type PI PI
add mapped point b_i[6] b_i[6] -type PI PI
add mapped point b_i[5] b_i[5] -type PI PI
add mapped point b_i[4] b_i[4] -type PI PI
add mapped point b_i[3] b_i[3] -type PI PI
add mapped point b_i[2] b_i[2] -type PI PI
add mapped point b_i[1] b_i[1] -type PI PI
add mapped point b_i[0] b_i[0] -type PI PI
add mapped point start_i start_i -type PI PI

//output ports
add mapped point done_o done_o -type PO PO
add mapped point nan_o nan_o -type PO PO
add mapped point inifinit_o inifinit_o -type PO PO
add mapped point overflow_o overflow_o -type PO PO
add mapped point underflow_o underflow_o -type PO PO
add mapped point product_o[31] product_o[31] -type PO PO
add mapped point product_o[30] product_o[30] -type PO PO
add mapped point product_o[29] product_o[29] -type PO PO
add mapped point product_o[28] product_o[28] -type PO PO
add mapped point product_o[27] product_o[27] -type PO PO
add mapped point product_o[26] product_o[26] -type PO PO
add mapped point product_o[25] product_o[25] -type PO PO
add mapped point product_o[24] product_o[24] -type PO PO
add mapped point product_o[23] product_o[23] -type PO PO
add mapped point product_o[22] product_o[22] -type PO PO
add mapped point product_o[21] product_o[21] -type PO PO
add mapped point product_o[20] product_o[20] -type PO PO
add mapped point product_o[19] product_o[19] -type PO PO
add mapped point product_o[18] product_o[18] -type PO PO
add mapped point product_o[17] product_o[17] -type PO PO
add mapped point product_o[16] product_o[16] -type PO PO
add mapped point product_o[15] product_o[15] -type PO PO
add mapped point product_o[14] product_o[14] -type PO PO
add mapped point product_o[13] product_o[13] -type PO PO
add mapped point product_o[12] product_o[12] -type PO PO
add mapped point product_o[11] product_o[11] -type PO PO
add mapped point product_o[10] product_o[10] -type PO PO
add mapped point product_o[9] product_o[9] -type PO PO
add mapped point product_o[8] product_o[8] -type PO PO
add mapped point product_o[7] product_o[7] -type PO PO
add mapped point product_o[6] product_o[6] -type PO PO
add mapped point product_o[5] product_o[5] -type PO PO
add mapped point product_o[4] product_o[4] -type PO PO
add mapped point product_o[3] product_o[3] -type PO PO
add mapped point product_o[2] product_o[2] -type PO PO
add mapped point product_o[1] product_o[1] -type PO PO
add mapped point product_o[0] product_o[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point current_state[0]/q current_state_reg[0]/Q  -type DFF DFF
add mapped point current_state[2]/q current_state_reg[2]/Q  -type DFF DFF
add mapped point current_state[2]/q current_state_reg[2]/QN  -type DFF DFF
add mapped point done_o/q done_o_reg/Q  -type DFF DFF
add mapped point exponent_temp[0]/q exponent_temp_reg[0]/Q  -type DLAT DLAT
add mapped point exponent_temp[0]/q exponent_temp_reg[0]/QN  -type DLAT DLAT
add mapped point exponent_temp[1]/q exponent_temp_reg[1]/Q  -type DLAT DLAT
add mapped point exponent_temp[1]/q exponent_temp_reg[1]/QN  -type DLAT DLAT
add mapped point exponent_temp[2]/q exponent_temp_reg[2]/Q  -type DLAT DLAT
add mapped point exponent_temp[2]/q exponent_temp_reg[2]/QN  -type DLAT DLAT
add mapped point exponent_temp[3]/q exponent_temp_reg[3]/Q  -type DLAT DLAT
add mapped point exponent_temp[3]/q exponent_temp_reg[3]/QN  -type DLAT DLAT
add mapped point exponent_temp[4]/q exponent_temp_reg[4]/Q  -type DLAT DLAT
add mapped point exponent_temp[4]/q exponent_temp_reg[4]/QN  -type DLAT DLAT
add mapped point exponent_temp[5]/q exponent_temp_reg[5]/Q  -type DLAT DLAT
add mapped point exponent_temp[5]/q exponent_temp_reg[5]/QN  -type DLAT DLAT
add mapped point exponent_temp[6]/q exponent_temp_reg[6]/Q  -type DLAT DLAT
add mapped point exponent_temp[6]/q exponent_temp_reg[6]/QN  -type DLAT DLAT
add mapped point exponent_temp[7]/q exponent_temp_reg[7]/Q  -type DLAT DLAT
add mapped point exponent_temp[7]/q exponent_temp_reg[7]/QN  -type DLAT DLAT
add mapped point exponent_temp[8]/q exponent_temp_reg[8]/Q  -type DLAT DLAT
add mapped point exponent_temp[8]/q exponent_temp_reg[8]/QN  -type DLAT DLAT
add mapped point exponent_temp[9]/q exponent_temp_reg[9]/Q  -type DLAT DLAT
add mapped point exponent_temp[9]/q exponent_temp_reg[9]/QN  -type DLAT DLAT
add mapped point inifinit_o/q inifinit_o_reg/Q  -type DFF DFF
add mapped point mantissa_temp[23]/q mantissa_temp_reg[23]/Q  -type DLAT DLAT
add mapped point mantissa_temp[23]/q mantissa_temp_reg[23]/QN  -type DLAT DLAT
add mapped point mantissa_temp[24]/q mantissa_temp_reg[24]/Q  -type DLAT DLAT
add mapped point mantissa_temp[24]/q mantissa_temp_reg[24]/QN  -type DLAT DLAT
add mapped point mantissa_temp[25]/q mantissa_temp_reg[25]/Q  -type DLAT DLAT
add mapped point mantissa_temp[25]/q mantissa_temp_reg[25]/QN  -type DLAT DLAT
add mapped point mantissa_temp[26]/q mantissa_temp_reg[26]/Q  -type DLAT DLAT
add mapped point mantissa_temp[26]/q mantissa_temp_reg[26]/QN  -type DLAT DLAT
add mapped point mantissa_temp[27]/q mantissa_temp_reg[27]/Q  -type DLAT DLAT
add mapped point mantissa_temp[27]/q mantissa_temp_reg[27]/QN  -type DLAT DLAT
add mapped point mantissa_temp[28]/q mantissa_temp_reg[28]/Q  -type DLAT DLAT
add mapped point mantissa_temp[28]/q mantissa_temp_reg[28]/QN  -type DLAT DLAT
add mapped point mantissa_temp[29]/q mantissa_temp_reg[29]/Q  -type DLAT DLAT
add mapped point mantissa_temp[29]/q mantissa_temp_reg[29]/QN  -type DLAT DLAT
add mapped point mantissa_temp[30]/q mantissa_temp_reg[30]/Q  -type DLAT DLAT
add mapped point mantissa_temp[30]/q mantissa_temp_reg[30]/QN  -type DLAT DLAT
add mapped point mantissa_temp[31]/q mantissa_temp_reg[31]/Q  -type DLAT DLAT
add mapped point mantissa_temp[31]/q mantissa_temp_reg[31]/QN  -type DLAT DLAT
add mapped point mantissa_temp[32]/q mantissa_temp_reg[32]/Q  -type DLAT DLAT
add mapped point mantissa_temp[32]/q mantissa_temp_reg[32]/QN  -type DLAT DLAT
add mapped point mantissa_temp[33]/q mantissa_temp_reg[33]/Q  -type DLAT DLAT
add mapped point mantissa_temp[33]/q mantissa_temp_reg[33]/QN  -type DLAT DLAT
add mapped point mantissa_temp[34]/q mantissa_temp_reg[34]/Q  -type DLAT DLAT
add mapped point mantissa_temp[34]/q mantissa_temp_reg[34]/QN  -type DLAT DLAT
add mapped point mantissa_temp[35]/q mantissa_temp_reg[35]/Q  -type DLAT DLAT
add mapped point mantissa_temp[35]/q mantissa_temp_reg[35]/QN  -type DLAT DLAT
add mapped point mantissa_temp[36]/q mantissa_temp_reg[36]/Q  -type DLAT DLAT
add mapped point mantissa_temp[36]/q mantissa_temp_reg[36]/QN  -type DLAT DLAT
add mapped point mantissa_temp[37]/q mantissa_temp_reg[37]/Q  -type DLAT DLAT
add mapped point mantissa_temp[37]/q mantissa_temp_reg[37]/QN  -type DLAT DLAT
add mapped point mantissa_temp[38]/q mantissa_temp_reg[38]/Q  -type DLAT DLAT
add mapped point mantissa_temp[38]/q mantissa_temp_reg[38]/QN  -type DLAT DLAT
add mapped point mantissa_temp[39]/q mantissa_temp_reg[39]/Q  -type DLAT DLAT
add mapped point mantissa_temp[39]/q mantissa_temp_reg[39]/QN  -type DLAT DLAT
add mapped point mantissa_temp[40]/q mantissa_temp_reg[40]/Q  -type DLAT DLAT
add mapped point mantissa_temp[40]/q mantissa_temp_reg[40]/QN  -type DLAT DLAT
add mapped point mantissa_temp[41]/q mantissa_temp_reg[41]/Q  -type DLAT DLAT
add mapped point mantissa_temp[41]/q mantissa_temp_reg[41]/QN  -type DLAT DLAT
add mapped point mantissa_temp[42]/q mantissa_temp_reg[42]/Q  -type DLAT DLAT
add mapped point mantissa_temp[42]/q mantissa_temp_reg[42]/QN  -type DLAT DLAT
add mapped point mantissa_temp[43]/q mantissa_temp_reg[43]/Q  -type DLAT DLAT
add mapped point mantissa_temp[43]/q mantissa_temp_reg[43]/QN  -type DLAT DLAT
add mapped point mantissa_temp[44]/q mantissa_temp_reg[44]/Q  -type DLAT DLAT
add mapped point mantissa_temp[44]/q mantissa_temp_reg[44]/QN  -type DLAT DLAT
add mapped point mantissa_temp[45]/q mantissa_temp_reg[45]/Q  -type DLAT DLAT
add mapped point mantissa_temp[45]/q mantissa_temp_reg[45]/QN  -type DLAT DLAT
add mapped point nan_o/q nan_o_reg/Q  -type DFF DFF
add mapped point overflow_o/q overflow_o_reg/Q  -type DFF DFF
add mapped point product_o[0]/q product_o_reg[0]/Q  -type DFF DFF
add mapped point product_o[1]/q product_o_reg[1]/Q  -type DFF DFF
add mapped point product_o[2]/q product_o_reg[2]/Q  -type DFF DFF
add mapped point product_o[3]/q product_o_reg[3]/Q  -type DFF DFF
add mapped point product_o[4]/q product_o_reg[4]/Q  -type DFF DFF
add mapped point product_o[5]/q product_o_reg[5]/Q  -type DFF DFF
add mapped point product_o[6]/q product_o_reg[6]/Q  -type DFF DFF
add mapped point product_o[7]/q product_o_reg[7]/Q  -type DFF DFF
add mapped point product_o[8]/q product_o_reg[8]/Q  -type DFF DFF
add mapped point product_o[9]/q product_o_reg[9]/Q  -type DFF DFF
add mapped point product_o[10]/q product_o_reg[10]/Q  -type DFF DFF
add mapped point product_o[11]/q product_o_reg[11]/Q  -type DFF DFF
add mapped point product_o[12]/q product_o_reg[12]/Q  -type DFF DFF
add mapped point product_o[13]/q product_o_reg[13]/Q  -type DFF DFF
add mapped point product_o[14]/q product_o_reg[14]/Q  -type DFF DFF
add mapped point product_o[15]/q product_o_reg[15]/Q  -type DFF DFF
add mapped point product_o[16]/q product_o_reg[16]/Q  -type DFF DFF
add mapped point product_o[17]/q product_o_reg[17]/Q  -type DFF DFF
add mapped point product_o[18]/q product_o_reg[18]/Q  -type DFF DFF
add mapped point product_o[19]/q product_o_reg[19]/Q  -type DFF DFF
add mapped point product_o[20]/q product_o_reg[20]/Q  -type DFF DFF
add mapped point product_o[21]/q product_o_reg[21]/Q  -type DFF DFF
add mapped point product_o[22]/q product_o_reg[22]/Q  -type DFF DFF
add mapped point product_o[23]/q product_o_reg[23]/Q  -type DFF DFF
add mapped point product_o[24]/q product_o_reg[24]/Q  -type DFF DFF
add mapped point product_o[25]/q product_o_reg[25]/Q  -type DFF DFF
add mapped point product_o[26]/q product_o_reg[26]/Q  -type DFF DFF
add mapped point product_o[27]/q product_o_reg[27]/Q  -type DFF DFF
add mapped point product_o[28]/q product_o_reg[28]/Q  -type DFF DFF
add mapped point product_o[29]/q product_o_reg[29]/Q  -type DFF DFF
add mapped point product_o[30]/q product_o_reg[30]/Q  -type DFF DFF
add mapped point product_o[31]/q product_o_reg[31]/Q  -type DFF DFF
add mapped point signal_a/q signal_a_reg/Q  -type DLAT DLAT
add mapped point signal_a/q signal_a_reg/QN  -type DLAT DLAT
add mapped point signal_b/q signal_b_reg/Q  -type DLAT DLAT
add mapped point signal_b/q signal_b_reg/QN  -type DLAT DLAT
add mapped point underflow_o/q underflow_o_reg/Q  -type DFF DFF
add mapped point current_state[1]/q current_state_reg[1]/Q  -type DFF DFF
add mapped point current_state[1]/q current_state_reg[1]/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
