1731432301 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/gates/andgate.sv
1730318984 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/or/orgate.sv
1731437199 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/gates/norgate.sv
1730319173 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/or/orgate_tb.sv
1731443620 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/comparator_generic_tb.sv
1730387224 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/xor/notgate.sv
1731439089 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/comparator.sv
1730388398 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/xor/xorgate.sv
1731432301 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/gates/orgate.sv
1731432301 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/xorgate.sv
1731438739 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/comparator_tb.sv
1730745879 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/xor/xorgate_tb.sv
1730387214 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/xor/andgate.sv
1731441559 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/comparator_device_tb.sv
1731442249 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/comparator_generic.sv
1731432301 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/xorgate_tb.sv
1730387205 /home/cinovador/Documents/course_files/verilog_tests/arch_fpga_asic/first_xcelium/xor/orgate.sv
1731441501 /home/cinovador/Documents/course_files/digital_logic/verilog_files/comparator/comparator_device.sv
