# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.10-p002_1 on Wed Mar 26 12:36:28 -03 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design multiplier32FP

create_clock -name "clk" -period 50.0 -waveform {0.0 25.0} [get_ports clk]
set_load -pin_load 0.045 [get_ports done_o]
set_load -pin_load 0.045 [get_ports nan_o]
set_load -pin_load 0.045 [get_ports inifinit_o]
set_load -pin_load 0.045 [get_ports overflow_o]
set_load -pin_load 0.045 [get_ports underflow_o]
set_load -pin_load 0.045 [get_ports {product_o[31]}]
set_load -pin_load 0.045 [get_ports {product_o[30]}]
set_load -pin_load 0.045 [get_ports {product_o[29]}]
set_load -pin_load 0.045 [get_ports {product_o[28]}]
set_load -pin_load 0.045 [get_ports {product_o[27]}]
set_load -pin_load 0.045 [get_ports {product_o[26]}]
set_load -pin_load 0.045 [get_ports {product_o[25]}]
set_load -pin_load 0.045 [get_ports {product_o[24]}]
set_load -pin_load 0.045 [get_ports {product_o[23]}]
set_load -pin_load 0.045 [get_ports {product_o[22]}]
set_load -pin_load 0.045 [get_ports {product_o[21]}]
set_load -pin_load 0.045 [get_ports {product_o[20]}]
set_load -pin_load 0.045 [get_ports {product_o[19]}]
set_load -pin_load 0.045 [get_ports {product_o[18]}]
set_load -pin_load 0.045 [get_ports {product_o[17]}]
set_load -pin_load 0.045 [get_ports {product_o[16]}]
set_load -pin_load 0.045 [get_ports {product_o[15]}]
set_load -pin_load 0.045 [get_ports {product_o[14]}]
set_load -pin_load 0.045 [get_ports {product_o[13]}]
set_load -pin_load 0.045 [get_ports {product_o[12]}]
set_load -pin_load 0.045 [get_ports {product_o[11]}]
set_load -pin_load 0.045 [get_ports {product_o[10]}]
set_load -pin_load 0.045 [get_ports {product_o[9]}]
set_load -pin_load 0.045 [get_ports {product_o[8]}]
set_load -pin_load 0.045 [get_ports {product_o[7]}]
set_load -pin_load 0.045 [get_ports {product_o[6]}]
set_load -pin_load 0.045 [get_ports {product_o[5]}]
set_load -pin_load 0.045 [get_ports {product_o[4]}]
set_load -pin_load 0.045 [get_ports {product_o[3]}]
set_load -pin_load 0.045 [get_ports {product_o[2]}]
set_load -pin_load 0.045 [get_ports {product_o[1]}]
set_load -pin_load 0.045 [get_ports {product_o[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {a_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports {b_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.28 [get_ports start_i]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports done_o]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports nan_o]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports inifinit_o]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports overflow_o]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports underflow_o]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.35 [get_ports {product_o[0]}]
set_input_transition -rise -min 0.146 [get_ports rst_n]
set_input_transition -rise -max 0.264 [get_ports rst_n]
set_input_transition -fall -min 0.164 [get_ports rst_n]
set_input_transition -fall -max 0.252 [get_ports rst_n]
set_input_transition -rise -min 0.146 [get_ports {a_i[31]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[31]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[31]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[31]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[30]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[30]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[30]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[30]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[29]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[29]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[29]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[29]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[28]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[28]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[28]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[28]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[27]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[27]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[27]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[27]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[26]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[26]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[26]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[26]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[25]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[25]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[25]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[25]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[24]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[24]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[24]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[24]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[23]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[23]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[23]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[23]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[22]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[22]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[22]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[22]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[21]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[21]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[21]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[21]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[20]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[20]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[20]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[20]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[19]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[19]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[19]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[19]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[18]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[18]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[18]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[18]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[17]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[17]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[17]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[17]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[16]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[16]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[16]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[16]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[15]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[15]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[15]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[15]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[14]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[14]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[14]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[14]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[13]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[13]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[13]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[13]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[12]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[12]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[12]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[12]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[11]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[11]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[11]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[11]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[10]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[10]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[10]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[10]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[9]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[9]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[9]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[9]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[8]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[8]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[8]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[8]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[7]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[7]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[7]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[7]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[6]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[6]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[6]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[6]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[5]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[5]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[5]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[5]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[4]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[4]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[4]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[4]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[3]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[3]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[3]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[3]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[2]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[2]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[2]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[2]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[1]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[1]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[1]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[1]}]
set_input_transition -rise -min 0.146 [get_ports {a_i[0]}]
set_input_transition -rise -max 0.264 [get_ports {a_i[0]}]
set_input_transition -fall -min 0.164 [get_ports {a_i[0]}]
set_input_transition -fall -max 0.252 [get_ports {a_i[0]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[31]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[31]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[31]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[31]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[30]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[30]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[30]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[30]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[29]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[29]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[29]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[29]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[28]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[28]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[28]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[28]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[27]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[27]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[27]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[27]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[26]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[26]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[26]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[26]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[25]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[25]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[25]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[25]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[24]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[24]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[24]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[24]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[23]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[23]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[23]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[23]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[22]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[22]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[22]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[22]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[21]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[21]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[21]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[21]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[20]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[20]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[20]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[20]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[19]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[19]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[19]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[19]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[18]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[18]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[18]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[18]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[17]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[17]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[17]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[17]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[16]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[16]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[16]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[16]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[15]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[15]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[15]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[15]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[14]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[14]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[14]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[14]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[13]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[13]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[13]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[13]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[12]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[12]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[12]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[12]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[11]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[11]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[11]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[11]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[10]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[10]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[10]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[10]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[9]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[9]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[9]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[9]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[8]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[8]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[8]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[8]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[7]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[7]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[7]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[7]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[6]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[6]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[6]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[6]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[5]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[5]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[5]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[5]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[4]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[4]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[4]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[4]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[3]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[3]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[3]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[3]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[2]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[2]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[2]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[2]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[1]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[1]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[1]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[1]}]
set_input_transition -rise -min 0.146 [get_ports {b_i[0]}]
set_input_transition -rise -max 0.264 [get_ports {b_i[0]}]
set_input_transition -fall -min 0.164 [get_ports {b_i[0]}]
set_input_transition -fall -max 0.252 [get_ports {b_i[0]}]
set_input_transition -rise -min 0.146 [get_ports start_i]
set_input_transition -rise -max 0.264 [get_ports start_i]
set_input_transition -fall -min 0.164 [get_ports start_i]
set_input_transition -fall -max 0.252 [get_ports start_i]
set_ideal_net [get_nets clk]
set_ideal_net [get_nets rst_n]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFHQX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFHQX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFHQX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFHQX8]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFNSRX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFNSRX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFNSRX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFNSRXL]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFQX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFQX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFQX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFQXL]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRHQX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRHQX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRHQX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRHQX8]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFRXL]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSHQX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSHQX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSHQX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSHQX8]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRHQX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRHQX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRHQX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRHQX8]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSRXL]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFSXL]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFTRX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFTRX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFTRX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFTRXL]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFX1]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFX2]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFX4]
set_dont_use false [get_lib_cells slow_vdd1v0/SDFFXL]
set_dont_use false [get_lib_cells slow_vdd1v0/TLATSRX1]
set_dont_use false [get_lib_cells slow_vdd1v0/TLATSRX2]
set_dont_use false [get_lib_cells slow_vdd1v0/TLATSRX4]
set_dont_use false [get_lib_cells slow_vdd1v0/TLATSRXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFHQX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFHQX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFHQX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFHQX8]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFNSRX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFNSRX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFNSRX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFNSRXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFQX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFQX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFQX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFQXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRHQX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRHQX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRHQX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRHQX8]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFRXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSHQX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSHQX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSHQX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSHQX8]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRHQX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRHQX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRHQX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRHQX8]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSRXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFSXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFTRX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFTRX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFTRX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFTRXL]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFX1]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFX2]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFX4]
set_dont_use false [get_lib_cells fast_vdd1v2/SDFFXL]
set_dont_use false [get_lib_cells fast_vdd1v2/TLATSRX1]
set_dont_use false [get_lib_cells fast_vdd1v2/TLATSRX2]
set_dont_use false [get_lib_cells fast_vdd1v2/TLATSRX4]
set_dont_use false [get_lib_cells fast_vdd1v2/TLATSRXL]
set_clock_latency  0.105 [get_clocks clk]
set_clock_uncertainty -setup 0.044 [get_clocks clk]
set_clock_uncertainty -hold 0.044 [get_clocks clk]
