
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Feb 24 2025 18:02:58 -03 (Feb 24 2025 21:02:58 UTC)

// Verification Directory fv/sequential 

module sequential(A, B, C, rst, clk, Q, SE, scan_in, scan_out);
  input A, B, C, rst, clk, SE, scan_in;
  output [1:0] Q;
  output scan_out;
  wire A, B, C, rst, clk, SE, scan_in;
  wire [1:0] Q;
  wire scan_out;
  wire n_1, n_3, n_4, n_5, n_6, n_8, n_9;
  SDFFQX1 \State_r_reg[1] (.CK (clk), .D (n_9), .SI (Q[1]), .SE (SE),
       .Q (scan_out));
  SDFFQX2 \State_r_reg[0] (.CK (clk), .D (n_6), .SI (scan_in), .SE
       (SE), .Q (Q[1]));
  NOR2X1 g301__2398(.A (rst), .B (n_8), .Y (n_9));
  AOI32X1 g303__5107(.A0 (Q[1]), .A1 (scan_out), .A2 (n_1), .B0 (Q[0]),
       .B1 (C), .Y (n_8));
  AOI21X1 g302__6260(.A0 (n_5), .A1 (n_3), .B0 (rst), .Y (n_6));
  XNOR2X1 g306__4319(.A (scan_out), .B (n_4), .Y (Q[0]));
  NAND3BXL g304__8428(.AN (scan_out), .B (n_4), .C (A), .Y (n_5));
  MXI2XL g305__5526(.A (Q[1]), .B (scan_out), .S0 (C), .Y (n_3));
  INVX1 g307(.A (B), .Y (n_1));
  INVX1 g310(.A (Q[1]), .Y (n_4));
endmodule

