
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Dec  4 2024 11:50:30 -03 (Dec  4 2024 14:50:30 UTC)

// Verification Directory fv/sequential 

module sequential(A, B, C, rst, clk, Q);
  input A, B, C, rst, clk;
  output [1:0] Q;
  wire A, B, C, rst, clk;
  wire [1:0] Q;
  wire [1:0] State_r;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9;
  DFFHQX1 \State_r_reg[1] (.CK (clk), .D (n_9), .Q (State_r[1]));
  NOR2X1 g301__2398(.A (rst), .B (n_8), .Y (n_9));
  DFFQX2 \State_r_reg[0] (.CK (clk), .D (n_6), .Q (Q[1]));
  AOI32X1 g303__5107(.A0 (Q[1]), .A1 (State_r[1]), .A2 (n_1), .B0
       (Q[0]), .B1 (n_2), .Y (n_8));
  AOI21X1 g302__6260(.A0 (n_5), .A1 (n_3), .B0 (rst), .Y (n_6));
  XNOR2X1 g306__4319(.A (State_r[1]), .B (n_4), .Y (Q[0]));
  NAND3BXL g304__8428(.AN (State_r[1]), .B (n_4), .C (n_0), .Y (n_5));
  MXI2XL g305__5526(.A (Q[1]), .B (State_r[1]), .S0 (n_2), .Y (n_3));
  INVX1 g307(.A (B), .Y (n_1));
  BUFX2 g308(.A (C), .Y (n_2));
  BUFX2 g309(.A (A), .Y (n_0));
  INVX1 g310(.A (Q[1]), .Y (n_4));
endmodule

