
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 14 2025 10:11:25 -03 (Jan 14 2025 13:11:25 UTC)

// Verification Directory fv/codificador_pt2262 

module ADDRESS_INTERPRETER(A, INTERPRETED_ADDR, F_BIT_LOCATOR);
  input [7:0] A;
  output [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  wire [7:0] A;
  wire [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  comp_endereco comp_endereco(.A (A), .A_01 (INTERPRETED_ADDR), .A_F
       (F_BIT_LOCATOR));
endmodule

module codificador_pt2262(clk, reset, A, D, sync, cod_o);
  input clk, reset;
  input [7:0] A;
  input [3:0] D;
  output sync, cod_o;
  wire clk, reset;
  wire [7:0] A;
  wire [3:0] D;
  wire sync, cod_o;
  wire [7:0] INTERPRETED_ADDR;
  wire [7:0] F_BIT_LOCATOR;
  wire [1:0] bit_gen_input;
  wire [2:0] signal_creator_current_state;
  wire [4:0] current_state;
  wire [6:0] signal_creator_pulse_counter_sync;
  wire [4:0] signal_creator_pulse_counter;
  wire [6:0] internal_oscillator_clk_cycle_counting;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_115, n_116, n_117, n_118, n_119, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_154;
  wire n_156, n_157, n_158, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, osc_clk, past_osc_clk,
       signal_creator_enable_pulse_counting,
       signal_creator_enable_pulse_counting_sync,
       signal_creator_is_first_run;
  ADDRESS_INTERPRETER addr_interpreter(.A (A), .INTERPRETED_ADDR
       (INTERPRETED_ADDR), .F_BIT_LOCATOR (F_BIT_LOCATOR));
  INVXL g9562(.A (n_172), .Y (n_154));
  INVXL g9564(.A (n_199), .Y (sync));
  NAND2BXL g10206__2398(.AN (n_162), .B (cod_o), .Y (n_199));
  NAND2XL g10207__5107(.A (bit_gen_input[0]), .B (n_174), .Y (n_162));
  NAND2XL g10208__6260(.A (n_111), .B (n_173), .Y (bit_gen_input[0]));
  NAND3BXL g10209__4319(.AN (reset), .B (n_151), .C (n_173), .Y
       (n_174));
  NAND2BXL g10210__8428(.AN (n_198), .B (n_152), .Y (n_173));
  OAI2BB1X1 g10212__5526(.A0N (signal_creator_current_state[2]), .A1N
       (n_150), .B0 (n_157), .Y (n_152));
  INVXL g10213(.A (n_180), .Y (n_151));
  NAND3BXL g10214__6783(.AN (current_state[4]), .B (n_176), .C (n_149),
       .Y (n_180));
  INVXL g10215(.A (n_150), .Y (n_175));
  AOI221X1 g10216__3680(.A0 (signal_creator_current_state[0]), .A1
       (n_143), .B0 (n_118), .B1 (n_160), .C0
       (signal_creator_current_state[1]), .Y (n_150));
  INVXL g10217(.A (n_148), .Y (n_149));
  OAI31X1 g10218__1617(.A0 (current_state[2]), .A1 (current_state[1]),
       .A2 (n_127), .B0 (n_146), .Y (n_148));
  OAI211X1 g10219__2802(.A0 (n_179), .A1 (n_141), .B0 (n_138), .C0
       (n_145), .Y (n_147));
  AOI21XL g10220__1705(.A0 (F_BIT_LOCATOR[5]), .A1 (n_131), .B0
       (n_144), .Y (n_146));
  NAND2XL g10221__5122(.A (current_state[1]), .B (n_142), .Y (n_145));
  OAI211X1 g10222__8246(.A0 (n_5), .A1 (n_139), .B0 (n_137), .C0
       (n_135), .Y (n_144));
  NAND2BXL g10223__7098(.AN (n_161), .B
       (signal_creator_pulse_counter_sync[6]), .Y (n_143));
  OAI211X1 g10224__6131(.A0 (n_2), .A1 (n_134), .B0 (n_132), .C0
       (n_136), .Y (n_142));
  AOI221X1 g10225__1881(.A0 (D[3]), .A1 (n_126), .B0 (D[2]), .B1
       (n_123), .C0 (n_140), .Y (n_141));
  NAND2BXL g10226__5115(.AN (n_172), .B
       (signal_creator_current_state[1]), .Y (n_157));
  NAND2BXL g10227__7482(.AN (n_166), .B
       (signal_creator_pulse_counter_sync[5]), .Y (n_161));
  NOR2XL g10228__4733(.A (current_state[2]), .B (n_133), .Y (n_140));
  OR2X1 g10229__6161(.A (signal_creator_current_state[2]), .B (n_160),
       .Y (n_172));
  NAND2BXL g10230__9315(.AN (n_167), .B
       (signal_creator_pulse_counter_sync[4]), .Y (n_166));
  AOI22XL g10231__9945(.A0 (F_BIT_LOCATOR[1]), .A1 (n_129), .B0
       (F_BIT_LOCATOR[4]), .B1 (n_123), .Y (n_139));
  NAND3BXL g10232__2883(.AN (n_177), .B (n_128), .C (n_130), .Y
       (n_138));
  OAI2BB1X1 g10233__2346(.A0N (current_state[2]), .A1N (n_130), .B0
       (n_124), .Y (n_137));
  AOI33XL g10234__1666(.A0 (n_122), .A1 (n_7), .A2 (n_125), .B0
       (n_117), .B1 (INTERPRETED_ADDR[1]), .B2 (n_129), .Y (n_136));
  NAND2BXL g10235__7410(.AN (n_156), .B (F_BIT_LOCATOR[0]), .Y (n_135));
  NAND2BXL g10236__6417(.AN (n_170), .B
       (signal_creator_pulse_counter_sync[3]), .Y (n_167));
  NAND2BXL g10237__5477(.AN (n_164), .B
       (signal_creator_pulse_counter[4]), .Y (n_160));
  AOI221X1 g10238__2398(.A0 (D[0]), .A1 (n_7), .B0 (D[1]), .B1
       (current_state[0]), .C0 (current_state[2]), .Y (n_134));
  AOI33XL g10239__5107(.A0 (INTERPRETED_ADDR[6]), .A1 (n_119), .A2
       (n_7), .B0 (n_121), .B1 (INTERPRETED_ADDR[7]), .B2
       (current_state[0]), .Y (n_133));
  AOI33XL g10240__6260(.A0 (INTERPRETED_ADDR[4]), .A1 (n_115), .A2
       (n_123), .B0 (n_116), .B1 (INTERPRETED_ADDR[5]), .B2 (n_126), .Y
       (n_132));
  INVXL g10241(.A (n_163), .Y (n_131));
  NAND2BXL g10242__4319(.AN (n_171), .B
       (signal_creator_pulse_counter_sync[2]), .Y (n_170));
  OR2X1 g10243__8428(.A (n_168), .B (n_169), .Y (n_164));
  NAND2XL g10244__5526(.A (current_state[1]), .B (n_126), .Y (n_163));
  NAND2BXL g10245__6783(.AN (n_165), .B (current_state[2]), .Y (n_176));
  NAND2BXL g10246__3680(.AN (past_osc_clk), .B (osc_clk), .Y (n_198));
  MX2X1 g10249__1617(.A (INTERPRETED_ADDR[2]), .B
       (INTERPRETED_ADDR[3]), .S0 (current_state[0]), .Y (n_128));
  AOI22XL g10250__2802(.A0 (F_BIT_LOCATOR[6]), .A1 (n_7), .B0
       (F_BIT_LOCATOR[7]), .B1 (current_state[0]), .Y (n_127));
  NAND2XL g10251__1705(.A (n_5), .B (n_125), .Y (n_181));
  AOI22XL g10252__5122(.A0 (F_BIT_LOCATOR[2]), .A1 (n_7), .B0
       (F_BIT_LOCATOR[3]), .B1 (current_state[0]), .Y (n_130));
  OR2X1 g10253__8246(.A (n_158), .B (n_182), .Y (n_156));
  NOR2XL g10254__7098(.A (n_7), .B (n_182), .Y (n_129));
  INVX1 g10255(.A (n_197), .Y (n_126));
  INVXL g10256(.A (n_182), .Y (n_125));
  DFFHQX1 past_osc_clk_reg(.CK (clk), .D (osc_clk), .Q (past_osc_clk));
  NAND2XL g10258__6131(.A (signal_creator_pulse_counter_sync[0]), .B
       (signal_creator_pulse_counter_sync[1]), .Y (n_171));
  NAND2XL g10259__1881(.A (current_state[3]), .B (current_state[1]), .Y
       (n_165));
  NAND2XL g10260__5115(.A (current_state[3]), .B (n_5), .Y (n_179));
  NAND2XL g10261__7482(.A (current_state[2]), .B (current_state[0]), .Y
       (n_197));
  NAND2XL g10262__4733(.A (n_2), .B (n_3), .Y (n_182));
  INVXL g10263(.A (n_124), .Y (n_177));
  INVXL g10264(.A (n_123), .Y (n_178));
  NOR2BX1 g10265__6161(.AN (INTERPRETED_ADDR[0]), .B
       (F_BIT_LOCATOR[0]), .Y (n_122));
  NAND2XL g10266__9315(.A (current_state[1]), .B (n_7), .Y (n_158));
  NAND2XL g10267__9945(.A (signal_creator_pulse_counter[2]), .B
       (signal_creator_pulse_counter[3]), .Y (n_169));
  NAND2XL g10268__2883(.A (signal_creator_pulse_counter[0]), .B
       (signal_creator_pulse_counter[1]), .Y (n_168));
  NOR2XL g10269__2346(.A (current_state[3]), .B (current_state[1]), .Y
       (n_124));
  NOR2XL g10270__1666(.A (current_state[0]), .B (n_3), .Y (n_123));
  INVXL g10271(.A (F_BIT_LOCATOR[7]), .Y (n_121));
  INVX1 g10272(.A (current_state[0]), .Y (n_7));
  INVXL g10273(.A (F_BIT_LOCATOR[6]), .Y (n_119));
  INVXL g10274(.A (signal_creator_current_state[0]), .Y (n_118));
  INVXL g10275(.A (F_BIT_LOCATOR[1]), .Y (n_117));
  INVXL g10276(.A (F_BIT_LOCATOR[5]), .Y (n_116));
  INVXL g10277(.A (F_BIT_LOCATOR[4]), .Y (n_115));
  INVX1 g10278(.A (current_state[3]), .Y (n_2));
  INVX1 g10280(.A (current_state[1]), .Y (n_5));
  NOR4BX1 g2__7410(.AN (n_181), .B (reset), .C (current_state[4]), .D
       (n_147), .Y (n_111));
  DFFHQX1 \current_state_reg[0] (.CK (clk), .D (n_103), .Q
       (current_state[0]));
  DFFHQX1 \current_state_reg[1] (.CK (clk), .D (n_101), .Q
       (current_state[1]));
  DFFHQX1 \current_state_reg[2] (.CK (clk), .D (n_100), .Q
       (current_state[2]));
  DFFHQX1 \current_state_reg[3] (.CK (clk), .D (n_89), .Q
       (current_state[3]));
  DFFHQX1 \current_state_reg[4] (.CK (clk), .D (n_92), .Q
       (current_state[4]));
  SDFFRHQX1 internal_oscillator_OUTPUT_CLK_reg(.RN (n_6), .CK (clk), .D
       (n_85), .SI (n_86), .SE (osc_clk), .Q (osc_clk));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[0] (.RN (n_6),
       .CK (clk), .D (n_93), .Q
       (internal_oscillator_clk_cycle_counting[0]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[1] (.RN (n_6),
       .CK (clk), .D (n_90), .Q
       (internal_oscillator_clk_cycle_counting[1]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[3] (.RN (n_6),
       .CK (clk), .D (n_99), .Q
       (internal_oscillator_clk_cycle_counting[3]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[5] (.RN (n_6),
       .CK (clk), .D (n_108), .Q
       (internal_oscillator_clk_cycle_counting[5]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[6] (.RN (n_6),
       .CK (clk), .D (n_110), .Q
       (internal_oscillator_clk_cycle_counting[6]));
  DFFHQX1 \signal_creator_current_state_reg[0] (.CK (osc_clk), .D
       (n_83), .Q (signal_creator_current_state[0]));
  DFFHQX1 \signal_creator_current_state_reg[1] (.CK (osc_clk), .D
       (n_75), .Q (signal_creator_current_state[1]));
  DFFHQX1 \signal_creator_current_state_reg[2] (.CK (osc_clk), .D
       (n_77), .Q (signal_creator_current_state[2]));
  SDFFRHQX1 signal_creator_enable_pulse_counting_reg(.RN (n_54), .CK
       (osc_clk), .D (signal_creator_enable_pulse_counting), .SI
       (n_62), .SE (n_24), .Q (signal_creator_enable_pulse_counting));
  DFFSHQX1 signal_creator_is_first_run_reg(.SN (n_54), .CK (osc_clk),
       .D (n_73), .Q (signal_creator_is_first_run));
  DFFRHQX1 signal_creator_output_signal_reg(.RN (n_54), .CK (osc_clk),
       .D (n_107), .Q (cod_o));
  DFFHQX1 \signal_creator_pulse_counter_reg[0] (.CK (osc_clk), .D
       (n_16), .Q (signal_creator_pulse_counter[0]));
  DFFHQX1 \signal_creator_pulse_counter_reg[1] (.CK (osc_clk), .D
       (n_60), .Q (signal_creator_pulse_counter[1]));
  DFFHQX1 \signal_creator_pulse_counter_reg[2] (.CK (osc_clk), .D
       (n_63), .Q (signal_creator_pulse_counter[2]));
  DFFHQX1 \signal_creator_pulse_counter_reg[3] (.CK (osc_clk), .D
       (n_82), .Q (signal_creator_pulse_counter[3]));
  DFFHQX1 \signal_creator_pulse_counter_reg[4] (.CK (osc_clk), .D
       (n_48), .Q (signal_creator_pulse_counter[4]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[0] (.CK (osc_clk), .D
       (n_14), .Q (signal_creator_pulse_counter_sync[0]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[1] (.CK (osc_clk), .D
       (n_55), .Q (signal_creator_pulse_counter_sync[1]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[2] (.CK (osc_clk), .D
       (n_71), .Q (signal_creator_pulse_counter_sync[2]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[3] (.CK (osc_clk), .D
       (n_59), .Q (signal_creator_pulse_counter_sync[3]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[4] (.CK (osc_clk), .D
       (n_58), .Q (signal_creator_pulse_counter_sync[4]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[5] (.CK (osc_clk), .D
       (n_57), .Q (signal_creator_pulse_counter_sync[5]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[6] (.CK (osc_clk), .D
       (n_56), .Q (signal_creator_pulse_counter_sync[6]));
  NOR2XL g10689__6417(.A (n_85), .B (n_109), .Y (n_110));
  AOI21XL g10691__5477(.A0 (internal_oscillator_clk_cycle_counting[5]),
       .A1 (n_97), .B0 (internal_oscillator_clk_cycle_counting[6]), .Y
       (n_109));
  NOR2XL g10692__2398(.A (n_85), .B (n_105), .Y (n_108));
  OAI211X1 g10693__5107(.A0 (signal_creator_is_first_run), .A1 (n_44),
       .B0 (n_67), .C0 (n_106), .Y (n_107));
  OAI211X1 g10695__6260(.A0 (cod_o), .A1 (n_9), .B0
       (signal_creator_current_state[2]), .C0 (n_102), .Y (n_106));
  XNOR2X1 g10696__4319(.A (internal_oscillator_clk_cycle_counting[5]),
       .B (n_97), .Y (n_105));
  AOI211XL g10698__8428(.A0 (n_13), .A1 (n_79), .B0 (n_85), .C0 (n_97),
       .Y (n_104));
  OAI211X1 g10701__5526(.A0 (n_0), .A1 (n_50), .B0 (n_6), .C0 (n_98),
       .Y (n_103));
  OAI211X1 g10702__6783(.A0 (signal_creator_current_state[0]), .A1
       (n_41), .B0 (n_9), .C0 (n_96), .Y (n_102));
  OAI211X1 g10705__3680(.A0 (n_0), .A1 (n_202), .B0 (n_6), .C0 (n_88),
       .Y (n_101));
  OAI211X1 g10706__1617(.A0 (n_3), .A1 (n_49), .B0 (n_6), .C0 (n_91),
       .Y (n_100));
  INVXL g10711(.A (n_95), .Y (n_99));
  INVXL g10712(.A (n_94), .Y (n_98));
  NAND3BXL g10713__2802(.AN (signal_creator_pulse_counter_sync[6]), .B
       (signal_creator_current_state[0]), .C (n_84), .Y (n_96));
  OAI211X1 g10714__1705(.A0
       (internal_oscillator_clk_cycle_counting[3]), .A1 (n_45), .B0
       (n_79), .C0 (n_86), .Y (n_95));
  OAI32X1 g10715__5122(.A0 (current_state[3]), .A1 (n_158), .A2 (n_25),
       .B0 (current_state[4]), .B1 (n_80), .Y (n_94));
  NOR2XL g10716__8246(.A (n_13), .B (n_79), .Y (n_97));
  NAND2XL g10718__7098(.A (internal_oscillator_clk_cycle_counting[0]),
       .B (n_86), .Y (n_93));
  AND2X1 g10719__6131(.A (n_81), .B (n_6), .Y (n_92));
  NAND4XL g10722__1881(.A (n_181), .B (n_163), .C (n_69), .D (n_26), .Y
       (n_91));
  NOR3BXL g10723__5115(.AN (n_28), .B (n_20), .C (n_85), .Y (n_90));
  NAND4XL g10724__7482(.A (n_6), .B (n_179), .C (n_70), .D (n_52), .Y
       (n_89));
  AOI22XL g10725__4733(.A0 (current_state[1]), .A1 (n_78), .B0 (n_32),
       .B1 (n_26), .Y (n_88));
  AOI211XL g10726__6161(.A0 (n_4), .A1 (n_28), .B0 (n_45), .C0 (n_85),
       .Y (n_87));
  INVX1 g10732(.A (n_85), .Y (n_86));
  NOR4X1 g10733__9315(.A (signal_creator_pulse_counter_sync[5]), .B
       (signal_creator_pulse_counter_sync[4]), .C
       (signal_creator_pulse_counter_sync[3]), .D (n_21), .Y (n_84));
  AND2X1 g10734__9945(.A (n_72), .B (n_54), .Y (n_83));
  NOR2XL g10735__2883(.A (n_10), .B (n_76), .Y (n_82));
  OAI22XL g10736__2346(.A0 (n_0), .A1 (n_42), .B0 (n_165), .B1 (n_197),
       .Y (n_81));
  AOI33XL g10737__1666(.A0 (n_5), .A1 (n_197), .A2 (n_51), .B0 (n_176),
       .B1 (current_state[0]), .B2 (n_173), .Y (n_80));
  NOR3BXL g10738__7410(.AN (internal_oscillator_clk_cycle_counting[5]),
       .B (n_13), .C (n_68), .Y (n_85));
  NAND2XL g10739__6417(.A (n_0), .B (n_201), .Y (n_78));
  NOR2XL g10740__5477(.A (n_53), .B (n_65), .Y (n_77));
  NAND2XL g10741__2398(.A (internal_oscillator_clk_cycle_counting[3]),
       .B (n_45), .Y (n_79));
  XNOR2X1 g10744__5107(.A (signal_creator_pulse_counter[3]), .B (n_18),
       .Y (n_76));
  OAI32X1 g10745__6260(.A0 (n_9), .A1 (n_154), .A2 (n_53), .B0 (n_44),
       .B1 (n_174), .Y (n_75));
  MX2X1 g10747__8428(.A (signal_creator_is_first_run), .B (n_61), .S0
       (n_24), .Y (n_73));
  OAI211X1 g10748__5526(.A0 (signal_creator_current_state[0]), .A1
       (n_203), .B0 (n_157), .C0 (n_66), .Y (n_72));
  AND2X1 g10749__6783(.A (n_37), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_71));
  OAI31X1 g10757__3680(.A0 (current_state[4]), .A1 (n_3), .A2 (n_17),
       .B0 (current_state[3]), .Y (n_70));
  NOR2XL g10758__1617(.A (n_19), .B (n_46), .Y (n_69));
  NAND4BXL g10759__2802(.AN (n_20), .B
       (internal_oscillator_clk_cycle_counting[6]), .C
       (internal_oscillator_clk_cycle_counting[3]), .D
       (internal_oscillator_clk_cycle_counting[2]), .Y (n_68));
  OAI211X1 g10760__1705(.A0 (n_29), .A1 (n_22), .B0
       (signal_creator_current_state[1]), .C0 (n_11), .Y (n_67));
  NAND2XL g10761__5122(.A (signal_creator_current_state[0]), .B (n_47),
       .Y (n_66));
  AOI22XL g10762__8246(.A0 (n_43), .A1 (n_180), .B0
       (signal_creator_current_state[2]), .B1 (n_175), .Y (n_65));
  AOI211XL g10764__6131(.A0 (n_12), .A1 (n_168), .B0 (n_10), .C0
       (n_18), .Y (n_63));
  INVXL g10765(.A (n_61), .Y (n_62));
  NOR2XL g10766__1881(.A (n_10), .B (n_38), .Y (n_60));
  AND2X1 g10767__5115(.A (n_36), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_59));
  AND2X1 g10768__7482(.A (n_35), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_58));
  AND2X1 g10769__4733(.A (n_33), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_57));
  AND2X1 g10770__6161(.A (n_34), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_56));
  NOR2XL g10771__9315(.A (n_8), .B (n_31), .Y (n_55));
  NAND2XL g10772__9945(.A (n_43), .B (n_162), .Y (n_61));
  INVXL g10773(.A (n_53), .Y (n_54));
  NAND3BXL g10774__2883(.AN (n_163), .B (n_2), .C (n_26), .Y (n_52));
  OAI211X1 g10775__2346(.A0 (n_125), .A1 (n_173), .B0 (n_7), .C0
       (n_199), .Y (n_51));
  XNOR2X1 g10776__1666(.A (current_state[0]), .B (n_27), .Y (n_50));
  OA21X1 g10777__7410(.A0 (n_19), .A1 (n_1), .B0 (n_0), .Y (n_49));
  AND2X1 g10778__6417(.A (n_30), .B
       (signal_creator_enable_pulse_counting), .Y (n_48));
  OAI211X1 g10779__5477(.A0 (bit_gen_input[0]), .A1 (n_174), .B0
       (n_24), .C0 (n_162), .Y (n_47));
  OAI211X1 g10780__2398(.A0 (current_state[0]), .A1 (n_179), .B0
       (n_176), .C0 (n_156), .Y (n_46));
  OAI31X1 g10781__5107(.A0 (n_0), .A1 (n_7), .A2 (n_181), .B0 (n_6), .Y
       (n_53));
  INVXL g10782(.A (n_44), .Y (n_43));
  AND2X1 g10783__6260(.A (n_27), .B (current_state[0]), .Y (n_42));
  AOI21XL g10784__4319(.A0 (signal_creator_pulse_counter[4]), .A1
       (n_169), .B0 (n_29), .Y (n_41));
  NOR2XL g10787__6783(.A (n_4), .B (n_28), .Y (n_45));
  NAND2XL g10790__3680(.A (signal_creator_current_state[0]), .B (n_24),
       .Y (n_44));
  XNOR2X1 g10791__1617(.A (signal_creator_pulse_counter[0]), .B
       (signal_creator_pulse_counter[1]), .Y (n_38));
  XNOR2X1 g10792__2802(.A (signal_creator_pulse_counter_sync[2]), .B
       (n_171), .Y (n_37));
  XNOR2X1 g10793__1705(.A (signal_creator_pulse_counter_sync[3]), .B
       (n_170), .Y (n_36));
  XNOR2X1 g10794__5122(.A (signal_creator_pulse_counter_sync[4]), .B
       (n_167), .Y (n_35));
  XNOR2X1 g10795__8246(.A (signal_creator_pulse_counter_sync[6]), .B
       (n_161), .Y (n_34));
  XNOR2X1 g10796__7098(.A (signal_creator_pulse_counter_sync[5]), .B
       (n_166), .Y (n_33));
  OAI22XL g10797__6131(.A0 (n_179), .A1 (n_178), .B0 (n_197), .B1
       (n_177), .Y (n_32));
  XNOR2X1 g10798__1881(.A (signal_creator_pulse_counter_sync[0]), .B
       (signal_creator_pulse_counter_sync[1]), .Y (n_31));
  XNOR2X1 g10799__5115(.A (signal_creator_pulse_counter[4]), .B
       (n_164), .Y (n_30));
  INVXL g10800(.A (n_26), .Y (n_25));
  NOR2BX1 g10802__7482(.AN (n_169), .B
       (signal_creator_current_state[0]), .Y (n_22));
  NAND2BXL g10803__4733(.AN (signal_creator_pulse_counter_sync[2]), .B
       (n_171), .Y (n_21));
  NOR2XL g10804__6161(.A (signal_creator_pulse_counter[2]), .B
       (signal_creator_pulse_counter[3]), .Y (n_29));
  NAND2XL g10805__9315(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_28));
  NOR2XL g10806__9945(.A (n_198), .B (n_181), .Y (n_27));
  NOR2XL g10807__2883(.A (current_state[4]), .B (n_173), .Y (n_26));
  NOR2XL g10808__2346(.A (signal_creator_current_state[1]), .B
       (signal_creator_current_state[2]), .Y (n_24));
  AND2X1 g10809__1666(.A (n_173), .B (n_163), .Y (n_17));
  NOR2XL g10810__7410(.A (signal_creator_pulse_counter[0]), .B (n_10),
       .Y (n_16));
  NOR2XL g10812__5477(.A (signal_creator_pulse_counter_sync[0]), .B
       (n_8), .Y (n_14));
  NOR2XL g10813__2398(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_20));
  NOR2XL g10814__5107(.A (n_7), .B (n_165), .Y (n_19));
  NOR2XL g10815__6260(.A (n_12), .B (n_168), .Y (n_18));
  INVXL g10817(.A (signal_creator_pulse_counter[2]), .Y (n_12));
  INVXL g10818(.A (signal_creator_current_state[2]), .Y (n_11));
  INVX1 g10819(.A (signal_creator_enable_pulse_counting), .Y (n_10));
  INVX1 g10820(.A (signal_creator_current_state[1]), .Y (n_9));
  INVX1 g10823(.A (reset), .Y (n_6));
  INVX1 g10826(.A (current_state[2]), .Y (n_3));
  INVXL g10828(.A (n_173), .Y (n_1));
  INVX1 g10829(.A (current_state[4]), .Y (n_0));
  OAI22X1 g2(.A0 (n_44), .A1 (n_162), .B0 (n_8), .B1 (n_24), .Y
       (n_200));
  OAI32X1 g10830(.A0 (current_state[3]), .A1 (n_7), .A2 (n_173), .B0
       (n_2), .B1 (n_197), .Y (n_201));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[4] (.RN (n_6), .CK
       (clk), .D (n_104), .Q
       (internal_oscillator_clk_cycle_counting[4]), .QN (n_13));
  DFFRX1 signal_creator_enable_pulse_counting_sync_reg(.RN (n_54), .CK
       (osc_clk), .D (n_200), .Q
       (signal_creator_enable_pulse_counting_sync), .QN (n_8));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[2] (.RN (n_6), .CK
       (clk), .D (n_87), .Q
       (internal_oscillator_clk_cycle_counting[2]), .QN (n_4));
  NAND2BX1 g10837(.AN (n_198), .B (n_129), .Y (n_202));
  AOI2BB1XL g10838(.A0N (signal_creator_current_state[1]), .A1N
       (n_160), .B0 (n_24), .Y (n_203));
endmodule

