
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 10 2025 09:53:44 -03 (Jan 10 2025 12:53:44 UTC)

// Verification Directory fv/codificador_pt2262 

module ADDRESS_INTERPRETER(A, INTERPRETED_ADDR, F_BIT_LOCATOR);
  input [7:0] A;
  output [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  wire [7:0] A;
  wire [7:0] INTERPRETED_ADDR, F_BIT_LOCATOR;
  comp_endereco comp_endereco(.A (A), .A_01 (INTERPRETED_ADDR), .A_F
       (F_BIT_LOCATOR));
endmodule

module codificador_pt2262(clk, reset, A, D, sync, cod_o);
  input clk, reset;
  input [7:0] A;
  input [3:0] D;
  output sync, cod_o;
  wire clk, reset;
  wire [7:0] A;
  wire [3:0] D;
  wire sync, cod_o;
  wire [7:0] INTERPRETED_ADDR;
  wire [7:0] F_BIT_LOCATOR;
  wire [1:0] bit_gen_input;
  wire [7:0] current_state;
  wire [6:0] signal_creator_pulse_counter_sync;
  wire [7:0] signal_creator_current_state;
  wire [4:0] signal_creator_pulse_counter;
  wire [15:0] internal_oscillator_clk_cycle_counting;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_188, n_203, n_204, n_205, n_206;
  wire n_207, n_209, n_210, osc_clk, past_osc_clk,
       signal_creator_enable_pulse_counting,
       signal_creator_enable_pulse_counting_sync,
       signal_creator_is_first_run;
  wire signal_creator_n_28, signal_creator_n_30, signal_creator_n_551,
       signal_creator_n_555, signal_creator_n_561;
  ADDRESS_INTERPRETER addr_interpreter(.A (A), .INTERPRETED_ADDR
       (INTERPRETED_ADDR), .F_BIT_LOCATOR (F_BIT_LOCATOR));
  NAND2BXL g7814__2398(.AN (n_176), .B (cod_o), .Y (n_206));
  NAND2XL g7815__5107(.A (n_182), .B (bit_gen_input[1]), .Y (n_176));
  OR3X1 g7816__6260(.A (reset), .B (n_163), .C (n_173), .Y (n_182));
  NAND3BXL g7817__4319(.AN (n_173), .B (n_154), .C (n_160), .Y
       (bit_gen_input[1]));
  NAND2BXL g7818__8428(.AN (current_state[4]), .B (n_203), .Y (n_173));
  NAND2BXL g7819__5526(.AN (n_172), .B (n_165), .Y (n_203));
  MX2X1 g7820__6783(.A (n_161), .B (n_162), .S0 (current_state[0]), .Y
       (n_163));
  OAI22XL g7821__3680(.A0 (n_168), .A1 (n_158), .B0
       (signal_creator_n_561), .B1 (n_179), .Y (n_165));
  NAND4XL g7822__1617(.A (n_151), .B (n_153), .C (n_154), .D (n_155),
       .Y (n_162));
  NAND4XL g7823__2802(.A (n_146), .B (n_145), .C (n_154), .D (n_156),
       .Y (n_161));
  AOI211XL g7824__1705(.A0 (current_state[0]), .A1 (n_209), .B0
       (reset), .C0 (n_159), .Y (n_160));
  NAND2BXL g7825__5122(.AN (signal_creator_n_30), .B
       (signal_creator_pulse_counter_sync[6]), .Y (n_179));
  AOI21XL g7826__8246(.A0 (n_150), .A1 (n_148), .B0 (current_state[0]),
       .Y (n_159));
  INVXL g7827(.A (n_166), .Y (n_158));
  NAND2BXL g7828__7098(.AN (n_175), .B (signal_creator_n_555), .Y
       (n_166));
  NAND2BXL g7829__6131(.AN (n_174), .B
       (signal_creator_pulse_counter_sync[5]), .Y
       (signal_creator_n_30));
  OAI31X1 g7831__5115(.A0 (signal_creator_current_state[3]), .A1
       (n_139), .A2 (n_180), .B0 (signal_creator_n_551), .Y (n_175));
  NAND2BXL g7832__7482(.AN (n_177), .B
       (signal_creator_pulse_counter_sync[4]), .Y (n_174));
  AOI33XL g7833__4733(.A0 (INTERPRETED_ADDR[4]), .A1 (n_131), .A2
       (n_144), .B0 (n_132), .B1 (INTERPRETED_ADDR[6]), .B2 (n_140), .Y
       (n_156));
  AOI33XL g7834__6161(.A0 (INTERPRETED_ADDR[5]), .A1 (n_137), .A2
       (n_144), .B0 (n_138), .B1 (INTERPRETED_ADDR[7]), .B2 (n_140), .Y
       (n_155));
  NAND2XL g7835__9315(.A (signal_creator_current_state[1]), .B (n_152),
       .Y (signal_creator_n_555));
  AOI33XL g7836__9945(.A0 (INTERPRETED_ADDR[3]), .A1 (n_134), .A2
       (n_143), .B0 (n_136), .B1 (INTERPRETED_ADDR[1]), .B2 (n_11), .Y
       (n_153));
  NOR2XL g7837__2883(.A (signal_creator_current_state[0]), .B (n_167),
       .Y (n_152));
  NAND3BXL g7838__2346(.AN (n_180), .B
       (signal_creator_current_state[3]), .C (n_142), .Y
       (signal_creator_n_551));
  NAND2BXL g7839__1666(.AN (signal_creator_n_28), .B
       (signal_creator_pulse_counter[4]), .Y (n_168));
  OR4X1 g7840__7410(.A (signal_creator_current_state[2]), .B
       (signal_creator_current_state[3]), .C (n_135), .D (n_180), .Y
       (signal_creator_n_561));
  NAND2BXL g7841__6417(.AN (n_181), .B
       (signal_creator_pulse_counter_sync[3]), .Y (n_177));
  AND2X1 g7842__5477(.A (n_184), .B (n_185), .Y (n_154));
  AOI33XL g7843__2398(.A0 (D[1]), .A1 (current_state[1]), .A2
       (current_state[3]), .B0 (current_state[2]), .B1 (D[3]), .B2
       (current_state[3]), .Y (n_151));
  OA22X1 g7844__5107(.A0 (n_132), .A1 (n_205), .B0 (n_131), .B1
       (n_204), .Y (n_150));
  AOI22XL g7846__4319(.A0 (F_BIT_LOCATOR[2]), .A1 (n_143), .B0
       (F_BIT_LOCATOR[0]), .B1 (n_11), .Y (n_148));
  AOI22XL g7847__8428(.A0 (F_BIT_LOCATOR[3]), .A1 (n_143), .B0
       (F_BIT_LOCATOR[1]), .B1 (n_11), .Y (n_147));
  AOI33XL g7848__5526(.A0 (D[0]), .A1 (current_state[1]), .A2
       (current_state[3]), .B0 (current_state[2]), .B1 (D[2]), .B2
       (current_state[3]), .Y (n_146));
  AOI33XL g7849__6783(.A0 (INTERPRETED_ADDR[2]), .A1 (n_130), .A2
       (n_143), .B0 (n_133), .B1 (INTERPRETED_ADDR[0]), .B2 (n_11), .Y
       (n_145));
  NAND2BXL g7850__3680(.AN (n_186), .B
       (signal_creator_pulse_counter_sync[2]), .Y (n_181));
  NAND2BXL g7851__1617(.AN (past_osc_clk), .B (osc_clk), .Y (n_172));
  OR2X1 g7852__2802(.A (n_178), .B (n_169), .Y (signal_creator_n_28));
  INVXL g7853(.A (n_144), .Y (n_170));
  NAND2BXL g7854__1705(.AN (n_204), .B (current_state[3]), .Y (n_185));
  NAND2BXL g7856__5122(.AN (signal_creator_current_state[3]), .B
       (n_142), .Y (n_167));
  NOR2XL g7857__8246(.A (current_state[3]), .B (n_204), .Y (n_144));
  DFFHQX1 past_osc_clk_reg(.CK (clk), .D (osc_clk), .Q (past_osc_clk));
  NAND2XL g7860__7098(.A (signal_creator_pulse_counter[3]), .B
       (signal_creator_pulse_counter[2]), .Y (n_169));
  NAND2XL g7861__6131(.A (signal_creator_pulse_counter[1]), .B
       (signal_creator_pulse_counter[0]), .Y (n_178));
  NAND2XL g7862__1881(.A (signal_creator_pulse_counter_sync[1]), .B
       (signal_creator_pulse_counter_sync[0]), .Y (n_186));
  NAND2XL g7863__5115(.A (current_state[2]), .B (current_state[1]), .Y
       (n_204));
  NOR2XL g7864__7482(.A (current_state[1]), .B (current_state[3]), .Y
       (n_143));
  INVX1 g7865(.A (n_11), .Y (n_188));
  INVX1 g7866(.A (n_140), .Y (n_205));
  NAND2XL g7867__4733(.A (signal_creator_current_state[2]), .B (n_135),
       .Y (n_139));
  NOR2XL g7868__6161(.A (signal_creator_current_state[2]), .B
       (signal_creator_current_state[4]), .Y (n_142));
  NAND2XL g7869__9315(.A (current_state[1]), .B (current_state[3]), .Y
       (n_183));
  NAND2XL g7870__9945(.A (current_state[2]), .B (current_state[3]), .Y
       (n_171));
  OR2X1 g7871__2883(.A (signal_creator_current_state[0]), .B
       (signal_creator_current_state[1]), .Y (n_180));
  NOR2XL g7872__2346(.A (current_state[2]), .B (current_state[3]), .Y
       (n_11));
  NOR2XL g7873__1666(.A (current_state[2]), .B (current_state[1]), .Y
       (n_140));
  INVXL g7874(.A (F_BIT_LOCATOR[7]), .Y (n_138));
  INVXL g7875(.A (F_BIT_LOCATOR[5]), .Y (n_137));
  INVXL g7876(.A (F_BIT_LOCATOR[1]), .Y (n_136));
  INVXL g7877(.A (signal_creator_current_state[4]), .Y (n_135));
  INVXL g7879(.A (F_BIT_LOCATOR[3]), .Y (n_134));
  INVXL g7880(.A (F_BIT_LOCATOR[0]), .Y (n_133));
  INVXL g7881(.A (F_BIT_LOCATOR[6]), .Y (n_132));
  INVXL g7882(.A (F_BIT_LOCATOR[4]), .Y (n_131));
  INVXL g7883(.A (F_BIT_LOCATOR[2]), .Y (n_130));
  NAND2BX1 g2__7410(.AN (current_state[3]), .B (n_140), .Y (n_184));
  DFFHQX1 \current_state_reg[0] (.CK (clk), .D (n_122), .Q
       (current_state[0]));
  DFFHQX1 \current_state_reg[1] (.CK (clk), .D (n_123), .Q
       (current_state[1]));
  DFFHQX1 \current_state_reg[2] (.CK (clk), .D (n_116), .Q
       (current_state[2]));
  DFFHQX1 \current_state_reg[3] (.CK (clk), .D (n_89), .Q
       (current_state[3]));
  DFFHQX1 \current_state_reg[4] (.CK (clk), .D (n_97), .Q
       (current_state[4]));
  SDFFRHQX1 internal_oscillator_OUTPUT_CLK_reg(.RN (n_1), .CK (clk), .D
       (n_105), .SI (n_106), .SE (osc_clk), .Q (osc_clk));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[0] (.RN (n_1),
       .CK (clk), .D (n_113), .Q
       (internal_oscillator_clk_cycle_counting[0]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[1] (.RN (n_1),
       .CK (clk), .D (n_112), .Q
       (internal_oscillator_clk_cycle_counting[1]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[3] (.RN (n_1),
       .CK (clk), .D (n_120), .Q
       (internal_oscillator_clk_cycle_counting[3]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[5] (.RN (n_1),
       .CK (clk), .D (n_127), .Q
       (internal_oscillator_clk_cycle_counting[5]));
  DFFRHQX1 \internal_oscillator_clk_cycle_counting_reg[6] (.RN (n_1),
       .CK (clk), .D (n_129), .Q
       (internal_oscillator_clk_cycle_counting[6]));
  DFFHQX1 \signal_creator_current_state_reg[0] (.CK (osc_clk), .D
       (n_101), .Q (signal_creator_current_state[0]));
  DFFHQX1 \signal_creator_current_state_reg[1] (.CK (osc_clk), .D
       (n_111), .Q (signal_creator_current_state[1]));
  DFFHQX1 \signal_creator_current_state_reg[2] (.CK (osc_clk), .D
       (n_109), .Q (signal_creator_current_state[2]));
  DFFHQX1 \signal_creator_current_state_reg[3] (.CK (osc_clk), .D
       (n_108), .Q (signal_creator_current_state[3]));
  DFFHQX1 \signal_creator_current_state_reg[4] (.CK (osc_clk), .D
       (n_107), .Q (signal_creator_current_state[4]));
  SDFFRHQX1 signal_creator_enable_pulse_counting_reg(.RN (n_64), .CK
       (osc_clk), .D (n_75), .SI
       (signal_creator_enable_pulse_counting), .SE (n_73), .Q
       (signal_creator_enable_pulse_counting));
  DFFSHQX1 signal_creator_is_first_run_reg(.SN (n_64), .CK (osc_clk),
       .D (n_86), .Q (signal_creator_is_first_run));
  SDFFRHQX1 signal_creator_output_signal_reg(.RN (n_64), .CK (osc_clk),
       .D (cod_o), .SI (n_125), .SE (n_0), .Q (cod_o));
  DFFHQX1 \signal_creator_pulse_counter_reg[0] (.CK (osc_clk), .D
       (n_27), .Q (signal_creator_pulse_counter[0]));
  DFFHQX1 \signal_creator_pulse_counter_reg[1] (.CK (osc_clk), .D
       (n_65), .Q (signal_creator_pulse_counter[1]));
  DFFHQX1 \signal_creator_pulse_counter_reg[2] (.CK (osc_clk), .D
       (n_80), .Q (signal_creator_pulse_counter[2]));
  DFFHQX1 \signal_creator_pulse_counter_reg[3] (.CK (osc_clk), .D
       (n_102), .Q (signal_creator_pulse_counter[3]));
  DFFHQX1 \signal_creator_pulse_counter_reg[4] (.CK (osc_clk), .D
       (n_67), .Q (signal_creator_pulse_counter[4]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[0] (.CK (osc_clk), .D
       (n_19), .Q (signal_creator_pulse_counter_sync[0]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[1] (.CK (osc_clk), .D
       (n_70), .Q (signal_creator_pulse_counter_sync[1]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[2] (.CK (osc_clk), .D
       (n_85), .Q (signal_creator_pulse_counter_sync[2]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[3] (.CK (osc_clk), .D
       (n_69), .Q (signal_creator_pulse_counter_sync[3]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[4] (.CK (osc_clk), .D
       (n_68), .Q (signal_creator_pulse_counter_sync[4]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[5] (.CK (osc_clk), .D
       (n_71), .Q (signal_creator_pulse_counter_sync[5]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[6] (.CK (osc_clk), .D
       (n_66), .Q (signal_creator_pulse_counter_sync[6]));
  NOR2XL g8362__6417(.A (n_105), .B (n_128), .Y (n_129));
  AOI21XL g8364__5477(.A0 (internal_oscillator_clk_cycle_counting[5]),
       .A1 (n_119), .B0 (internal_oscillator_clk_cycle_counting[6]), .Y
       (n_128));
  NOR2XL g8365__2398(.A (n_105), .B (n_126), .Y (n_127));
  XNOR2X1 g8367__5107(.A (internal_oscillator_clk_cycle_counting[5]),
       .B (n_119), .Y (n_126));
  OAI211X1 g8370__6260(.A0 (signal_creator_is_first_run), .A1 (n_44),
       .B0 (n_62), .C0 (n_121), .Y (n_125));
  AOI211XL g8371__4319(.A0 (n_6), .A1 (n_99), .B0 (n_105), .C0 (n_119),
       .Y (n_124));
  OAI211X1 g8372__8428(.A0 (n_188), .A1 (n_49), .B0 (n_1), .C0 (n_114),
       .Y (n_123));
  OAI211X1 g8373__5526(.A0 (current_state[0]), .A1 (n_48), .B0 (n_1),
       .C0 (n_117), .Y (n_122));
  NOR2XL g8376__6783(.A (n_115), .B (n_50), .Y (n_121));
  INVXL g8384(.A (n_118), .Y (n_120));
  OAI211X1 g8385__3680(.A0 (internal_oscillator_clk_cycle_counting[3]),
       .A1 (n_53), .B0 (n_99), .C0 (n_106), .Y (n_118));
  AOI221X1 g8386__1617(.A0 (n_185), .A1 (n_47), .B0 (n_8), .B1 (n_88),
       .C0 (n_51), .Y (n_117));
  NAND3BXL g8387__2802(.AN (n_100), .B (n_1), .C (n_96), .Y (n_116));
  NOR4X1 g8388__1705(.A (signal_creator_pulse_counter_sync[6]), .B
       (signal_creator_pulse_counter_sync[5]), .C (n_92), .D
       (signal_creator_n_561), .Y (n_115));
  AOI22XL g8389__5122(.A0 (n_8), .A1 (n_104), .B0 (current_state[1]),
       .B1 (current_state[4]), .Y (n_114));
  NOR2XL g8391__8246(.A (n_6), .B (n_99), .Y (n_119));
  NAND2XL g8392__7098(.A (internal_oscillator_clk_cycle_counting[0]),
       .B (n_106), .Y (n_113));
  NOR3BXL g8393__6131(.AN (n_31), .B (n_33), .C (n_105), .Y (n_112));
  OAI211X1 g8396__1881(.A0 (signal_creator_n_555), .A1 (n_84), .B0
       (n_95), .C0 (n_91), .Y (n_111));
  AOI211XL g8397__5115(.A0 (n_13), .A1 (n_31), .B0 (n_53), .C0 (n_105),
       .Y (n_110));
  OAI31X1 g8398__7482(.A0 (n_83), .A1 (n_182), .A2 (bit_gen_input[1]),
       .B0 (n_103), .Y (n_109));
  OAI211X1 g8399__4733(.A0 (signal_creator_n_551), .A1 (n_84), .B0
       (n_98), .C0 (n_90), .Y (n_108));
  OAI211X1 g8400__6161(.A0 (n_83), .A1 (n_176), .B0 (n_79), .C0 (n_94),
       .Y (n_107));
  INVX1 g8406(.A (n_105), .Y (n_106));
  OAI211X1 g8407__9315(.A0 (n_4), .A1 (n_55), .B0 (n_76), .C0 (n_210),
       .Y (n_104));
  OAI2BB1X1 g8408__9945(.A0N (n_84), .A1N (n_82), .B0
       (signal_creator_current_state[2]), .Y (n_103));
  NOR2XL g8409__2883(.A (n_10), .B (n_87), .Y (n_102));
  OAI2BB1X1 g8410__2346(.A0N (signal_creator_current_state[0]), .A1N
       (n_81), .B0 (n_78), .Y (n_101));
  NOR4X1 g8411__1666(.A (current_state[4]), .B (n_54), .C (n_61), .D
       (n_203), .Y (n_100));
  NOR3BXL g8412__7410(.AN (internal_oscillator_clk_cycle_counting[5]),
       .B (n_6), .C (n_77), .Y (n_105));
  NAND2XL g8413__6417(.A (signal_creator_current_state[3]), .B (n_81),
       .Y (n_98));
  AOI21XL g8414__5477(.A0 (n_26), .A1 (n_57), .B0 (reset), .Y (n_97));
  OAI2BB1X1 g8415__2398(.A0N (n_8), .A1N (n_58), .B0
       (current_state[2]), .Y (n_96));
  NAND2XL g8416__5107(.A (signal_creator_current_state[1]), .B (n_81),
       .Y (n_95));
  NAND2XL g8417__6260(.A (signal_creator_current_state[4]), .B (n_81),
       .Y (n_94));
  NAND2XL g8418__4319(.A (internal_oscillator_clk_cycle_counting[3]),
       .B (n_53), .Y (n_99));
  OR4X1 g8422__5526(.A (signal_creator_pulse_counter_sync[2]), .B
       (signal_creator_pulse_counter_sync[4]), .C
       (signal_creator_pulse_counter_sync[3]), .D (n_15), .Y (n_92));
  NAND3BXL g8423__6783(.AN (n_83), .B (n_182), .C (n_7), .Y (n_91));
  NAND3BXL g8424__3680(.AN (n_83), .B (bit_gen_input[1]), .C (n_14), .Y
       (n_90));
  NAND4XL g8425__1617(.A (n_1), .B (n_35), .C (n_46), .D (n_56), .Y
       (n_89));
  OAI22XL g8426__2802(.A0 (current_state[0]), .A1 (n_59), .B0 (n_205),
       .B1 (n_20), .Y (n_88));
  XNOR2X1 g8427__1705(.A (signal_creator_pulse_counter[3]), .B (n_32),
       .Y (n_87));
  MX2X1 g8428__5122(.A (n_74), .B (signal_creator_is_first_run), .S0
       (n_73), .Y (n_86));
  AND2X1 g8429__8246(.A (n_41), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_85));
  INVXL g8437(.A (n_81), .Y (n_82));
  AOI211XL g8438__7098(.A0 (n_12), .A1 (n_178), .B0 (n_10), .C0 (n_32),
       .Y (n_80));
  NAND3BXL g8439__6131(.AN (signal_creator_n_561), .B (n_64), .C
       (n_179), .Y (n_79));
  OAI21XL g8440__1881(.A0 (n_34), .A1 (n_165), .B0 (n_64), .Y (n_78));
  NAND4BXL g8441__5115(.AN (n_33), .B
       (internal_oscillator_clk_cycle_counting[6]), .C
       (internal_oscillator_clk_cycle_counting[3]), .D
       (internal_oscillator_clk_cycle_counting[2]), .Y (n_77));
  OAI211X1 g8442__7482(.A0 (n_29), .A1 (n_18), .B0 (n_205), .C0 (n_3),
       .Y (n_76));
  NAND2XL g8444__4733(.A (n_168), .B (n_64), .Y (n_84));
  NAND2XL g8445__6161(.A (n_45), .B (n_64), .Y (n_83));
  NOR3XL g8446__9315(.A (n_45), .B (n_63), .C (n_25), .Y (n_81));
  INVXL g8447(.A (n_74), .Y (n_75));
  INVXL g8448(.A (n_73), .Y (n_72));
  AND2X1 g8449__9945(.A (n_39), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_71));
  NOR2XL g8450__2883(.A (n_9), .B (n_36), .Y (n_70));
  AND2X1 g8451__2346(.A (n_37), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_69));
  AND2X1 g8452__1666(.A (n_40), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_68));
  AND2X1 g8453__7410(.A (n_42), .B
       (signal_creator_enable_pulse_counting), .Y (n_67));
  AND2X1 g8454__6417(.A (n_38), .B
       (signal_creator_enable_pulse_counting_sync), .Y (n_66));
  NOR2XL g8455__5477(.A (n_10), .B (n_43), .Y (n_65));
  NAND2XL g8456__2398(.A (n_45), .B (n_176), .Y (n_74));
  NOR2XL g8457__5107(.A (n_34), .B (n_45), .Y (n_73));
  INVX1 g8458(.A (n_63), .Y (n_64));
  OAI2BB1X1 g8459__6260(.A0N (signal_creator_n_555), .A1N (n_28), .B0
       (n_169), .Y (n_62));
  OAI22XL g8460__4319(.A0 (current_state[1]), .A1 (n_30), .B0 (n_23),
       .B1 (n_188), .Y (n_61));
  OAI211X1 g8462__5526(.A0 (n_184), .A1 (sync), .B0 (n_183), .C0 (n_3),
       .Y (n_59));
  OAI21XL g8463__6783(.A0 (n_5), .A1 (n_24), .B0 (n_203), .Y (n_58));
  OAI2BB1X1 g8464__3680(.A0N (current_state[0]), .A1N (n_22), .B0
       (current_state[4]), .Y (n_57));
  OR3XL g8465__1617(.A (current_state[4]), .B (n_170), .C (n_20), .Y
       (n_56));
  AOI22XL g8466__2802(.A0 (n_5), .A1 (n_20), .B0 (n_17), .B1 (n_203),
       .Y (n_55));
  OAI22XL g8467__1705(.A0 (n_24), .A1 (n_11), .B0 (current_state[0]),
       .B1 (n_171), .Y (n_54));
  OAI21XL g8468__5122(.A0 (n_21), .A1 (n_184), .B0 (n_1), .Y (n_63));
  NOR2XL g8470__7098(.A (n_21), .B (n_22), .Y (n_51));
  NOR3BXL g8471__6131(.AN (n_175), .B
       (signal_creator_pulse_counter[3]), .C
       (signal_creator_pulse_counter[2]), .Y (n_50));
  OR2X1 g8472__1881(.A (n_172), .B (n_21), .Y (n_49));
  NAND2XL g8473__5115(.A (current_state[4]), .B (n_22), .Y (n_48));
  AOI21XL g8474__7482(.A0 (n_2), .A1 (n_206), .B0 (n_173), .Y (n_47));
  NAND2XL g8475__4733(.A (n_29), .B (n_203), .Y (n_46));
  NOR2XL g8476__6161(.A (n_13), .B (n_31), .Y (n_53));
  INVX1 g8479(.A (n_45), .Y (n_44));
  XNOR2X1 g8480__9315(.A (signal_creator_pulse_counter[0]), .B
       (signal_creator_pulse_counter[1]), .Y (n_43));
  XNOR2X1 g8481__9945(.A (signal_creator_pulse_counter[4]), .B
       (signal_creator_n_28), .Y (n_42));
  XNOR2X1 g8482__2883(.A (signal_creator_pulse_counter_sync[2]), .B
       (n_186), .Y (n_41));
  XNOR2X1 g8483__2346(.A (signal_creator_pulse_counter_sync[4]), .B
       (n_177), .Y (n_40));
  XNOR2X1 g8484__1666(.A (signal_creator_pulse_counter_sync[5]), .B
       (n_174), .Y (n_39));
  XNOR2X1 g8485__7410(.A (signal_creator_pulse_counter_sync[6]), .B
       (signal_creator_n_30), .Y (n_38));
  XNOR2X1 g8486__6417(.A (signal_creator_pulse_counter_sync[3]), .B
       (n_181), .Y (n_37));
  XNOR2X1 g8487__5477(.A (signal_creator_pulse_counter_sync[0]), .B
       (signal_creator_pulse_counter_sync[1]), .Y (n_36));
  OAI21XL g8488__2398(.A0 (current_state[4]), .A1 (n_204), .B0
       (current_state[3]), .Y (n_35));
  NOR3BXL g8489__5107(.AN (signal_creator_current_state[0]), .B
       (signal_creator_current_state[1]), .C (n_167), .Y (n_45));
  INVXL g8490(.A (n_29), .Y (n_30));
  NAND2BXL g8491__6260(.AN (signal_creator_n_551), .B
       (signal_creator_pulse_counter[4]), .Y (n_28));
  NOR2XL g8492__4319(.A (signal_creator_pulse_counter[0]), .B (n_10),
       .Y (n_27));
  OR2X1 g8493__8428(.A (n_2), .B (n_185), .Y (n_26));
  NOR2XL g8494__5526(.A (n_180), .B (n_167), .Y (n_34));
  NOR2XL g8495__6783(.A (internal_oscillator_clk_cycle_counting[1]), .B
       (internal_oscillator_clk_cycle_counting[0]), .Y (n_33));
  NOR2XL g8496__3680(.A (n_12), .B (n_178), .Y (n_32));
  NAND2XL g8497__1617(.A (internal_oscillator_clk_cycle_counting[1]),
       .B (internal_oscillator_clk_cycle_counting[0]), .Y (n_31));
  NOR2XL g8498__2802(.A (current_state[0]), .B (n_5), .Y (n_29));
  INVXL g8500(.A (n_23), .Y (n_24));
  NOR2XL g8501__1705(.A (signal_creator_pulse_counter_sync[0]), .B
       (n_9), .Y (n_19));
  NOR2XL g8502__5122(.A (current_state[2]), .B (n_11), .Y (n_18));
  NAND2XL g8503__8246(.A (current_state[2]), .B (current_state[0]), .Y
       (n_17));
  NAND2BXL g8504__7098(.AN (n_166), .B (signal_creator_n_561), .Y
       (n_25));
  NOR2XL g8505__6131(.A (n_4), .B (n_2), .Y (n_23));
  NOR2XL g8506__1881(.A (n_172), .B (n_184), .Y (n_22));
  NAND2XL g8507__5115(.A (current_state[4]), .B (current_state[0]), .Y
       (n_21));
  NAND2XL g8508__7482(.A (current_state[0]), .B (n_3), .Y (n_20));
  INVXL g8509(.A (n_206), .Y (sync));
  INVXL g8510(.A (n_186), .Y (n_15));
  INVXL g8511(.A (n_182), .Y (n_14));
  INVXL g8513(.A (signal_creator_pulse_counter[2]), .Y (n_12));
  INVX1 g8515(.A (signal_creator_enable_pulse_counting), .Y (n_10));
  INVX1 g8517(.A (current_state[4]), .Y (n_8));
  INVXL g8518(.A (bit_gen_input[1]), .Y (n_7));
  INVX1 g8520(.A (current_state[3]), .Y (n_5));
  INVX1 g8521(.A (current_state[1]), .Y (n_4));
  INVX1 g8522(.A (n_203), .Y (n_3));
  INVX1 g8523(.A (current_state[0]), .Y (n_2));
  INVX1 g8524(.A (reset), .Y (n_1));
  NAND2BX1 g7884__4733(.AN (n_25), .B (n_73), .Y (n_0));
  OAI22X1 g2(.A0 (n_44), .A1 (n_176), .B0 (n_9), .B1 (n_72), .Y
       (n_207));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[2] (.RN (n_1), .CK
       (clk), .D (n_110), .Q
       (internal_oscillator_clk_cycle_counting[2]), .QN (n_13));
  DFFRX1 signal_creator_enable_pulse_counting_sync_reg(.RN (n_64), .CK
       (osc_clk), .D (n_207), .Q
       (signal_creator_enable_pulse_counting_sync), .QN (n_9));
  DFFRX1 \internal_oscillator_clk_cycle_counting_reg[4] (.RN (n_1), .CK
       (clk), .D (n_124), .Q
       (internal_oscillator_clk_cycle_counting[4]), .QN (n_6));
  OAI221X1 g8532(.A0 (n_138), .A1 (n_205), .B0 (n_137), .B1 (n_204),
       .C0 (n_147), .Y (n_209));
  NAND3BXL g8533(.AN (n_20), .B (n_188), .C (n_143), .Y (n_210));
endmodule

