
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Dec 20 2024 13:24:43 -03 (Dec 20 2024 16:24:43 UTC)

// Verification Directory fv/PT2262_ENCODER 

module PT2262_ENCODER(clk, reset, A, D, sync, cod_o);
  input clk, reset;
  input [7:0] A;
  input [3:0] D;
  output sync, cod_o;
  wire clk, reset;
  wire [7:0] A;
  wire [3:0] D;
  wire sync, cod_o;
  wire [7:0] INTERPRETED_ADDR;
  wire [7:0] F_BIT_LOCATOR;
  wire [1:0] bit_gen_input;
  wire [7:0] current_state;
  wire [15:0] internal_oscillator_clk_cycle_counting;
  wire [7:0] signal_creator_current_state;
  wire [4:0] signal_creator_pulse_counter;
  wire [6:0] signal_creator_pulse_counter_sync;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       bit_gen_enb, bit_gen_output, bit_gen_rst, bit_sent_flag;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_153;
  wire n_155, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_202;
  wire n_203, osc_clk, osc_rst, past_osc_clk,
       signal_creator_enable_pulse_counting,
       signal_creator_enable_pulse_counting_sync,
       signal_creator_is_first_run;
  ADDRESS_INTERPRETER addr_interpreter(.A (A), .INTERPRETED_ADDR
       (INTERPRETED_ADDR), .F_BIT_LOCATOR (F_BIT_LOCATOR));
  INVXL g5284(.A (n_203), .Y (sync));
  AND2XL g5644__2398(.A (bit_gen_output), .B (n_180), .Y (cod_o));
  NAND2BXL g5645__5107(.AN (n_180), .B (bit_gen_output), .Y (n_203));
  NAND2XL g5646__6260(.A (bit_gen_input[0]), .B (bit_gen_input[1]), .Y
       (n_180));
  TLATX1 \bit_gen_input_reg[1] (.G (n_173), .D (n_171), .Q
       (bit_gen_input[1]), .QN (UNCONNECTED));
  OAI211X1 g5648__4319(.A0 (current_state[0]), .A1 (n_159), .B0
       (n_168), .C0 (n_170), .Y (n_171));
  AND3XL g5649__8428(.A (osc_rst), .B (n_186), .C (n_169), .Y (n_173));
  AOI32X1 g5650__5526(.A0 (n_155), .A1 (n_185), .A2 (n_166), .B0
       (F_BIT_LOCATOR[0]), .B1 (n_163), .Y (n_170));
  OAI221X1 g5651__6783(.A0 (current_state[4]), .A1 (n_165), .B0
       (n_185), .B1 (n_176), .C0 (n_178), .Y (n_169));
  TLATNXL bit_gen_rst_reg(.GN (n_167), .D (osc_rst), .Q (bit_gen_rst),
       .QN (n_11));
  OA22X1 g5653__3680(.A0 (n_179), .A1 (n_164), .B0 (n_161), .B1
       (n_178), .Y (n_168));
  AOI31X1 g5654__1617(.A0 (current_state[4]), .A1 (n_13), .A2 (n_160),
       .B0 (reset), .Y (n_167));
  AOI221X1 g5655__2802(.A0 (n_10), .A1 (n_157), .B0 (current_state[0]),
       .B1 (n_158), .C0 (n_16), .Y (n_166));
  AND2X1 g5656__1705(.A (n_162), .B (n_177), .Y (n_165));
  AOI32X1 g5657__5122(.A0 (F_BIT_LOCATOR[5]), .A1 (current_state[0]),
       .A2 (n_185), .B0 (F_BIT_LOCATOR[4]), .B1 (n_10), .Y (n_164));
  INVXL g5658(.A (n_163), .Y (n_174));
  NOR2XL g5659__8246(.A (n_202), .B (n_178), .Y (n_163));
  OAI2BB1X1 g5660__7098(.A0N (n_183), .A1N (n_13), .B0 (n_185), .Y
       (n_162));
  NAND2BXL g5661__6131(.AN (n_175), .B (bit_sent_flag), .Y (n_186));
  NAND2BXL g5662__1881(.AN (n_182), .B (F_BIT_LOCATOR[1]), .Y (n_161));
  NOR2XL g5663__5115(.A (current_state[1]), .B (n_182), .Y (n_160));
  NAND2XL g5664__7482(.A (current_state[0]), .B (n_155), .Y (n_176));
  NAND2BXL g5665__4733(.AN (past_osc_clk), .B (osc_clk), .Y (n_175));
  OR2X1 g5666__6161(.A (n_187), .B (n_185), .Y (n_159));
  OAI22XL g5667__9315(.A0 (F_BIT_LOCATOR[7]), .A1 (current_state[2]),
       .B0 (F_BIT_LOCATOR[3]), .B1 (n_13), .Y (n_158));
  OAI22XL g5668__9945(.A0 (F_BIT_LOCATOR[6]), .A1 (current_state[2]),
       .B0 (F_BIT_LOCATOR[2]), .B1 (n_13), .Y (n_157));
  OR2X1 g5669__2883(.A (n_13), .B (n_187), .Y (n_179));
  OR2X1 g5670__2346(.A (current_state[2]), .B (n_187), .Y (n_178));
  DFFHQX1 past_osc_clk_reg(.CK (clk), .D (osc_clk), .Q (past_osc_clk));
  NAND2XL g5673__1666(.A (n_153), .B (n_13), .Y (n_181));
  NAND2XL g5674__7410(.A (n_153), .B (n_10), .Y (n_202));
  NAND2XL g5675__6417(.A (current_state[3]), .B (current_state[0]), .Y
       (n_183));
  INVX1 g5676(.A (n_155), .Y (n_184));
  NAND2XL g5677__5477(.A (current_state[3]), .B (n_10), .Y (n_177));
  NAND2XL g5678__2398(.A (current_state[0]), .B (n_153), .Y (n_182));
  NOR2XL g5679__5107(.A (current_state[1]), .B (current_state[4]), .Y
       (n_155));
  NAND2BXL g5680__6260(.AN (current_state[4]), .B (current_state[1]),
       .Y (n_187));
  NAND2XL g5681__4319(.A (current_state[3]), .B (current_state[2]), .Y
       (n_185));
  INVX1 g5682(.A (reset), .Y (osc_rst));
  INVX1 g5683(.A (current_state[2]), .Y (n_13));
  INVX1 g5684(.A (current_state[3]), .Y (n_153));
  TLATX1 bit_gen_enb_reg(.G (n_28), .D (osc_rst), .Q (bit_gen_enb), .QN
       (UNCONNECTED0));
  TLATX1 \bit_gen_input_reg[0] (.G (n_173), .D (n_104), .Q
       (bit_gen_input[0]), .QN (UNCONNECTED1));
  DFFSHQX1 \current_state_reg[0] (.SN (osc_rst), .CK (clk), .D (n_100),
       .Q (current_state[0]));
  DFFSHQX1 \current_state_reg[1] (.SN (osc_rst), .CK (clk), .D (n_88),
       .Q (current_state[1]));
  DFFSHQX1 \current_state_reg[2] (.SN (osc_rst), .CK (clk), .D (n_71),
       .Q (current_state[2]));
  DFFSHQX1 \current_state_reg[3] (.SN (osc_rst), .CK (clk), .D (n_76),
       .Q (current_state[3]));
  DFFHQX1 internal_oscillator_OUTPUT_CLK_reg(.CK (clk), .D (n_123), .Q
       (osc_clk));
  SDFFQX1 \internal_oscillator_clk_cycle_counting_reg[0] (.CK (clk), .D
       (n_15), .SI (osc_rst), .SE (n_105), .Q
       (internal_oscillator_clk_cycle_counting[0]));
  DFFHQX1 \internal_oscillator_clk_cycle_counting_reg[1] (.CK (clk), .D
       (n_112), .Q (internal_oscillator_clk_cycle_counting[1]));
  DFFHQX1 \internal_oscillator_clk_cycle_counting_reg[2] (.CK (clk), .D
       (n_111), .Q (internal_oscillator_clk_cycle_counting[2]));
  DFFHQX1 \internal_oscillator_clk_cycle_counting_reg[3] (.CK (clk), .D
       (n_108), .Q (internal_oscillator_clk_cycle_counting[3]));
  DFFHQX1 \internal_oscillator_clk_cycle_counting_reg[4] (.CK (clk), .D
       (n_128), .Q (internal_oscillator_clk_cycle_counting[4]));
  DFFHQX1 \internal_oscillator_clk_cycle_counting_reg[5] (.CK (clk), .D
       (n_139), .Q (internal_oscillator_clk_cycle_counting[5]));
  DFFHQX1 \internal_oscillator_clk_cycle_counting_reg[6] (.CK (clk), .D
       (n_142), .Q (internal_oscillator_clk_cycle_counting[6]));
  TLATX1 signal_creator_bit_sent_reg(.G (n_150), .D (n_56), .Q
       (bit_sent_flag), .QN (UNCONNECTED2));
  DFFHQX1 \signal_creator_current_state_reg[0] (.CK (osc_clk), .D
       (n_151), .Q (signal_creator_current_state[0]));
  DFFHQX1 \signal_creator_current_state_reg[1] (.CK (osc_clk), .D
       (n_135), .Q (signal_creator_current_state[1]));
  DFFHQX1 \signal_creator_current_state_reg[2] (.CK (osc_clk), .D
       (n_137), .Q (signal_creator_current_state[2]));
  DFFHQX1 \signal_creator_current_state_reg[3] (.CK (osc_clk), .D
       (n_136), .Q (signal_creator_current_state[3]));
  DFFHQX1 \signal_creator_current_state_reg[4] (.CK (osc_clk), .D
       (n_147), .Q (signal_creator_current_state[4]));
  SDFFRHQX1 signal_creator_enable_pulse_counting_reg(.RN (bit_gen_rst),
       .CK (osc_clk), .D (signal_creator_enable_pulse_counting), .SI
       (n_57), .SE (n_83), .Q (signal_creator_enable_pulse_counting));
  SDFFRHQX1 signal_creator_enable_pulse_counting_sync_reg(.RN
       (bit_gen_rst), .CK (osc_clk), .D
       (signal_creator_enable_pulse_counting_sync), .SI (n_77), .SE
       (n_79), .Q (signal_creator_enable_pulse_counting_sync));
  DFFSHQX1 signal_creator_is_first_run_reg(.SN (bit_gen_rst), .CK
       (osc_clk), .D (n_95), .Q (signal_creator_is_first_run));
  SDFFRHQX1 signal_creator_output_signal_reg(.RN (bit_gen_rst), .CK
       (osc_clk), .D (bit_gen_output), .SI (n_110), .SE (n_102), .Q
       (bit_gen_output));
  DFFHQX1 \signal_creator_pulse_counter_reg[0] (.CK (osc_clk), .D
       (n_22), .Q (signal_creator_pulse_counter[0]));
  DFFHQX1 \signal_creator_pulse_counter_reg[1] (.CK (osc_clk), .D
       (n_61), .Q (signal_creator_pulse_counter[1]));
  DFFHQX1 \signal_creator_pulse_counter_reg[2] (.CK (osc_clk), .D
       (n_92), .Q (signal_creator_pulse_counter[2]));
  DFFHQX1 \signal_creator_pulse_counter_reg[3] (.CK (osc_clk), .D
       (n_114), .Q (signal_creator_pulse_counter[3]));
  DFFHQX1 \signal_creator_pulse_counter_reg[4] (.CK (osc_clk), .D
       (n_127), .Q (signal_creator_pulse_counter[4]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[0] (.CK (osc_clk), .D
       (n_21), .Q (signal_creator_pulse_counter_sync[0]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[1] (.CK (osc_clk), .D
       (n_62), .Q (signal_creator_pulse_counter_sync[1]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[2] (.CK (osc_clk), .D
       (n_91), .Q (signal_creator_pulse_counter_sync[2]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[3] (.CK (osc_clk), .D
       (n_115), .Q (signal_creator_pulse_counter_sync[3]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[4] (.CK (osc_clk), .D
       (n_124), .Q (signal_creator_pulse_counter_sync[4]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[5] (.CK (osc_clk), .D
       (n_138), .Q (signal_creator_pulse_counter_sync[5]));
  DFFHQX1 \signal_creator_pulse_counter_sync_reg[6] (.CK (osc_clk), .D
       (n_144), .Q (signal_creator_pulse_counter_sync[6]));
  AO22X1 g6975__8428(.A0 (bit_gen_enb), .A1 (n_149), .B0
       (signal_creator_current_state[0]), .B1 (n_106), .Y (n_151));
  NAND2XL g6978__5526(.A (n_81), .B (n_148), .Y (n_150));
  OAI21XL g6979__6783(.A0 (n_11), .A1 (n_51), .B0 (n_148), .Y (n_149));
  NAND2XL g6980__3680(.A (bit_gen_rst), .B (n_145), .Y (n_148));
  OAI211X1 g6981__1617(.A0 (n_180), .A1 (n_81), .B0 (n_146), .C0
       (n_116), .Y (n_147));
  NAND3BXL g6983__2802(.AN (n_58), .B (bit_gen_rst), .C (n_141), .Y
       (n_146));
  OAI22XL g6984__1705(.A0 (n_119), .A1 (n_90), .B0 (n_58), .B1 (n_141),
       .Y (n_145));
  INVXL g6985(.A (n_143), .Y (n_144));
  OAI211X1 g6986__5122(.A0 (signal_creator_pulse_counter_sync[6]), .A1
       (n_129), .B0 (signal_creator_enable_pulse_counting_sync), .C0
       (n_141), .Y (n_143));
  NOR2XL g6991__8246(.A (n_105), .B (n_140), .Y (n_142));
  AOI21XL g6994__7098(.A0 (internal_oscillator_clk_cycle_counting[5]),
       .A1 (n_121), .B0 (internal_oscillator_clk_cycle_counting[6]), .Y
       (n_140));
  NOR2XL g6995__6131(.A (n_105), .B (n_130), .Y (n_139));
  NAND2XL g6996__1881(.A (signal_creator_pulse_counter_sync[6]), .B
       (n_129), .Y (n_141));
  INVXL g6997(.A (n_134), .Y (n_138));
  OAI31X1 g6998__5115(.A0 (bit_gen_input[1]), .A1 (bit_gen_input[0]),
       .A2 (n_81), .B0 (n_132), .Y (n_137));
  OAI211X1 g6999__7482(.A0 (n_59), .A1 (n_126), .B0 (n_86), .C0
       (n_117), .Y (n_136));
  OAI211X1 g7000__4733(.A0 (n_60), .A1 (n_126), .B0 (n_85), .C0
       (n_118), .Y (n_135));
  OAI211X1 g7001__6161(.A0 (signal_creator_pulse_counter_sync[5]), .A1
       (n_120), .B0 (signal_creator_enable_pulse_counting_sync), .C0
       (n_133), .Y (n_134));
  INVXL g7002(.A (n_129), .Y (n_133));
  AOI21XL g7003__9315(.A0 (signal_creator_current_state[2]), .A1
       (n_106), .B0 (n_131), .Y (n_132));
  NOR2XL g7006__9945(.A (n_47), .B (n_126), .Y (n_131));
  XNOR2X1 g7007__2883(.A (internal_oscillator_clk_cycle_counting[5]),
       .B (n_121), .Y (n_130));
  NOR2XL g7009__2346(.A (n_122), .B (n_105), .Y (n_128));
  AND2X1 g7011__1666(.A (n_120), .B
       (signal_creator_pulse_counter_sync[5]), .Y (n_129));
  INVXL g7012(.A (n_125), .Y (n_127));
  OAI211X1 g7013__7410(.A0 (signal_creator_pulse_counter[4]), .A1
       (n_96), .B0 (signal_creator_enable_pulse_counting), .C0 (n_119),
       .Y (n_125));
  AOI211XL g7014__6417(.A0 (n_9), .A1 (n_98), .B0 (n_2), .C0 (n_120),
       .Y (n_124));
  NAND2XL g7015__5477(.A (bit_gen_rst), .B (n_119), .Y (n_126));
  NOR2XL g7021__2398(.A (reset), .B (n_0), .Y (n_123));
  XNOR2X1 g7022__5107(.A (internal_oscillator_clk_cycle_counting[4]),
       .B (n_97), .Y (n_122));
  NAND2XL g7025__6260(.A (signal_creator_current_state[1]), .B (n_106),
       .Y (n_118));
  NAND2XL g7026__4319(.A (signal_creator_current_state[3]), .B (n_106),
       .Y (n_117));
  NAND2XL g7027__8428(.A (signal_creator_current_state[4]), .B (n_106),
       .Y (n_116));
  AND2X1 g7028__5526(.A (n_97), .B
       (internal_oscillator_clk_cycle_counting[4]), .Y (n_121));
  NOR2XL g7029__6783(.A (n_9), .B (n_98), .Y (n_120));
  NAND2XL g7030__3680(.A (signal_creator_pulse_counter[4]), .B (n_96),
       .Y (n_119));
  INVXL g7032(.A (n_113), .Y (n_115));
  INVXL g7033(.A (n_109), .Y (n_114));
  OAI211X1 g7034__1617(.A0 (signal_creator_pulse_counter_sync[3]), .A1
       (n_68), .B0 (signal_creator_enable_pulse_counting_sync), .C0
       (n_98), .Y (n_113));
  NOR2XL g7035__2802(.A (n_39), .B (n_105), .Y (n_112));
  NOR2XL g7036__1705(.A (n_70), .B (n_105), .Y (n_111));
  OAI221X1 g7037__5122(.A0 (signal_creator_is_first_run), .A1 (n_56),
       .B0 (signal_creator_pulse_counter[3]), .B1 (n_94), .C0 (n_101),
       .Y (n_110));
  OAI211X1 g7039__8246(.A0 (signal_creator_pulse_counter[3]), .A1
       (n_67), .B0 (signal_creator_enable_pulse_counting), .C0 (n_107),
       .Y (n_109));
  NOR2XL g7040__7098(.A (n_99), .B (n_105), .Y (n_108));
  INVXL g7041(.A (n_96), .Y (n_107));
  OAI222XL g7044__6131(.A0 (current_state[2]), .A1 (n_63), .B0 (n_187),
       .B1 (n_84), .C0 (n_13), .C1 (n_89), .Y (n_104));
  NOR2XL g7045__1881(.A (n_11), .B (n_102), .Y (n_106));
  NAND2XL g7046__5115(.A (osc_rst), .B (n_103), .Y (n_105));
  OA22X1 g7052__7482(.A0 (n_69), .A1 (n_58), .B0
       (signal_creator_pulse_counter[2]), .B1 (n_87), .Y (n_101));
  OAI222XL g7053__4733(.A0 (n_4), .A1 (n_53), .B0 (n_40), .B1 (n_36),
       .C0 (n_181), .C1 (n_35), .Y (n_100));
  XNOR2X1 g7054__6161(.A (internal_oscillator_clk_cycle_counting[3]),
       .B (n_66), .Y (n_99));
  NAND4BXL g7055__9315(.AN (n_75), .B
       (internal_oscillator_clk_cycle_counting[2]), .C
       (internal_oscillator_clk_cycle_counting[3]), .D
       (internal_oscillator_clk_cycle_counting[4]), .Y (n_103));
  NAND3BXL g7056__9945(.AN (n_79), .B (n_58), .C (n_90), .Y (n_102));
  NAND2XL g7057__2883(.A (signal_creator_pulse_counter_sync[3]), .B
       (n_68), .Y (n_98));
  AND2X1 g7058__2346(.A (n_66), .B
       (internal_oscillator_clk_cycle_counting[3]), .Y (n_97));
  AND2X1 g7059__1666(.A (n_67), .B (signal_creator_pulse_counter[3]),
       .Y (n_96));
  MX2X1 g7061__7410(.A (signal_creator_is_first_run), .B (n_52), .S0
       (n_79), .Y (n_95));
  OA21X1 g7062__6417(.A0 (signal_creator_pulse_counter[2]), .A1 (n_82),
       .B0 (n_87), .Y (n_94));
  OAI2BB1X1 g7063__5477(.A0N (current_state[4]), .A1N (n_49), .B0
       (n_37), .Y (n_93));
  AOI211XL g7064__2398(.A0 (n_17), .A1 (n_25), .B0 (n_12), .C0 (n_67),
       .Y (n_92));
  AOI211XL g7065__5107(.A0 (n_8), .A1 (n_33), .B0 (n_2), .C0 (n_68), .Y
       (n_91));
  OR2X1 g7066__6260(.A (n_184), .B (n_74), .Y (n_89));
  OAI31X1 g7067__4319(.A0 (n_186), .A1 (n_16), .A2 (n_176), .B0 (n_73),
       .Y (n_88));
  AND2X1 g7068__8428(.A (n_82), .B (n_60), .Y (n_90));
  NAND3BXL g7071__5526(.AN (bit_gen_input[0]), .B (bit_gen_input[1]),
       .C (n_80), .Y (n_86));
  NAND3BXL g7072__6783(.AN (bit_gen_input[1]), .B (bit_gen_input[0]),
       .C (n_80), .Y (n_85));
  MX2X1 g7073__3680(.A (n_65), .B (n_64), .S0 (current_state[2]), .Y
       (n_84));
  AND2X1 g7074__1617(.A (n_78), .B (n_60), .Y (n_87));
  OAI2BB1X1 g7075__2802(.A0N (n_180), .A1N (n_57), .B0 (n_51), .Y
       (n_83));
  INVXL g7076(.A (n_81), .Y (n_80));
  NAND2BXL g7077__1705(.AN (n_59), .B
       (signal_creator_pulse_counter[4]), .Y (n_78));
  NOR2XL g7078__5122(.A (n_180), .B (n_56), .Y (n_77));
  AND2X1 g7079__8246(.A (n_59), .B (n_47), .Y (n_82));
  NAND2XL g7082__7098(.A (bit_gen_rst), .B (n_57), .Y (n_81));
  NAND2XL g7083__6131(.A (n_51), .B (n_56), .Y (n_79));
  INVXL g7084(.A (n_72), .Y (n_76));
  OAI211X1 g7085__1881(.A0 (internal_oscillator_clk_cycle_counting[1]),
       .A1 (internal_oscillator_clk_cycle_counting[0]), .B0
       (internal_oscillator_clk_cycle_counting[6]), .C0
       (internal_oscillator_clk_cycle_counting[5]), .Y (n_75));
  AOI221X1 g7086__5115(.A0 (D[2]), .A1 (n_6), .B0 (D[3]), .B1 (n_7),
       .C0 (n_46), .Y (n_74));
  AOI32X1 g7087__7482(.A0 (current_state[4]), .A1 (current_state[0]),
       .A2 (n_27), .B0 (current_state[1]), .B1 (n_48), .Y (n_73));
  AOI32X1 g7088__4733(.A0 (n_202), .A1 (n_40), .A2 (n_41), .B0
       (current_state[3]), .B1 (n_179), .Y (n_72));
  OAI32X1 g7089__6161(.A0 (n_10), .A1 (n_186), .A2 (n_178), .B0 (n_13),
       .B1 (n_50), .Y (n_71));
  XNOR2X1 g7090__9315(.A (internal_oscillator_clk_cycle_counting[2]),
       .B (n_24), .Y (n_70));
  NAND3BXL g7091__9945(.AN (signal_creator_pulse_counter_sync[6]), .B
       (n_33), .C (n_44), .Y (n_69));
  OAI221X1 g7092__2883(.A0 (n_30), .A1 (n_202), .B0 (n_23), .B1
       (n_182), .C0 (n_34), .Y (n_65));
  OAI221X1 g7093__2346(.A0 (n_31), .A1 (n_202), .B0 (n_29), .B1 (n_10),
       .C0 (n_183), .Y (n_64));
  AOI21XL g7094__1666(.A0 (current_state[3]), .A1 (n_38), .B0 (n_45),
       .Y (n_63));
  NOR2XL g7095__7410(.A (n_8), .B (n_33), .Y (n_68));
  NOR2XL g7096__6417(.A (n_17), .B (n_25), .Y (n_67));
  AND2X1 g7097__5477(.A (n_24), .B
       (internal_oscillator_clk_cycle_counting[2]), .Y (n_66));
  INVXL g7098(.A (n_55), .Y (n_62));
  INVXL g7099(.A (n_54), .Y (n_61));
  INVX1 g7100(.A (n_56), .Y (n_57));
  OAI211X1 g7101__2398(.A0 (signal_creator_pulse_counter_sync[1]), .A1
       (signal_creator_pulse_counter_sync[0]), .B0
       (signal_creator_enable_pulse_counting_sync), .C0 (n_33), .Y
       (n_55));
  OAI211X1 g7102__5107(.A0 (signal_creator_pulse_counter[1]), .A1
       (signal_creator_pulse_counter[0]), .B0
       (signal_creator_enable_pulse_counting), .C0 (n_25), .Y (n_54));
  XNOR2X1 g7103__6260(.A (n_10), .B (n_42), .Y (n_53));
  NAND4BXL g7104__4319(.AN (signal_creator_current_state[3]), .B
       (signal_creator_current_state[1]), .C (n_5), .D (n_32), .Y
       (n_60));
  NAND4BXL g7105__8428(.AN (signal_creator_current_state[1]), .B
       (signal_creator_current_state[3]), .C (n_5), .D (n_32), .Y
       (n_59));
  NAND3BXL g7106__5526(.AN (signal_creator_current_state[0]), .B
       (signal_creator_current_state[4]), .C (n_43), .Y (n_58));
  NAND3BXL g7107__6783(.AN (signal_creator_current_state[4]), .B
       (signal_creator_current_state[0]), .C (n_43), .Y (n_56));
  INVXL g7108(.A (n_51), .Y (n_52));
  AOI211XL g7109__3680(.A0 (n_183), .A1 (n_186), .B0 (n_187), .C0
       (n_14), .Y (n_50));
  OR2X1 g7110__1617(.A (n_10), .B (n_42), .Y (n_49));
  OAI211X1 g7111__2802(.A0 (n_18), .A1 (n_3), .B0 (current_state[0]),
       .C0 (n_4), .Y (n_48));
  NAND2XL g7112__1705(.A (n_32), .B (n_43), .Y (n_51));
  OAI33X1 g7113__5122(.A0 (F_BIT_LOCATOR[2]), .A1 (n_20), .A2 (n_202),
       .B0 (n_19), .B1 (F_BIT_LOCATOR[3]), .B2 (n_182), .Y (n_46));
  NOR4BX1 g7114__8246(.AN (INTERPRETED_ADDR[6]), .B (F_BIT_LOCATOR[6]),
       .C (n_184), .D (n_177), .Y (n_45));
  NOR4X1 g7115__7098(.A (signal_creator_pulse_counter_sync[5]), .B
       (signal_creator_pulse_counter_sync[4]), .C
       (signal_creator_pulse_counter_sync[3]), .D
       (signal_creator_pulse_counter_sync[2]), .Y (n_44));
  NAND3BXL g7116__6131(.AN (n_5), .B (n_26), .C (n_32), .Y (n_47));
  OAI21XL g7118__1881(.A0 (current_state[3]), .A1 (n_179), .B0 (n_177),
       .Y (n_41));
  AND2X1 g7120__5115(.A (n_26), .B (n_5), .Y (n_43));
  NAND2BXL g7121__7482(.AN (current_state[1]), .B (n_27), .Y (n_42));
  XNOR2X1 g7123__4733(.A (internal_oscillator_clk_cycle_counting[0]),
       .B (internal_oscillator_clk_cycle_counting[1]), .Y (n_39));
  NOR3BXL g7124__6161(.AN (INTERPRETED_ADDR[7]), .B (F_BIT_LOCATOR[7]),
       .C (n_176), .Y (n_38));
  NAND3BXL g7125__9315(.AN (n_185), .B (current_state[1]), .C
       (current_state[0]), .Y (n_37));
  OA22X1 g7126__9945(.A0 (n_184), .A1 (n_16), .B0 (n_187), .B1 (n_18),
       .Y (n_36));
  OA21X1 g7127__2883(.A0 (n_184), .A1 (n_203), .B0 (n_176), .Y (n_35));
  OA22X1 g7128__2346(.A0 (D[1]), .A1 (n_183), .B0 (D[0]), .B1 (n_177),
       .Y (n_34));
  AOI22XL g7129__1666(.A0 (n_10), .A1 (n_3), .B0 (current_state[0]),
       .B1 (n_186), .Y (n_40));
  NOR2BX1 g7130__7410(.AN (INTERPRETED_ADDR[4]), .B (F_BIT_LOCATOR[4]),
       .Y (n_31));
  NOR2BX1 g7131__6417(.AN (INTERPRETED_ADDR[0]), .B (F_BIT_LOCATOR[0]),
       .Y (n_30));
  NOR2BX1 g7132__5477(.AN (INTERPRETED_ADDR[5]), .B (F_BIT_LOCATOR[5]),
       .Y (n_29));
  NAND2XL g7133__2398(.A (osc_rst), .B (n_174), .Y (n_28));
  NAND2XL g7134__5107(.A (signal_creator_pulse_counter_sync[1]), .B
       (signal_creator_pulse_counter_sync[0]), .Y (n_33));
  NOR2XL g7135__6260(.A (signal_creator_current_state[0]), .B
       (signal_creator_current_state[4]), .Y (n_32));
  NOR2BX1 g7136__4319(.AN (INTERPRETED_ADDR[1]), .B (F_BIT_LOCATOR[1]),
       .Y (n_23));
  NOR2XL g7137__8428(.A (signal_creator_pulse_counter[0]), .B (n_12),
       .Y (n_22));
  NOR2XL g7138__5526(.A (signal_creator_pulse_counter_sync[0]), .B
       (n_2), .Y (n_21));
  NOR2XL g7139__6783(.A (n_175), .B (n_181), .Y (n_27));
  NOR2XL g7140__3680(.A (signal_creator_current_state[1]), .B
       (signal_creator_current_state[3]), .Y (n_26));
  NAND2XL g7141__1617(.A (signal_creator_pulse_counter[1]), .B
       (signal_creator_pulse_counter[0]), .Y (n_25));
  AND2X1 g7142__2802(.A (internal_oscillator_clk_cycle_counting[0]), .B
       (internal_oscillator_clk_cycle_counting[1]), .Y (n_24));
  INVXL g7143(.A (INTERPRETED_ADDR[2]), .Y (n_20));
  INVXL g7144(.A (INTERPRETED_ADDR[3]), .Y (n_19));
  INVX1 g7145(.A (n_185), .Y (n_18));
  INVXL g7146(.A (signal_creator_pulse_counter[2]), .Y (n_17));
  INVX1 g7147(.A (n_181), .Y (n_16));
  INVXL g7148(.A (internal_oscillator_clk_cycle_counting[0]), .Y
       (n_15));
  INVXL g7149(.A (n_202), .Y (n_14));
  INVXL g7151(.A (signal_creator_enable_pulse_counting), .Y (n_12));
  INVX1 g7153(.A (current_state[0]), .Y (n_10));
  INVXL g7154(.A (signal_creator_pulse_counter_sync[4]), .Y (n_9));
  INVXL g7155(.A (signal_creator_pulse_counter_sync[2]), .Y (n_8));
  INVXL g7156(.A (n_183), .Y (n_7));
  INVXL g7157(.A (n_177), .Y (n_6));
  INVX1 g7158(.A (signal_creator_current_state[2]), .Y (n_5));
  INVX1 g7160(.A (n_186), .Y (n_3));
  INVX1 g7161(.A (signal_creator_enable_pulse_counting_sync), .Y (n_2));
  XOR2XL g2__1705(.A (osc_clk), .B (n_103), .Y (n_0));
  DFFRX1 \current_state_reg[4] (.RN (osc_rst), .CK (clk), .D (n_93), .Q
       (current_state[4]), .QN (n_4));
endmodule

